### ISSUE TITLE
Implement the first version of the component

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-angular#1]
A follow-up of https://github.com/ckeditor/ckeditor5/issues/1020.

Related https://github.com/ckeditor/ckeditor5/issues/1002.

**Comment by Reinmar** [comment]
This package should be called `@ckeditor/ckeditor5-angular`.

Let's make a quick review of this pkg and publish its first dev preview quickly, just like with the React integration (https://github.com/ckeditor/ckeditor5-react/issues/5).
