### ISSUE TITLE
How to integrate CKEditor5 Comments and Track Changes with Angular

### ISSUE THREAD

**Issue by existentialist1888** [ckeditor/ckeditor5-angular#100]
I have gone through the instructions of creating a custom build to add track changes with Angular and believe I have a working build, it works outside of Angular anyway.  However, when creating the HTML page for the CKEditor with track changes, you need to specify the div that's being used for the sidebar.  Without specifying the sidebar element I get the error: "sidebar-missing-container: Missing container element.", which can be duplicated if I remove that section in the non Angular implementation.  How do you specify this as well as the additional parameters, such as the users and suggestions data for the Angular version of CKEditor5?

**Comment by Mgsy** [comment]
Hello, you can take a look at our Angular integration sample for CKEditor 5 + real-time collaboration. You'll be able to analyse the code and see how the sidebar element is handled - https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-angular.

Please, let us know if you managed to solve your problem.

**Comment by existentialist1888** [comment]
Thank you for responding.  That example helped a lot and it looks like I'm on my way, much further than I was this morning, anyway.  However, now none of the formatting is being displayed in the editor.  The text is shown but it all looks like standard text with the exception of hyperlinks.  I've attached two screen shots, one showing the way it should be displayed and one showing the way that it is being displayed.  No errors are being thrown that I can tell and nothing is showing up in the developer tools of the browser.  I've tried it with two different builds of CKEditor, including the standard Classic Build.  Any idea of what might be going on?
 
 
----- Original message -----From: Kacper Tomporowski <notifications@github.com>To: ckeditor/ckeditor5-angular <ckeditor5-angular@noreply.github.com>Cc: existentialist1888 <sbroadhe@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [ckeditor/ckeditor5-angular] How to integrate CKEditor5 Comments and Track Changes with Angular (#100)Date: Mon, May 6, 2019 1:01 AM 
Hello, you can take a look at our Angular integration sample for CKEditor 5 + real-time collaboration. You'll be able to analyse the code and see how the sidebar element is handled - https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-angular.
Please, let us know if you managed to solve your problem.

**Comment by Mgsy** [comment]
I'm glad that our sample helped you. Unfortunately, you didn't attach any screenshot. Could you try to upload it via GitHub?

**Comment by existentialist1888** [comment]
I apologize that the images didn't come through.  I responded to the email and I'm almost positive I attached them there, but it looks like they didn't get uploaded to github.  After looking at them a little closer it looks like some of the formatting came through, but not all.  For instance, strikethrough and highlight is working, but the basics like bold and itallics are not shown.  Not only that, but it just looks like the format as a whole looks different.  The implementation is pretty straightforward, I haven't tried to do anything fancy at this point so any help in debugging what's going on in the Editor would be helpful.
<img width="1282" alt="Screen Shot 2019-05-06 at 2 51 28 PM" src="https://user-images.githubusercontent.com/50179434/57311816-38699580-70a1-11e9-9076-580070950fcf.png">
<img width="1413" alt="Screen Shot 2019-05-06 at 2 51 05 PM" src="https://user-images.githubusercontent.com/50179434/57311817-38699580-70a1-11e9-8eef-cc2f7f2d6d0a.png">

**Comment by ma2ciek** [comment]
Hi @existentialist1888!

> Update: Upon further research it appears that the css (scss) file that we're using for the application are getting used inside the editor. Therefore, global settings that we have for various tags are getting used inside the editor so it looks like they're not getting set at all. I've noticed this is happening even with the straight ClassicBuild so I have not included the stylesheet parser. I've tried disabling it using the removePlugins option of the config, but it's not working.

The editor isn't run in the iframe, so every CSS selector added globally might also affect the CKEditor5 content. We can't do much with it, that's how the CSS works. IMO the best way to solve it is to identify incorrect selectors one by one and make them more precise, so they won't affect the editor content.

Angular supports component style scoping, which makes the style encapsulation pretty easy to achieve.

I don't understand the latter part of your comment. That's has nothing to do with CKEditor5 plugins. Every CKEditor 5 build or other editors will fall into this problem.

**Comment by ma2ciek** [comment]
I think that the issue was discussed enough so we can close it. Feel free to leave a comment if you still struggle with the integration.
