### ISSUE TITLE
Failed to input Chinese with Bold tag

### ISSUE THREAD

**Issue by samilywang** [ckeditor/ckeditor5-angular#101]
![error](https://user-images.githubusercontent.com/13418696/57190531-bddc3100-6f4d-11e9-87fb-e8ebbf164c77.gif)

Just like the gif shows, first I click the bold tag on, then I tried to input some Chinese words. But the bold tag auto unfocused and the Chinese words are not bold.

The same situation as italic, underline, subscript, superscript...

Is this a bug or I need to do some config to correct this situation?

**Comment by Mgsy** [comment]
Hello, this issue has been fixed in https://github.com/ckeditor/ckeditor5-engine/pull/1730 and will be included in the next release.
