### ISSUE TITLE
How to set focus on the CKEditor 5 editor?

### ISSUE THREAD

**Issue by M-Blobby** [ckeditor/ckeditor5-angular#106]
Hello,

Does anyone know how to set focus in CKEditor 5 component's editor?
My `<ckeditor>` component is disabled by default, and I would like to set the focus when the user presses a button.

I tried something like this, but the `elementRef` is private :

```javascript
addFocus(): void {
  this.isEditing = true;
  this.ckEditor.elementRef.nativeElement.focus();
}
```

**Comment by ma2ciek** [comment]
Hi @M-Blobby,

the `<ckeditor>` component exposes the `editorInstance`, which is an instance of CKEditor 5 editor, on which you can use the `editorInstance.editing.view.document.focus()` method to focus the editable element.

**Comment by M-Blobby** [comment]
Hello @ma2ciek ,

Thank you a lot for your help :). Just in case someone has the same problem, I followed the ma2ciek help but without 'document' (else I got the error "the function focus is not defined") so :

```
editorInstance.editing.view.focus();
```

**Comment by tarcisiocipriano** [comment]
Where does this "editorInstance" come from?
I'm trying to use the ViewChild, to a local reference on <ckeditor> but without success :(

**Comment by ma2ciek** [comment]
Hi @tarcisiocipriano, 

See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#accessing-the-editor-instance.

**Comment by orlandovallejos** [comment]
This is what I did:

```
onReady={ editor => {
      console.log( 'Editor is ready to use!', editor );

      editor.focus();
  } }
```

And it worked!

**Comment by Prince890840** [comment]
I face a problem that focus is working well. when I click on the reject button, but parrelally I do 2nd scenario, which is to `scroll` that element into view both cases do not work simultaneously.

`const scrollToElement = () => {
  const element = document.getElementsByClassName('ck-editor');
  if (element[0]) {
    element[0].scrollIntoView({ behavior: 'smooth' });
  }
};`

1. ![image](https://github.com/ckeditor/ckeditor5-angular/assets/77726300/8166350f-b14c-44bb-bd93-74e4b986be53)
2. ![image](https://github.com/ckeditor/ckeditor5-angular/assets/77726300/151d8548-7f62-4c1f-bdd1-dfff19862a6c)
3. ![image](https://github.com/ckeditor/ckeditor5-angular/assets/77726300/8afdeb12-c1e4-4037-bc0f-6abf180cd056)

My question is why are both cases not worked parallelly? I used this also. `editorInstance.editing.view.focus()`
