### ISSUE TITLE
InlineEditor's balloon is outside of app root. How can I define a container for that balloon?

### ISSUE THREAD

**Issue by grimace** [ckeditor/ckeditor5-angular#107]
I'm using angular and ckeditor5 and would like to create an InlineEditor on the fly ( aka, someone clicks on an element on the page ).  When the balloon element for the InlineEditor get's added to the page, it gets added outside of app-root and so the balloon is never shown.

Is there a way to specify the container where the balloon get's added to the dom?
I can currently edit the text where I click but there is no balloon for styling the text.

**Comment by ma2ciek** [comment]
This balloon can be taken using `editor.ui.view.panel.element`. So once the editor is ready you'll be able to move it somewhere using the [element.appendChild()`](https://developer.mozilla.org/pl/docs/Web/API/Element/appendChild).
