### ISSUE TITLE
What events do we want to propagate from the editor?

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#11]
For now there're 4 events that are propagated via emitters:

* ready - once the editor is ready to use
* focus - on the editor view document `focus` event
* blur - on the editor view document `blur` event
* change - on the editor model document `change:data` event

Are they enough? Or should we add more?

Note that these angular emitters will emit the original CKEditor event and the editor, so if someone would need some deep integration he can always get the editor instance.

Should we provide similar API in https://github.com/ckeditor/ckeditor5-angular and https://github.com/ckeditor/ckeditor5-react?

cc @Reinmar @pjasiun @pomek

**Comment by oleq** [comment]
IMO both adapters should mirror the API as much as frameworks will allow – for easier maintenance and consistency.

**Comment by ma2ciek** [comment]
Hi, @vugar005.

We won't propagate so specific events, because they depend on plugins that you have included in the CKE5 build.

If you want to listen to some specific event, you can always get the editor from the component and plug your listener to some of the available hooks.

**Comment by ma2ciek** [comment]
I'm closing it since we have it solved and at some point, it's about doubling the API we provide. Anyone who wants to listen to some specific event can hook the listener to some of the editor's entities.
