### ISSUE TITLE
Retrieve cursor position / selection with events

### ISSUE THREAD

**Issue by maximelafarie** [ckeditor/ckeditor5-angular#110]
Hi!
According to the following implementation:

```html
<ckeditor [editor]="Editor"
                 (change)="onChange($event)"
                 (blur)="blurEvent($event)"
                 placeholder="Some stuff"
                 formControlName="message"></ckeditor>
```

I would like to retrieve the cursor position or the selection when `blur` event occurs, but I can't find how to get these values.
According to [the documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#blur) I can retrieve the editor instance which is given by the `Output()` event. And in some topics on the web or from the ckeditor support, I read that it was possible to get this values with the `getSelection()` method (but that was for CKE4, not 5).

```typescript
public blurEvent(e: BlurEvent) {
  const selection = el.editor.model.getSelectedContent();
  console.log('ckedit', selection);
}
```

So with that, I got the following error:

```typescript
ERROR TypeError: Cannot read property 'getFirstRange' of undefined
```

Is there any way to get these values with this actual implementation?

EDIT: I guess I can do something with [DocumentSelection](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html) but I'm not sure.

Regards! 🖖

**Comment by Mgsy** [comment]
Hello, you're right - you can get the current selection from [`editor.model.document.selection`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_documentselection-DocumentSelection.html). It exposes API which you can use to obtain the current selection.

**Comment by maximelafarie** [comment]
Awesome @Mgsy, it works perfectly with 
```typescript
editor.model.change(writer => {
  editor.model.insertContent(
    writer.createText(newText), editor.model.document.selection, 'in');
});
```
Thank you for your fast answer! Regards! 🖖
