### ISSUE TITLE
plugin installation

### ISSUE THREAD

**Issue by sergiorodriguez82** [ckeditor/ckeditor5-angular#113]
Hi, nice work with this editor!

I'm trying to use the basic build with the alignment plugin. I'm creating an angular app.
Is there anyway I can use it without creating my own build? could you please guide me!
Thanks!

**Comment by Mgsy** [comment]
Hello, our builds contain a basic set of plugins and it's up to the user which features he wants to activate. The only way to add plugins to the editor is to create a custom build. You can find a guide about it [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).
