### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'ckeditor'

### ISSUE THREAD

**Issue by 704826318** [ckeditor/ckeditor5-angular#114]
Can't bind to 'ngModel' since it isn't a known property of 'ckeditor'. ("<ckeditor [ERROR ->][(ngModel)]="data" [editor]="Editor"></ckeditor>")

**Comment by ma2ciek** [comment]
That error will happen because you didn't add the `FormsModule` to the `imports` array in the module where the `CKEditorModule` is imported.

**Comment by smallcoderofme** [comment]
**For help！！！**
![image](https://user-images.githubusercontent.com/18281729/80348298-28ddf080-88a0-11ea-8967-e3c8d86ac416.png)
![image](https://user-images.githubusercontent.com/18281729/80348351-3eebb100-88a0-11ea-8a13-020bb5609b21.png)
![image](https://user-images.githubusercontent.com/18281729/80348380-4e6afa00-88a0-11ea-8d24-bdf10c29e358.png)
The "AuthorizeModule" is submodule of app.

**Comment by smallcoderofme** [comment]
https://github.com/ckeditor/ckeditor5-angular/issues/195#issue-607331485

**Comment by faiezPanopticanalytics** [comment]
Hello ma2ciek

i am using ckedior fom CDN link and it can't bind data with ng model
