### ISSUE TITLE
Could not add Highlight plugin in ckEditor classic build

### ISSUE THREAD

**Issue by kapilthakkar2912** [ckeditor/ckeditor5-angular#115]
Hello,

I'm trying  to add **Highlight** plugin but its how to unavailable.
I have installed that plugin still same console message found.

Version Details:
Angular 7
ckEditor 5

**Comment by kapilthakkar2912** [comment]
i'm using angular 7 and ckEditor 5

**Comment by Mgsy** [comment]
Hi, you should prepare your custom build with the highlight plugin. Please, take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).

**Comment by kapilthakkar2912** [comment]
Thanks @Mgsy.

But in custom build image related option not working(imageStyle:alignLeft,imageStyle:alignRight) .

**Comment by Mgsy** [comment]
>But in custom build image related option not working(imageStyle:alignLeft,imageStyle:alignRight) .

Can you check whether there is some error in the console? 

Anyway, did you define image styles and toolbar config? At first, you should import the [`ImageToolbar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagetoolbar-ImageToolbar.html) and [`ImageStyles`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagestyle-ImageStyle.html) plugins, then set the configuration:

```js
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        image: {
            // You need to configure the image toolbar, too, so it uses the new style buttons.
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight' 
        ],

            styles: [
                // This option is equal to a situation where no style is applied.
                'full',

                // This represents an image aligned to the left.
                'alignLeft',

                // This represents an image aligned to the right.
                'alignRight'
            ]
        }
    } )
    .then( ... )
    .catch( ... );
```

Please, take a look at the [image plugin documentation](https://ckeditor.com/docs/ckeditor5/latest/features/image.html).

**Comment by kapilthakkar2912** [comment]
Hello,
I have added following imports,
```
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
```

and following code in .js file.

```
export default class ClassicEditorWithRealTimeCollaboration extends BaseEditor {}

ClassicEditorWithRealTimeCollaboration.builtinPlugins = [
	Alignment,
	Autoformat,
	BlockQuote,
	Bold,
	EasyImage,
	Essentials,
	FontFamily,
	FontSize,
	Heading,
	Highlight,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Italic,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	RemoveFormat,
	Strikethrough,
	Table,
	TableToolbar,
	Underline,
	UploadAdapter
];

ClassicEditorWithRealTimeCollaboration
    .create( document.querySelector( '#editor' ), {
        image: {
            // You need to configure the image toolbar, too, so it uses the new style buttons.
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight' 
        ],

            styles: [
                // This option is equal to a situation where no style is applied.
                'full',

                // This represents an image aligned to the left.
                'alignLeft',

                // This represents an image aligned to the right.
                'alignRight'
            ]
        }
    } )
    .then(  )
    .catch( );
ClassicEditorWithRealTimeCollaboration.defaultConfig = {
	toolbar:{ 
		items :[
		'heading',
		'|',
		'fontsize',
		'fontfamily',
		'|',
		'bold',
		'italic',
		'underline',
		'strikethrough',
		'removeFormat',
		'highlight',
		'|',
		'alignment',
		'|',
		'numberedList',
		'bulletedList',
		'|',
		'link',
		'blockquote',
		'imageUpload',
		'insertTable',
		'|',
		'undo',
		'redo',
	],
	viewportTopOffset: 118,
}
	
};
```


still not working for me.

**Comment by Mgsy** [comment]
The code should be added to the editor configuration, in your case it will be `ClassicEditorWithRealTimeCollaboration.defaultConfig`. I've modified your code:

```js
export default class ClassicEditorWithRealTimeCollaboration extends BaseEditor {}

ClassicEditorWithRealTimeCollaboration.builtinPlugins = [
	Alignment,
	Autoformat,
	BlockQuote,
	Bold,
	EasyImage,
	Essentials,
	FontFamily,
	FontSize,
	Heading,
	Highlight,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Italic,
	Link,
	List,
	Paragraph,
	PasteFromOffice,
	RemoveFormat,
	Strikethrough,
	Table,
	TableToolbar,
	Underline,
	UploadAdapter
];

ClassicEditorWithRealTimeCollaboration.defaultConfig = {
        image: {
            // You need to configure the image toolbar, too, so it uses the new style buttons.
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight' 
            ],

            styles: [
                // This option is equal to a situation where no style is applied.
                'full',

                // This represents an image aligned to the left.
                'alignLeft',

                // This represents an image aligned to the right.
                'alignRight'
            ]
        },
	toolbar: { 
		items :[
		'heading',
		'|',
		'fontsize',
		'fontfamily',
		'|',
		'bold',
		'italic',
		'underline',
		'strikethrough',
		'removeFormat',
		'highlight',
		'|',
		'alignment',
		'|',
		'numberedList',
		'bulletedList',
		'|',
		'link',
		'blockquote',
		'imageUpload',
		'insertTable',
		'|',
		'undo',
		'redo',
	],
	viewportTopOffset: 118,
    }
	
};
```

**Comment by kapilthakkar2912** [comment]
Hello @Mgsy ,

Thank you for your quick replay.
Still image toolbar is not working for me.

can you provide any demo link ?

Best Regards.
Thank you.

**Comment by Mgsy** [comment]
>Still image toolbar is not working for me.

Did you rebuild the editor (`npm run build` in the main folder)? Do you have any errors in the console?

**Comment by kapilthakkar2912** [comment]
I have rebuild twice in `/vendor/ckeditor5/` folder and no any error in console.

**Comment by Mgsy** [comment]
I'm sorry, but I can't reproduce your issue. 

As I see you use a code from our CKEditor 5 with real-time collaboration for the angular sample. It has `Highlight` plugin enabled by default, as well as configured image styles. 

Please, clone the repository once again and follow the instructions in README - https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-angular.

If you don't want to work on our sample, here is a [CKEditor 5 and Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html), so you'll be able to integrate it on your own.

**Comment by kapilthakkar2912** [comment]
i'll test and let you know.

Thank you for your quick replay.

Thank you!

**Comment by kapilthakkar2912** [comment]
I have  used "https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-angular."  build and its working fine.

Thanks @Mgsy !
