### ISSUE TITLE
Image toolbar not working properly 

### ISSUE THREAD

**Issue by kapilthakkar2912** [ckeditor/ckeditor5-angular#116]
When i upload the image at that time toolbar is working properly but when i come for edit and click on image at that time i can not see toolbar ( Arrow is there ).

Please refer screenshot.

![ckEditorImageToolbar](https://user-images.githubusercontent.com/19683659/59331108-f3401100-8ca7-11e9-81d0-4d714b880209.png)

same issue happening with table toolbar. 
![ckEditorTableToolbar](https://user-images.githubusercontent.com/19683659/59331318-85481980-8ca8-11e9-8b06-c33c85b6e433.png)

**Comment by Mgsy** [comment]
Hello, I can't reproduce your issue. Can you provide exact steps to reproduce the problem? Do you have any errors in the console?

**Comment by kamalakkannan1984** [comment]
Resolved
YourComponent.html
<ckeditor [editor]="Editor"   data="{{editorData}}" (ready)="onReady($event)"></ckeditor>

YourComponent.ts
public onReady($event : any) {
        		
		$event.plugins.get('FileRepository').createUploadAdapter = function (loader: any) {
			console.log(loader);
			return new UploadAdapter(loader);
		  };
    }
This is you make another class below your component 
export class UploadAdapter {
	private loader: any;
	constructor(loader: any) {
	  this.loader = loader;
	  console.log(this.readThis(loader.file));
	}
  
	public upload(): Promise<any> {
	  //"data:image/png;base64,"+ btoa(binaryString) 
	  return this.readThis(this.loader.file);
	}
  
	readThis(file: File): Promise<any> {	 
	  let imagePromise: Promise<any> = new Promise((resolve, reject) => {
		var myReader: FileReader = new FileReader();
		myReader.onloadend = (e) => {
		  let image = myReader.result;		 
		  return { default: "data:image/png;base64," + image };
		  resolve();
		}		
		myReader.readAsBinaryString;
	  });
	  return imagePromise;
	}
  
  }

**Comment by kapilthakkar2912** [comment]
Sorry, I did't get you

**Comment by kapilthakkar2912** [comment]
Sorry, I did't get you

**Comment by ma2ciek** [comment]
It looks like a CSS issue, not related to CKEditor 5 at all.

**Comment by kapilthakkar2912** [comment]
Hello @ma2ciek,
Can you give me some css class name so i can find similar name in my project.

Thank you !
