### ISSUE TITLE
Reset formcontrol on a ckeditor

### ISSUE THREAD

**Issue by LouisAugry** [ckeditor/ckeditor5-angular#118]
Hey ! 

I've a formControl on a ckeditor, and when i'm reseting the formControl or simply patchValue null or empty string, the ckeditor replace this with ```<p>&nbsp;</p>```

**Comment by ma2ciek** [comment]
When the editor is empty the `editor.getData()` should return an empty string, however, the DOM will contain the `<p>&nbsp;</p>` because of the auto paragraphing. Otherwise, you would start writing the plain text in the editor root.

Could you clarify the issue? From the above, I don't simply understand what do you want to achieve and what's the real problem is.

**Comment by oleq** [comment]
Maybe we could somehow allow using the [`trim` option in `getData`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_utils_dataapimixin-DataApiMixin.html#function-getData)?

**Comment by ma2ciek** [comment]
But the `trim: 'empty'` is set by default so the `editor.getData()` should return an empty string by default.

**Comment by oleq** [comment]
So how come https://github.com/ckeditor/ckeditor5-angular/blob/1ef5947aa81acb8c692f20dad556e0ec1227224d/src/ckeditor/ckeditor.component.ts#L269 returns dirty data? Because it's editor data we're talking about @LouisAugry, right? Not the DOM?

**Comment by LouisAugry** [comment]
I only play with the formControl. Not with the editor directly. When I reset my formControl, the value isn't null but <p>&nbsp;</p>. It's the problem here

**Comment by oleq** [comment]
Any chance for a live demo somewhere?

**Comment by ma2ciek** [comment]
I've played with and I've been logging the value after the form controller reset - https://github.com/ckeditor/ckeditor5-angular/blob/master/src/app/demo-reactive-form/demo-reactive-form.component.ts#L37. The value was correct (`''`).
