### ISSUE TITLE
Custom Image upload Adapter not working after moving to new version of ckeditor5

### ISSUE THREAD

**Issue by manyaml** [ckeditor/ckeditor5-angular#119]
Hello
custom image upload used to work before but after I migrated to a new version, I started seeing some bugs.

```js
TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
```

is there anything that I'm missing?
https://stackblitz.com/edit/angular-qwm6py?file=package.json

new package.json looks like this 
```json
{
  "name": "angular",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.6",
    "@angular/common": "^7.2.6",
    "@angular/compiler": "^7.2.6",
    "@angular/core": "^7.2.6",
    "@angular/forms": "^7.2.6",
    "@angular/platform-browser": "^7.2.6",
    "@angular/platform-browser-dynamic": "^7.2.6",
    "@angular/router": "^7.2.6",
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "@ckeditor/ckeditor5-build-classic": "^12.2.0",
    "@ckeditor/ckeditor5-core": "^12.1.1",
    "@ckeditor/ckeditor5-upload": "11.0.2",
    "@ckeditor/ckeditor5-clipboard": "11.0.2",
    "@ckeditor/ckeditor5-adapter-ckfinder": "11.0.2",
    "core-js": "^2.6.5",
    "rxjs": "^6.4.0",
    "zone.js": "^0.8.29"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```

**Comment by Mgsy** [comment]
Hi!

>custom image upload used to work before but after I migrated to a new version

Can you be more specific? Which package did you update?

I can see in your code that you made your upload adapter on top of the [base64uploadadapter](https://github.com/ckeditor/ckeditor5-upload/blob/master/src/base64uploadadapter.js). Please, take a look at our [Custom image upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html) guide to see how to implement it properly.

**Comment by manyaml** [comment]
HI
https://stackblitz.com/edit/angular-qwm6py?file=package.json. when @ckeditor/ckeditor5-build-classic version is set to "11.2.0" image upload worked without any issues. If I change that package version to 12.2.0 I'm getting some error. you can use that example to get that error( just change the version to 12.2.0 and try to upload an image)

**Comment by manyaml** [comment]
Also is there any tentative date for Base64UploadAdapter availability?

**Comment by Mgsy** [comment]
We've just released new packages (also with Base64UploadAdapter). Please, update your dependencies (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)) and check whether your issue still occurs.
