### ISSUE TITLE
npm run e2e fails

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-angular#12]
Because of missing `e2e/protractor.conf.js` file.

![image](https://user-images.githubusercontent.com/2270764/43060319-ad46ebac-8e50-11e8-87bc-a1d21eabe26e.png)

**Comment by ma2ciek** [comment]
Don't install it via `lerna`. Remove `node_modules` and run `npm install`.

**Comment by pomek** [comment]
I did it via `npm i`.

**Comment by ma2ciek** [comment]
Ok. I see. Default angular `.gitignore` file includes `e2e/*.js` files. Don't know why. I'll change it.

**Comment by ma2ciek** [comment]
Fix is added to the https://github.com/ckeditor/ckeditor5-angular/pull/10, which contains other improvements.
