### ISSUE TITLE
Cannot read property "modal" of undefined

### ISSUE THREAD

**Issue by ChuchunovMV** [ckeditor/ckeditor5-angular#120]
Hi I have been trying to integrate the ckeditor5 with angular app and followed instruction given in the document.

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html

https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html

Normal ckeditor5 is working but when i'm trying to enable ckfinder with it, it is not working. 
As per the doc, when we click on the ckfinder button , it should open the modal box but right now its not opening "

[ScreenShot](https://i.stack.imgur.com/2XTU8.png)

Appreciate your time and thanks in advance

I'm pasting my files for your reference

`
<ckeditor 
    [config]="_config"
    [editor]="Editor" 
    [ngModel]="_value" 
    (ngModelChange)="modelChange($event)">        
</ckeditor>
`

`
public Editor = ClassicEditor;
public _config = {
        toolbar: [
            'ckfinder',
            'heading',
            '|',
            'undo',
            'redo',
            '|',
            'bulletedList',
            'numberedList',
            '|',
            'bold',
            'italic',
            'link',
            'blockQuote'
        ],
        language: 'ru'
    };
`

**Comment by Mgsy** [comment]
Hello, did you add this part to the document?:
```html
<script src="https://example.com/ckfinder/ckfinder.js"></script>
```

You can use our resources:
```html
<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>
```

**Comment by ChuchunovMV** [comment]
> Hello, did you add this part to the document?:
> 
> ```
> <script src="https://example.com/ckfinder/ckfinder.js"></script>
> ```
> 
> You can use our resources:
> 
> ```
> <script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>
> ```
No i didn't. Thanks you
