### ISSUE TITLE
What exactly how can I place "ClassicEditor.create( document ....." on my project

### ISSUE THREAD

**Issue by JamesKrub** [ckeditor/ckeditor5-angular#121]
I has a angular project that 
    `import { CKEditorModule } from '@ckeditor/ckeditor5-angular';` 
in my module

and
    `import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';` 
in my component 

and the I decleared my variable like this ` public Editor = ClassicEditor;`

so I have my a little question, How can I add font color to my editor by using
```
ClassicEditor
    .create( document.querySelector( '#editor' ), {
        fontColor: {
            colors: [
                {
                    color: 'hsl(0, 0%, 0%)',
                    label: 'Black'
                },
            ]
        },
        fontBackgroundColor: {
            colors: [
                {
                    color: 'hsl(0, 75%, 60%)',
                    label: 'Red'
                },
            ]
        },
        toolbar: [
            'heading', 'bulletedList', 'numberedList', 'fontColor', 'fontBackgroundColor', 'undo', 'redo'
        ]
    } )
    .then( )
    .catch();
```
I have read all the instruction like create component in ` ./src/ckeditor` bit I don't get it.
So my question is how can you explain me the easiest and simple way to put these code.

**Comment by Mgsy** [comment]
cc @ma2ciek

**Comment by ma2ciek** [comment]
Hello @JamesKrub,

The *Font Color* and *Font Background Color* features aren't a part of the default `ClassicEditor` build, thus you need to [create such build on your own](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and then import that build in the Angular component scope.

**Comment by JavaSparker** [comment]
I have the same problem, any help plaise
