### ISSUE TITLE
cannot find @ckeditor/ckeditor5-build-classic in angular 8

### ISSUE THREAD

**Issue by rajrs** [ckeditor/ckeditor5-angular#122]
```
//post component
import { Component, OnInit } from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';

@Component({
  selector: 'app-post-editor',
  templateUrl: './post-editor.component.html',
  styleUrls: ['./post-editor.component.css']
})
export class PostEditorComponent implements OnInit {
public Editor = ClassicEditor;
  constructor() { }

  ngOnInit() {
  }

}
```
[https://stackblitz.com/edit/ng-webstore?file=src%2Fapp%2Fpost-editor%2Fpost-editor.component.ts](stackblits)

created this project  in stackbiltz and it is available in above url
![error-ckeditor](https://user-images.githubusercontent.com/4453931/60324321-20780900-99a2-11e9-8e99-cc0fa087ca66.png)

**Comment by ma2ciek** [comment]
Hi @rajrs.

As I see the StackBlitz has configured the `tsconfig.json` differently.

You need to make a default import instead of the namespace import:

```ts
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
```

And for the missing declaration warning it's enough to create a `typings.d.ts` file and fill it with:

```ts
declare module '@ckeditor/ckeditor5-build-classic' {}
```

**Comment by rajrs** [comment]
![image](https://user-images.githubusercontent.com/4453931/60717831-a0711680-9f40-11e9-9ad8-fcd2206c99bb.png)
its working, Thank u @ma2ciek

**Comment by vaibhaw1234** [comment]
yes

**Comment by Siddharth77** [comment]
@rajrs Could you please help what exactly have you done over here.

1. I have created a tsconfig.d.ts file as suggested by @Mgsy 
2. Able to get away with the problem which you're facing in red underline
3. I'm facing problem with named Import under ClassicEditor now and not able to get through it.

I still feel it needs more attention and proper resolution.

**Comment by Siddharth77** [comment]
Well ! I have resolved after following the steps by @ma2ciek, on 22 July 2019 comment.

- https://github.com/ckeditor/ckeditor5-angular/issues/70

**Comment by yasminkasem66** [comment]
I ran into the same problem and the solution was to create file typings.d.ts file in my project root 
and adding the following code into the typing file

declare module '@ckeditor/ckeditor5-build-classic' {
    const ClassicEditorBuild: any;
    export = ClassicEditorBuild;
}


![1](https://user-images.githubusercontent.com/40964618/168056938-bd752208-0981-47c9-9253-cce12cc0e12d.png)
![2](https://user-images.githubusercontent.com/40964618/168056942-1dc129d9-c27a-479a-9336-f7f08df878cf.png)
