### ISSUE TITLE
How to set external links open in new tab.

### ISSUE THREAD

**Issue by penaczko** [ckeditor/ckeditor5-angular#124]
Hi,

I've installed CKEditor 5 for Angular with ClassicEditor, and I cannot set external links to open in new tab automatically. 

I was trying to set it in my component by: 

`
public config = {
   link: {
      addTargetToExternalLinks: true
   }
};
`
`
public Editor = ClassicEditor;
`

and add it to the template like this: `<ckeditor [config] = "config"  [editor] = "Editor"></ckeditor>`, but all the links that I have, are opening in the same tab.

Can I ask you to explain me what am I doing wrong?

**Comment by Mgsy** [comment]
Hello, I've checked your case and I was able to successfully set this configuration option in CKEditor 5 with Angular. Please be sure that you pass the config to the editor properly.

**Comment by penaczko** [comment]
I've checked it twice. I was following the instruction under the: [Rich text editor component for Angular](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html). I also chose CKEditor 5 Classic Build. Everything has been done like in the instruction, and in my component I am adding these two fields:
`public config = { link: { addTargetToExternalLinks: true } };`
`public Editor = ClassicEditor;`,
then in the template:
`<ckeditor [config] = "config" [editor] = "Editor"></ckeditor>`.
And after compilation, all the links that I have inserted into the Editor are opening in the same tab. 

I can change e.g: toolbar in this way (`[config]="{ toolbar: [ 'heading', '|', 'bold', 'italic' ] }"`), but when I try to change the language it also doesn't work, same as the links.

**Comment by Mgsy** [comment]
@ma2ciek, can you take a look at this one?

**Comment by ma2ciek** [comment]
Hi!

It's natural that changing the language doesn't work, because we don't ship the language in the builds (it would increase the bundle size pretty much). If you want to change the language, please, add the language file too to the build. See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#localization (note that you use the custom build, so you need to import the language from the custom build too).

I'll investigate the link problem.

**Comment by penaczko** [comment]
Ok, so I am waiting for the information :) 
Thanks guys :)

**Comment by ma2ciek** [comment]
Everything works perfectly. Do you use [the latest available package](https://www.npmjs.com/package/@ckeditor/ckeditor5-build-classic)?
<img width="819" alt="Screen Shot 2019-07-22 at 16 38 20" src="https://user-images.githubusercontent.com/2768047/61641300-2ca06f00-ac9f-11e9-8d5c-2821fcad397f.png">

**Comment by penaczko** [comment]
Ok, but does it also work for you when you have created some content and want to display it in the other component template? 

Because when I create something and store it in the DB, and when I want to display the created content in the other component ( e.g: on the 'Home section'), all the links that I have attached to my created text are opening in the current tab.

When I add a decorator (e.g: `config = { link: { decorators: { isDownloadable: { mode: 'manual', label: 'Downloadable', attributes: { download: 'file.png' } } } } }`) to the config, it is also not working.

**Comment by ma2ciek** [comment]
No problem. Closing this issue, since it's invalid.
