### ISSUE TITLE
Cannot read property 'data-ck-expando' of undefined

### ISSUE THREAD

**Issue by emrade** [ckeditor/ckeditor5-angular#125]
I followed the angular integration as stated on the website and after i was done i got the warning below.
`Could not find a declaration file for module '@ckeditor/ckeditor5-build-classic'. 'path_to_dir/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js' implicitly has an 'any' type.
  Try `npm install @types/ckeditor__ckeditor5-build-classic` if it exists or add a new declaration (.d.ts) file containing declare module '@ckeditor/ckeditor5-build-classic';`

Then i followed the instructions on this link [https://github.com/ckeditor/ckeditor5-angular/issues/122](https://github.com/ckeditor/ckeditor5-angular/issues/122) to solve the issue. 

After, i noticed that when i navigate from the page i used the ckeditor to another page i get errors on my console.
`ERROR Error: "Uncaught (in promise): TypeError: t is undefined
ur@http://localhost:4200/vendor.js:93111:179895....`
The error doesn't say anything specific. Please do you know how i can solve the issue?
Let me know if you need any more info from me.

**ng version**
Angular CLI: 8.0.6
Node: 12.4.0
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

**Comment by Mgsy** [comment]
Hi, can you share your integration code? It will be easier for us to find a source of the problem.

**Comment by emrade** [comment]
Added `import { CKEditorModule } from '@ckeditor/ckeditor5-angular';` to the module imports

`// file.ts`
`import ClassicEditor from '@ckeditor/ckeditor5-build-classic';`
`public Editor = ClassicEditor;
  config = { 
    toolbar: [ 
      'heading', '|', 
      'bold', 'italic', 'link', 'bulletedList', 'numberedList', 
      'blockQuote', 'insertTable', 'mediaEmbed',
      'undo', 'redo' 
    ], 
    placeholder: 'Type a description...'
  };`

`// file.html`
`<ckeditor [editor]="Editor" [config]="config"></ckeditor>`

`// typings.d.ts`
`declare module '@ckeditor/ckeditor5-build-classic';`

That is basically all the code

**Comment by emrade** [comment]
Hello, i used chrome to run the project and this time the error was clearer. 
`Uncaught (in promise): TypeError: Cannot read property 'data-ck-expando' of undefined`

**Comment by emrade** [comment]
After finding out what the real issue was. I checked out the current issues and found that someone else already experienced it.

I read through and found a solution [https://github.com/ckeditor/ckeditor5-angular/issues/109#issuecomment-511030224](https://github.com/ckeditor/ckeditor5-angular/issues/109#issuecomment-511030224) which was to update the project to angular 8.1. That worked for me.

Thank you. The ckeditor is really great. Keep up the good work.

**Comment by Mgsy** [comment]
Great to hear that you managed to solve your problem 🎉

**Comment by gvreddy04** [comment]
This worked for me. [https://github.com/ckeditor/ckeditor5-angular/issues/109#issuecomment-547745762](url)
