### ISSUE TITLE
angular chunkOptimization + sourceMap runtime crash

### ISSUE THREAD

**Issue by MrRicherd** [ckeditor/ckeditor5-angular#127]
have base angular cli project.
diffirents config
angular.json: `"sourceMap": true,`
packaje.json: `"build": "ng build --prod",`
terminal:
1) npm install @ckeditor/ckeditor5-editor-inline --save
2) npm install @ckeditor/ckeditor5-highlight --save
3) npm install @ckeditor/ckeditor5-angular --save
app.component.html:
```
<div style="text-align:center">
  <h1>
    App is work
  </h1>
</div>
<form [formGroup]="form">
  <ckeditor [editor]="editor" [formControlName] [config]="config"></ckeditor>
</form>
```
app.component.html:
```
import { Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

import * as InlineEditor from '@ckeditor/ckeditor5-build-inline';
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent {
  editor = InlineEditor;
  config = {
    extraPlugins: [ Highlight],
  };

  form = new FormGroup({test: new FormControl('')});
}
```
app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';
import { ReactiveFormsModule } from '@angular/forms';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CKEditorModule,
    ReactiveFormsModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
npm run buld. copy on webserver.
result:
```
highlightcommand.js.pre-build-optimizer.js:24 Uncaught ReferenceError: Command is not defined
    at Module.zUnb (highlightcommand.js.pre-build-optimizer.js:24)
    at f (bootstrap:78)
    at Object.0 (switchbutton.css:1)
    at f (bootstrap:78)
    at t (bootstrap:45)
    at Array.r [as push] (bootstrap:32)
    at main.07e0cd282412c2a34be9.js:1
```
![image](https://user-images.githubusercontent.com/53515572/62706490-532d0c80-b9f8-11e9-859c-1fe184e1d550.png)

**Comment by ma2ciek** [comment]
Hi @MrRicherd!

You shouldn't use source together with the built editor, you should [create a custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) instead and then import it from the Angular component.

See this section: https://github.com/ckeditor/ckeditor5/blob/9401c6f6a9f1ee49e729b5da4ff39639c19ab4fa/docs/builds/guides/frameworks/angular.md#using-custom-ckeditor-5-builds. It will be merged soon to the master.

**Comment by MrRicherd** [comment]
gen new error:
```
ckeditor-ckeditor5-angular.js.pre-build-optimizer.js:326 TypeError: Cannot read property 'length' of undefined
    at Object.get [as anchor] (ckeditor.js.pre-build-optimizer.js:5585)
    at e.get [as anchor] (ckeditor.js.pre-build-optimizer.js:6114)
    at t.get [as anchor] (ckeditor.js.pre-build-optimizer.js:5979)
    at ckeditor.js.pre-build-optimizer.js:11183
    at e.refresh (ckeditor.js.pre-build-optimizer.js:11182)
    at t.<anonymous> (ckeditor.js.pre-build-optimizer.js:11110)
    at t.fire (ckeditor.js.pre-build-optimizer.js:579)
    at t._handleChangeBlock (ckeditor.js.pre-build-optimizer.js:9587)
    at t._runPendingChanges (ckeditor.js.pre-build-optimizer.js:10114)
    at t.enqueueChange (ckeditor.js.pre-build-optimizer.js:10026)
```
![image](https://user-images.githubusercontent.com/53515572/62781230-30662b00-bac0-11e9-98ba-dcfde4638d12.png)

**Comment by ma2ciek** [comment]
Could you check whether the alone editor works as expected? It's the first time I see this error.

**Comment by MrRicherd** [comment]
if include with tag script, it's fine.
if use "require" then  crash with error

**Comment by ma2ciek** [comment]
So I guess, that the problem exists in the transpilation to ES5, as the editor without the transpilation works as expected.

**Comment by MrRicherd** [comment]
Can you say what could be the problem?

**Comment by ma2ciek** [comment]
The incorrect Babel / UglifyJs / TypeScript transpilation.

Could you check whether targeting ES6 fixes this issue?
