### ISSUE TITLE
Add coveralls reporter

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#13]
It's incompatible with the default angular's coverage reporter (`karma-coverage-istanbul-reporter`). See https://github.com/ckeditor/ckeditor5-angular/pull/10#issuecomment-407758960 for more info.

Adding coveralls reporter results in:
```
10% building modules 1/1 modules 0 active25 07 2018 12:12:56.326:ERROR [reporter]: Can not load "coveralls"!
 Error: coverage reporter should precede coveralls
    at CoverallsReporter (/home/travis/build/ckeditor/ckeditor5-angular/node_modules/karma-coveralls/lib/index.js:14:11)
```

while running coveralls on the generated `lcov.info` throws an error too.

**Comment by ma2ciek** [comment]
A related problem to the CC: https://github.com/ckeditor/ckeditor5-angular/pull/24. We could drop this reporter completely if we somehow manage to work with coveralls.

**Comment by Reinmar** [comment]
Raising the priority because of https://github.com/ckeditor/ckeditor5-angular/issues/46.
