### ISSUE TITLE
[Angular 8] instanciated objects with ngModel and CKeditor

### ISSUE THREAD

**Issue by sohaieb** [ckeditor/ckeditor5-angular#130]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

**@ckeditor/ckeditor5-angular: 1.1.0
@ckeditor/ckeditor5-build-decoupled-document: 12.3.1**

## 📋 Steps to reproduce

1. Click on "modify" button on a page row of the ngx-datatable wich contains a list of html pages.
2. Bootstrap Modal displays with the selected row informations (specially the htmlContent to CKEditor with different langages, its title and its link).
3. On change the langage's drop box , CKEditor Content changes by the langage key of the selected one (exp: if FR: then to frensh lang, if EN then to English lang etc.).

## ✅ Expected result
CKEditor ngModel binding works fine (means to keep the html content for both different langages FR and En correctly).

## ❎ Actual result
when selecting a row, the html content linked to CKEditor is updating only with one content value for both langages (expl: if the htmlContent of the FR lang is "<p>salut!</p>" the En lang has the same value "salut!" and not "hello") and this is not what I expected as a result.

## 📃 Other details that might be useful

I did a test by making a component model object of the "Page" Class to test if CKEditor and its NgModel directive is working correctly with properties and values, but I still having the same issue,
you can check the results and code:

**this is called when I click on any row (just to test fr & en values with CKeditor ngModel):**
```
updatePage() {
        this.model = {
            id: -1,
            actif: 0,
            link: 'sohaieb',
            htmlContent: {
                fr: 'Salut tout le monde', **<=== Wanted Value**
                en: 'hello welcome'
            },
            title: {
                fr: 'title1',
                en: 'title2'
            }
        };
console.log(model.htmlContent);
        this.showAddModal();
        //  update request
    }
```
**this is the code of the html view of the Ckeditors availables in the view:**
```
<ckeditor name="content" 
[editor]="editor1" data=" " (ready)="onReady($event)"
[config]="editorConfig"
[(ngModel)]="model.htmlContent[langs.fr]"
></ckeditor>
<ckeditor name="content" 
    [editor]="editor1" 
    data=" " 
    (ready)="onReady($event)" 
    [config]="editorConfig" 
    [(ngModel)]="model.htmlContent[langs.en]">
    </ckeditor>
```
**and finally the result is :**
```
model: {
actif: 0
htmlContent:
    en: "<p>hello welcome</p>"
    fr: "<p>hello welcome</p>"  **<=== My Issue**
id: -1
link: "sohaieb"
title:
   en: "title2"
   fr: "title1"
}
```
explanation: as you can see in the code the **FR model html content is :** "fr: 'Salut tout le monde'," , but in the result it still **"hello world"**
![capt](https://user-images.githubusercontent.com/32372764/63186589-bf40ed80-c054-11e9-8d4c-34211620bad3.JPG)

**Comment by ma2ciek** [comment]
Hi @sohaieb!

I've transferred this issue to the `ckeidtor5-angular` repository.
I'll check if the issue occurs because AFAIK the `<ckeditor>` elements don't share anything and they should work in such scenario.

**Comment by sohaieb** [comment]
> Hi @sohaieb!
> 
> I've transferred this issue to the `ckeidtor5-angular` repository.
> I'll check if the issue occurs because AFAIK the `<ckeditor>` elements don't share anything and they should work in such scenario.

Hi @ma2ciek 
Thank you a lot :)

**Comment by ma2ciek** [comment]
Hi again.

I've tried to reproduce it locally but everything's been working well. Check it [here](https://github.com/ma2ciek/ckeditor5-angular-test/tree/t/130).

**Comment by ma2ciek** [comment]
And here's the demo with a button toggling editors: https://github.com/ma2ciek/ckeditor5-angular-test/tree/t/130-b

**Comment by sohaieb** [comment]
Hello again ! 
thank you a lot for your answer, 
To be honest, I tried your two projects, it worked for me too .. 
but when I try the same codes logic in my project, this still the same issue .. 
In this case, I will try to debug my project line by line and I will tell you if there is something making conflicts .
thank you a lot by the way :)

**Comment by sohaieb** [comment]
Hello again,
I can confirm that it was not a bug now .. 
this is really terrible, I did change nothing in my code and i found it working really good now .. 
I think maybe it was a caches problem but to be honest i cleared all my caches (browser and angular caches) . 

By the way, thank you a lot for your help Sir :)
