### ISSUE TITLE
Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by Biplab-1991** [ckeditor/ckeditor5-angular#133]
whenever iam using plugins inside create function ClassicEditor iam getting this error

**Comment by Mgsy** [comment]
Hi, did you follow our [Angular integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html)? Also your config code will be appreciated.

**Comment by Biplab-1991** [comment]
yes i have followed in same way

this is my ts:-

import { Component } from "@angular/core";
//import Plugin from "@ckeditor/ckeditor5-core/src/plugin";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import PasteFromOffice from "@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice";
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
ClassicEditor.create(document.querySelector("#editor"), {
  plugins: [PasteFromOffice,Bold],
  toolbar: ["bold"]
})
  .then(res => {
    console.log("initialized----", res);
  })
  .catch(err => {
    console.log("err---", err);
  });
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "ckeditor";

  public Editor = ClassicEditor;

 
}


and this html:-

<ckeditor style="width:50%;height:50%;" [editor]="Editor"></ckeditor>

<router-outlet></router-outlet>

but geeting this error:-

err--- CKEditorError: plugincollection-plugin-not-loaded: The requested plugin is not loaded. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-plugin-not-loaded
 {"plugin":"Clipboard"}
    at Ta.get (http://localhost:4200/vendor.js:72955:256728)
    at PasteFromOffice.init (http://localhost:4200/vendor.js:81240:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:2753:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:4200/polyfills.js:2512:43)
    at http://localhost:4200/polyfills.js:3251:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:2785:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.js:2557:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:2963:35)


my requirement is whatever there in excel like and font size,whatever i copy exact thing should be pasted in ckeditor

**Comment by ma2ciek** [comment]
Hi, the problem is that you can't build the source code in the Angular application yet (#26) and that you can't add plugins to the build this way.

Please, follow the steps described in [this guide](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build).
