### ISSUE TITLE
Can we Integrate MathType (@wiris/mathtype-ckeditor5) package?

### ISSUE THREAD

**Issue by Asifislam110** [ckeditor/ckeditor5-angular#134]

**Comment by ma2ciek** [comment]
Hi,

The `<ckeditor>` components accept any CKEditor 5 editor build.

All you need is to create a CKEditor 5 build including the MathType plugin - you can follow the [custom builds guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and then import the build from the editor and pass it to the [`editor` property](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#editor-required).

**Comment by phpdev1995** [comment]
@ma2ciek Hi can you please tell me how can i render mathtype MathML on target div using CKEditor5

**Comment by ma2ciek** [comment]
Hi @phpdev1995, have you created a custom build including the MathType plugin already? You can e.g. use the https://ckeditor.com/ckeditor-5/online-builder/ to achieve it quicker.

**Comment by phpdev1995** [comment]
@ma2ciek thanks for reply 

Yes I created custom build math type working in ckeditor but im unable to get mathtype output to target div when displaying on details web page.

**Comment by ma2ciek** [comment]
If you want to have the editor output then go with `editor.getData()`

IDK if there's a dedicated option in the MathType plugin, it's out of scope of the `ckeditor5-angular` repository.
