### ISSUE TITLE
Usage of angular components within html's ckeditor

### ISSUE THREAD

**Issue by snakone** [ckeditor/ckeditor5-angular#138]
is there any way to include angular components inside the html cdkeditor?

using `<app-component></app-component>` on the html converts to `&lt;app-component&gt;`

**Comment by ma2ciek** [comment]
The CKEditor 5 is mainly a content editor, it wasn't designed to be a suite builder.

Every element that should be parsed from data in CKEditor 5 must be provided with the schema and the conversion part - take a look e.g. at the https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-a-block-widget.html. The `<ckeditor5-angular>` is only an angular wrapper that fits the Angular API and allow easier integration, it doesn't allow to read any kind of registered Angular components, etc.

Sadly, this will probably never be available.
