### ISSUE TITLE
After build issue

### ISSUE THREAD

**Issue by holmes1491** [ckeditor/ckeditor5-angular#144]
ReferenceError: Cannot access 't' before initialization issue 

the issue shows in one of the bundle js

`
createEditor() {
                const t = document.createElement(this.tagName);
                return this.elementRef.nativeElement.appendChild(t),
                this.editor.create(t, this.config).then(t=>{
                    this.editorInstance = t,
                    t.setData(this.data),
                    this.initialIsDisabled && (t.isReadOnly = this.initialIsDisabled),
                    this.ngZone.run(()=>{
                        this.ready.emit(t)
                    }
                    ),
                    this.setUpEditorEvents(t)
                }
                ).catch(t=>{
                    console.error(t.stack)
                }
                )
            }
`

**Comment by ma2ciek** [comment]
Hi @holmes1491,

Thanks for reporting the issue.

Could you provide more information? Specifically:
- the full stack trace
- your project's TypeScript configuration
- steps to reproduce the above error

**Comment by ma2ciek** [comment]
I'm closing due to the lack of activity.
