### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by csimpi** [ckeditor/ckeditor5-angular#145]
Dear Authors,
thank you for making this angular component for CKEditor 5!

I don't really understand how should I enable the `ImageResize` plugin.

I import the classic build:
`import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';`

When I try to add the `ImageResize ` plugin I'm getting `ckeditor-duplicated-modules` error so it seems it has been added to the build. 
```
{
    extraPlugins: [ ImageResize ],
    image: {
      toolbar: [ 'imageTextAlternative', '|', 'imageStyle:full', 'imageStyle:side' ]
    },
   
  };
```

If I remove the `extraPlugins` section from the config, the resized doesn't work/doesn't appear at all.

`editor.plugins.has( 'ImageResize' )` returns `false`

So I'm not really sure what should I do now.

**Comment by ma2ciek** [comment]
Hi @csimpi!

Unfortunately, it's forbidden to use builds with source code (and in the angular integration there's also a problem with importing CKEditor 5 source code as there's a conflict with webpack loaders). The easiest solution here is to [create a custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build) of `ckeditor5-build-classic` with the `ImageResize` plugin added to the list of plugins. Sorry for the inconvenience.

**Comment by drilon-hametaj** [comment]
Hi, i have same problem, how can i create a custom build? In the guide it is not clear how to do in Angular

**Comment by csimpi** [comment]
@drilon-hametaj If you're following every step of the documentation very carefully, also you've read every single word, checked every link you'll be able to do it. After a couple of hours of struggling I could create my own package.

**Comment by ma2ciek** [comment]
You can also create a custom build using the \[online builder\](https://ckeditor.com/ckeditor-5/online-builder/) if you struggle with these steps.

**Comment by farrvince** [comment]
> online builder

Hello
I made a custom build with this online builder, I added ImageResize and Underline, but still doesn't work. 

https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable - {name: "underline"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
– {name: "imageResize"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
– {name: "imageResize:50"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
– {name: "imageResize:75"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
– {name: "imageResize:original"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
– {name: "linkImage"}

[Warning] widget-toolbar-no-items: Trying to register a toolbar without items. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items (ckeditor.js, line 5)
– {toolbarId: "mediaEmbed"}

[Warning] toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable (ckeditor.js, line 5)
– {name: "AutoLink"}

Here is my config:

<script>
      ClassicEditor
          .create( document.querySelector( '#mytextarea' ), {
              toolbar: {
                  items: [
                      'heading',
                      '|',
                      'bold',
                      'italic',
                      'link',
                      'AutoLink',
                      'alignment',
                      'bulletedList',
                      'numberedList',
                      'fontBackgroundColor',
                      'fontColor',
                      '|',
                      'indent',
                      'outdent',
                      '|',
                      'CKFinder',
                      'mediaEmbed',
                      'imageUpload',
                      'ImageToolbar',
                      'blockQuote',
                      'insertTable',
                      'undo',
                      'redo',
                      'Code',
                      'CodeBlock',
                      'underline'
                  ]
              },
              link: {
                  // Automatically add target="_blank" and rel="noopener noreferrer" to all external links.
                  addTargetToExternalLinks: true,

                  // Let the users control the "download" attribute of each link.
                  decorators: [
                      {
                          mode: 'manual',
                          label: 'Downloadable',
                          attributes: {
                              download: 'download'
                          }
                      }
                  ],

                  openInNewTab: {
                      mode: 'manual',
                      label: 'Open in a new tab',
                      defaultValue: true,			// This option will be selected by default.
                      attributes: {
                          target: '_blank',
                          rel: 'noopener noreferrer'
                      }
                  }
              },
              ckfinder: {
                  // Upload the images to the server using the CKFinder QuickUpload command.
                  uploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
              },
              language: 'hu',
              image: {
                  // Configure the available styles.
                  styles: [
                      'alignLeft', 'alignCenter', 'alignRight',
                      'full',
                      'side'
                  ],

                  // Configure the available image resize options.
                  resizeOptions: [
                      {
                          name: 'imageResize:original',
                          value: null,
                          icon: 'original'
                      },
                      {
                          name: 'imageResize:50',
                          value: '50',
                          icon: 'medium'
                      },
                      {
                          name: 'imageResize:75',
                          value: '75',
                          icon: 'large'
                      }
                  ],
                  // You need to configure the image toolbar, too, so it shows the new style
                  // buttons as well as the resize buttons.
                  toolbar: [

                      'imageResize',
                      'imageResize:50',
                      'imageResize:75',
                      'imageResize:original',
                      'linkImage'
                  ]
              },
              table: {
                  contentToolbar: [
                      'tableColumn',
                      'tableRow',
                      'mergeTableCells'
                  ]
              },
              licenseKey: ''
          } )
          .then( editor => {
              window.editor = editor;
          } )

          .catch( error => {
              console.error( 'Oops, something went wrong!' );
              console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
              console.warn( 'Build id: 5qhks2ekajeb-qmoluj4vpora' );
              console.error( error );
          } );
  </script>

**Comment by Saad674** [comment]
kdjkjifjdkjg

-

**Comment by zos224** [comment]
@ma2ciek I have built my custom plugin, but when I import it by:
import Editor from 'ckeditor5-custom-build/build/ckeditor';
I received this error like: Uncaught SyntaxError: The requested module '/ckeditor5/build/ckeditor.js?t=1669313604796' does not provide an export named 'default' 
How can I fix this?
