### ISSUE TITLE
Update compatibility info on npm page

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor5-angular#152]
On [npm integration page](https://www.npmjs.com/package/@ckeditor/ckeditor5-angular) there's info that it works with Angular 2+. According to [GitHub Readme](https://github.com/ckeditor/ckeditor5-angular/blob/master/README.md#supported-angular-versions) it should be probably updated to 5+ (same issue as with CKE4).

**Comment by ma2ciek** [comment]
This was fixed on the master already (so after the release the NPM page will be fine as well).

**Comment by ma2ciek** [comment]
It's live on NPM - https://www.npmjs.com/package/@ckeditor/ckeditor5-angular
