### ISSUE TITLE
Editor is not showing and giving an error in production(Angular8).

### ISSUE THREAD

**Issue by muhazzib** [ckeditor/ckeditor5-angular#157]
Ckeditor5 is working fine in development mode but giving an error in production.
**Production Mode Error**
![Screenshot_33](https://user-images.githubusercontent.com/25737000/66900976-36740d00-f017-11e9-84c0-d1daefeb4499.png)
![Screenshot_34](https://user-images.githubusercontent.com/25737000/66901058-67ecd880-f017-11e9-8a79-70f8bc1aa766.png)
**Code**
**TypeScript File**
```
import { Component, OnInit, DoCheck } from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import { ConfigService } from '../../services/config.service';
import { ChallengesService } from '../services/challenges.service';
import { Challenge } from '../interfaces/challenge';
import { Condition } from '../interfaces/condition';
import { Router, ActivatedRoute } from '@angular/router';
@Component({
  selector: 'app-create-challenge',
  templateUrl: './create-challenge.component.html',
  styleUrls: ['./create-challenge.component.scss']
})
export class CreateChallengeComponent implements OnInit, DoCheck {
  public Editor = ClassicEditor;
  showEditor = false;
  editorConfig = {
    placeholder: 'Type the content here!',
    toolbar: ['bold', 'italic']
  }
}
```
**HTML**
```
<ckeditor
   class="editor"
   [config]="editorConfig" [editor]="Editor"
   name="description"
   [(ngModel)]="translation.description"></ckeditor>
```
**Configuration**
```
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';
@NgModule({
declarations: [...],
imports: [CKEditorModule],
 providers: [...]
})
```
Versions:
"@ckeditor/ckeditor5-angular": "^1.1.0"
"@ckeditor/ckeditor5-build-classic": "^12.4.0"

**Comment by paolomainardi** [comment]
It should be nice to understand which dependency needs to be updated here to fix this issue, we have the very same issue (#155) on Angular5.

**Comment by ma2ciek** [comment]
I'd bet the `terser-webpack-plugin` and the `terser` lib itself.

**Comment by paolomainardi** [comment]
@ma2ciek is there a polyfill loaded somewhere to make the placehoder works ?

**Comment by ma2ciek** [comment]
What do you mean by the `polyfill`? The issue happens because the code of the placeholder is incorrectly transpiled by the `terser` minifier. So there is no polyfill that could fix that as it happens deep in the Angular build system. The only way to fix it is to somehow upgrade the above deps, probably the best way is by upgrading the whole Angular ecosystem to the latest version.

 This issue is deeply described in the https://github.com/ckeditor/ckeditor5/issues/1758 already.

**Comment by ma2ciek** [comment]
Duplicate of  https://github.com/ckeditor/ckeditor5/issues/1758.

**Comment by paolomainardi** [comment]
@ma2ciek yes, the question about the polyfill is related to the fact that ES5 browsers do not have a native `placeholder` attribute, checking the linked issue.

**Comment by ma2ciek** [comment]
The issue isn't related to the native placeholder attribute, it's related only to the transpilation. 

Also, the CKEditor 5 editor currently doesn't work in IE11, so transpiling the code with the editor down to ES5 is pointless IMO as all current browsers support ES6.

**Comment by gvreddy04** [comment]
I have same issue, below changes worked for me:

in tsconfig.json:

from "target": "es2015" to "target": "es6"
removed placeholder.
Note: I'm using my own customized ckEditor build: https://www.npmjs.com/package/@gvreddy04/ckeditor5-build-classic-all-features
