### ISSUE TITLE
How to upload image? 

### ISSUE THREAD

**Issue by NavKumarV** [ckeditor/ckeditor5-angular#159]
I have installed below 2 packages: 
**npm i @ckeditor/ckeditor5-build-classic
npm i @ckeditor/ckeditor5-angular**

And the ckeditor works fine for making the text bold, Itallic and can add links, all works fine. 
But when i click on image uploading button, it opens the folder to select the image, but it wont display/upload the selected image.

Angular CLI: 8.0.6
Node: 10.16.0
OS: linux x64
Angular: 8.0.3

Thanks in advance

**Comment by Mgsy** [comment]
Hi, did you set up an upload adapter? Please, see our [image upload overview](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html) to learn more about uploading images in CKEditor 5.

**Comment by ma2ciek** [comment]
Please, take a look also on these issues - https://github.com/ckeditor/ckeditor5-angular/issues?utf8=%E2%9C%93&q=image+upload, it's a duplicate.

**Comment by ma2ciek** [comment]
Closing as duplicate.
