### ISSUE TITLE
Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by Roadirsh** [ckeditor/ckeditor5-angular#16]
Hello,

This package is not compatible with Safari < 10. 

The const keyword is not supported in strict mode for Safari 9.1 and I think it has to do with the compiler not working correctly, could you check please ? 

To be exact it seems to be linked to this: [Github](https://github.com/ckeditor/ckeditor5-utils/blob/25ebf078bab20ab0839a01ff6849cce5cd426919/src/ckeditorerror.js#L13)

Thank you

**Comment by jodator** [comment]
Hello @Roadirsh [CKEditor 5 support latest versions of major browsers](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/support/browser-compatibility.html#desktop-environment).

Also:
> Safari on iOS in version 10 had a critical bug in JS parser. They fixed it in iOS 11. If you want to have CKE5 working in iOS 10, then you need to transpile CKE5 to ES5 (at least the broken feature).

You can find more information in https://github.com/ckeditor/ckeditor5/issues/542

**Comment by Roadirsh** [comment]
I see, thank you for the quick answer, I've search to find a way to compile a node_modules folder to es5 from typescript, but I didn't find anything. 

Your documentation has a way to do with [Webpack and Babel](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target), but no exemple with Typescript and the Angular CLI.

And on [Stackoverflow](https://stackoverflow.com/a/51243504/2393203) a CKEditor team member, explain fully why it is not working and will never work.

I will have to keep CKEditor 4 for now.

**Comment by ma2ciek** [comment]
> I see, thank you for the quick answer, I've search to find a way to compile a node_modules folder to es5 from typescript, but I didn't find anything.

Compiling the editor to the ES5 is possible and it's described [here](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target).

In your case, if you copy the ES6 build from `@ckeditor/ckeditor5-build-classic/build/ckeditor.js` to the angular env, the webpack will handle it and compile accordingly to the `target` option in the `tsconfig.json`.
