### ISSUE TITLE
How to use WordCount with BalloonEditor?

### ISSUE THREAD

**Issue by dkruchok** [ckeditor/ckeditor5-angular#160]
How I can add word counter like in the [doc page](https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html#demo) but with angular? 
If I trying to add WordCount plugin to the configurations it throws the **_ckeditor-duplicated-modules_** error.
I see wordcount is in a [list of configurations](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-wordCount) 
Is it possible or I need to create a **custom build** for that?

```
// In component
import * as BalloonEditor from '@ckeditor/ckeditor5-build-balloon';
import * as WordCount from '@ckeditor/ckeditor5-word-count/src/wordcount';
.....
public Editor = BalloonEditor;
public config = {
    toolbar: ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote'],
    // plugins: [WordCount],
    wordCount: {
      displayWords: true,
      displayCharacters: true,
      onUpdate(stats) {
        console.log(stats);
      }
}
....
//template
<ckeditor
formControlName="content"
[editor]="Editor"
[config]="config"
(ready)="onReady($event)"
(change)="onChange($event)"
(focus)="onFocus($event)"
(blur)="onBlur($event)">
</ckeditor>
```

package.json
```
    "@ckeditor/ckeditor5-angular": "^1.1.2",
    "@ckeditor/ckeditor5-build-balloon": "^15.0.0",
    "@ckeditor/ckeditor5-word-count": "^15.0.0",
```

**Comment by Mgsy** [comment]
Hi, you have to create a custom build with WordCount plugin enabled, then integrate the build with Angular. Please, see our [Adding a plugin to a build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) guide.

**Comment by devmnnit** [comment]
I am facing the same issue with custom build also. It throws the ckeditor-duplicated-modules error.

**Comment by rikuwolf** [comment]
For me, the WordCount plugin works with my custom build (based on the Classic Editor template) in Angular, but I had a TypeScript problem with the Editor's config type definitions when adding the wordCount config. Changing the type from `EditorConfig` to `any` removed the TypeScript problem and feature started to work.
