### ISSUE TITLE
Highlight code blocks 

### ISSUE THREAD

**Issue by MrBandaruk** [ckeditor/ckeditor5-angular#161]
Hello. How can I use [ngx-highlightjs](https://github.com/murhafsousli/ngx-highlightjs) with code blocks?

**Comment by Mgsy** [comment]
Hi! Code blocks plugin allows integration with a third-party syntax highlight plugins. You should take care of using classes which are recognized by a highlighter. For more information, please see the [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#integration-with-code-highlighters).
