### ISSUE TITLE
In Angular component config enterMode and coreStyles_bold doesn't work

### ISSUE THREAD

**Issue by oneclickwebstudio** [ckeditor/ckeditor5-angular#164]
## Type of report
Trying to set
```
const config = {
  ckeditor: {
    enterMode: 2,
    coreStyles_bold : { element: 'b', overrides: 'strong' },
    toolbar: {
      items: ['undo', 'redo', '|', 'bold', 'italic', 'underline', 'strikethrough', 'code', 'link']
    }
  }
};
```
to
`<ckeditor [editor]="Editor" [config]="config" formControlName="about"></ckeditor>
`

### Expected result

While pressing ENTER should create `<br/>` instead new paragraph
the same with coreStyles_bold

### Actual result

pasting paragraph and strong tag instead of `<b>`

**Comment by ma2ciek** [comment]
Hi @oneclickwebstudio,

The `enterMode ` and `coreStyles_bold` are CKEditor 4 configurations and they aren't implemented in CKEditor 5.

See https://github.com/ckeditor/ckeditor5/issues/1141 for the reasoning why the enter feature behavior isn't configurable.

Also, here's the comparison between CKEditor 4 and CKEditor 5 - https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html.
