### ISSUE TITLE
Module parse failed: Unterminated string constant

### ISSUE THREAD

**Issue by GencBlakqori** [ckeditor/ckeditor5-angular#17]
I'm trying to use this with angular-cli and I'm getting this error:
```
Module parse failed: Unterminated string constant (5:453480)
You may need an appropriate loader to handle this file type.
|  * For licensing, see LICENSE.md.
|  */
| | !function(t){t.en=Object.assign(t.en||{},{a:"Cannot upload file:",b:"Block quote",c:"Bold",d:"Choose heading",e:"Heading",f:"Italic",g:"image widget",h:"Enter image caption",i:"Full size image",j:"Side...
```
then the whole ckeditor.js file is being logged and at the end of the log I get this line: 
```
| //# sourceMappingURL=ckeditor.js.map
```

This happens to me also when I try to use ckeditor without the angular wrapper in my angular-cli application. 

Angular version: **6.0.7**

**Comment by pomek** [comment]
Did you follow the instruction – https://github.com/ckeditor/ckeditor5-angular#quick-start?

**Comment by pomek** [comment]
Could you provide steps required for reproducing the error?

**Comment by GencBlakqori** [comment]
Basically just followed all the steps in quick start:
1) installet ckeditor5-angular
2) installed the classic editor
3) added the allowJs attribute
4) imported the ckeditor5-angular module
5) used the editor in my component.

**Comment by pomek** [comment]
I will look on this today and let you know what I figured out.

**Comment by pomek** [comment]
Because I don't know Angular, I must follow [the official quick start guide](https://angular.io/guide/quickstart).. I'll describe everything what I've done and what I've achieved.

1. I created my first Angular app using the Angular quick start guide. It works.
2. I installed `ClassicEditor`: `npm install --save-dev @ckeditor/ckeditor5-build-classic`.
3. I installed the Angular component: `npm install --save-dev @ckeditor/ckeditor5-angular`.
4. In `tsconfig.json` I added: `allowJs: true` into `compilerOptions` object.
5. I modified the `App` component:

**src/app/app.module.ts**

```ts
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';

import {AppComponent} from './app.component';

// Import the component.
import {CKEditorModule} from '@ckeditor/ckeditor5-angular';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    // Attach the component into an application.
    CKEditorModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**src/app/app.component.ts**

```ts
import {Component} from '@angular/core';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  public Editor = ClassicEditor;

  title = 'My First Angular App!';
}
```

**src/app/app.component.html**

```html
<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">

  <ckeditor [editor]="Editor" data="<p>Hello world!</p>"></ckeditor>
</div>
```

6. `ng serve -o` seems to work.

![image](https://user-images.githubusercontent.com/2270764/43483566-51cbaff2-950c-11e8-9f54-c896b6a6fc7e.png)

---

Am I missing anything?

**Comment by pomek** [comment]
```bash
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.1
Node: 10.7.0
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cli                      6.1.1
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```

**Comment by ma2ciek** [comment]
> Module parse failed: Unterminated string constant (5:453480)
You may need an appropriate loader to handle this file type.

It means, that the problem is probably connected to the webpack loader you're using.
What version of Angular CLI do you use? Did you install something extra?

**Comment by ma2ciek** [comment]
I'm closing this issue because of the lack of activity. Please, reopen it if you still have some questions.
