### ISSUE TITLE
Readme lacks the build editor step

### ISSUE THREAD

**Issue by viktorvavilov** [ckeditor/ckeditor5-angular#171]
Repository is incomplete and has missed files.

ERROR in src/app/context-demo/context-demo.ts:3:27 - error TS2307: Cannot find module '../../../ckeditor/build/cksource'.

3 import * as CKSource from '../../../ckeditor/build/cksource';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/demo-form/demo-form.component.ts:8:27 - error TS2307: Cannot find module '../../../ckeditor/build/cksource'.

8 import * as CKSource from '../../../ckeditor/build/cksource';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/demo-reactive-form/demo-reactive-form.component.ts:7:27 - error TS2307: Cannot find module '../../../ckeditor/build/cksource'.

7 import * as CKSource from '../../../ckeditor/build/cksource';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/simple-usage/simple-usage.component.ts:2:27 - error TS2307: Cannot find module '../../../ckeditor/build/cksource'.

2 import * as CKSource from '../../../ckeditor/build/cksource';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/watchdog-demo/watchdog-demo.ts:3:27 - error TS2307: Cannot find module '../../../ckeditor/build/cksource'.

3 import * as CKSource from '../../../ckeditor/build/cksource';

**Comment by Mgsy** [comment]
Hi, thanks for the report. Actually, as I can see the project misses some key steps to follow in readme. We'll fix it.

So, please follow the below instructions:
1. In the main sample directory run `npm install`.
1. Go to CKEditor 5 directory and install dependencies - `cd vendor/ckeditor5 && npm install && cd ../..`
1. Build the app - `npm run build`.
1. Start the app - `npm run serve`.

Let me know if above helps.

**Comment by ma2ciek** [comment]
I'm sorry @viktorvavilov, I forgot to update the readme.
