### ISSUE TITLE
Doesn't work in MatFormField

### ISSUE THREAD

**Issue by mswilson4040** [ckeditor/ckeditor5-angular#175]
This module supports ReactiveForms but it doesn't work in a MatFormFieldControl:

> Error: mat-form-field must contain a MatFormFieldControl.

```
<mat-form-field>
    <ckeditor [editor]="descriptionEditor" [config]="editorConfig" formControlName="description"></ckeditor>
    <mat-hint>Some descrption text</mat-hint>
</mat-form-field>
```

**Comment by Mgsy** [comment]
cc @ma2ciek

**Comment by ma2ciek** [comment]
The `CKEditorComponent` doesn't implement the `MatFormFieldControl` interface. The `MatFormFieldControl`  is an angular-material thing, not a principle of `ReactiveForms`, and the integration with material design is an open issue - #21.
