### ISSUE TITLE
Using disabled property with context watchdog causes a crash

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-angular#177]
Watchdog crashes when ckeditor component is initialized with `disabled` property and `watchdog` property together.

Below code is fired when `disabled` property of the component is read:

```plaintext
public setDisabledState( isDisabled: boolean ): void {
	// If already initialized.
	if ( this.editorInstance ) {
		this.editorInstance.isReadOnly = isDisabled;
	}

	// Store the state anyway to use it once the editor is created.
	this.initialIsDisabled = isDisabled;
}
```

`this.editorInstance` is a getter:

```plaintext
public get editorInstance(): CKEditor5.Editor | null {
	if ( this.editorWatchdog ) {
		return this.editorWatchdog.editor;
	}

	if ( this.watchdog ) {
		return this.watchdog.getItem( this.id );
	}

	return null;
}
```

Unfortunately, at the time `setDisabledState` is called, the editor is not yet added to the watchdog, so `this.watchdog.getItem` throws an error.

**Comment by ma2ciek** [comment]
In the next iteration we should close the ckeditor/ckeditor5#6461 and use the new API.
