### ISSUE TITLE
Angular SSR issue

### ISSUE THREAD

**Issue by damiencal** [ckeditor/ckeditor5-angular#180]
Im able to build the app client side but not when building server side.

![DeepinScreenshot_select-area_20200320195119](https://user-images.githubusercontent.com/2505223/77196723-33101080-6ae4-11ea-80f7-2e8763abf024.png)

I followed the tutorial https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#quick-start

Im using:
    "@ckeditor/ckeditor5-angular": "1.2.2",
    "@ckeditor/ckeditor5-build-classic": "18.0.0",

NPM 12
Angular 8.2.14

**Comment by ma2ciek** [comment]
Hi @damiencal, that's not an issue with the `ckeditor5-angular` integration, currently the SSR doesn't work with CKEditror5 and there're some easy workarounds to import the editor only on the frontend.

Please, give a reaction or post your use case in ckeditor/ckeditor5#1511.
