### ISSUE TITLE
Update all internals and samples to Angular@10

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#182]
Possibly connected - #176.

**Comment by ma2ciek** [comment]
This task wasn't as simple as I thought as updating internal dependencies has an impact on the release process. In short: the `ng-builder` package that we use to create Angular-compatible NPM packages uses Angular's deps to create these NPM builds and we need to keep it at a low version to serve a package that is compatible with Angular5+ apps :sob: 

On the other hand, it makes the package look old and unmaintained on  https://www.npmjs.com/package/@ckeditor/ckeditor5-angular. IDK what we should do here to fix that situation. At some point, we should migrate our old custom library-creating tool to the official one - https://angular.io/guide/creating-libraries. The problem is that the official one will be working only for Angular 8+ or Angular 9+ apps. This could be done as a major release to not break backward compatibility, so we could still support the 1.x version and porting some important bug fixes there. Though, then we'd be in the trouble maintaining two versions of that lib. 

cc @wwalc @mlewand

**Comment by wwalc** [comment]
https://angular.io/guide/releases#support-policy-and-schedule

![](https://user-images.githubusercontent.com/545175/77754768-44997100-702c-11ea-8b7d-846930f232c0.png)

> This could be done as a major release to not break backward compatibility

  
I don't feel competent enough here to decide what direction to take, but I think I'd be okay with doing whatever is right to support just versions 8+ starting from April 18, 2020.   
  
If it turns out that there is a significant demand for supporting the latest CKE5 on older versions of Angular, then we always will have an option to have a new minor release for the 1.x product line.  
  
There would be of course some side effects, like having to keep the public documentation for both integrations for some time etc.

**Comment by ma2ciek** [comment]
Connected - #96.

**Comment by ma2ciek** [comment]
There's a high chance that the old Angular library compiler leads to:

*   #194 Watchdog isn't defined in the production build error
*   #181 Editor deep import warning

**Comment by ma2ciek** [comment]
As I see - https://github.com/nicky-lenaers/ngx-scroll-to#installation - it's normal to have a few branches and releases for various Angular versions, though it would be painful to maintain it :/

**Comment by wwalc** [comment]
> As I see - https://github.com/nicky-lenaers/ngx-scroll-to#installation - it's normal to have a few branches and releases for various Angular versions, though it would be painful to maintain it :/

Are you sure? Isn't that library just pointing to older versions of the library that have been released years ago?

**Comment by ma2ciek** [comment]
Hm, right, readme is pointing to older versions, though we could have a temp branch for old versions for hot fixes.

**Comment by shakoorattari** [comment]
Hi, Is it fixed?

**Comment by Pasqualle** [comment]
I do not see a reason why would a library author care about an unsupported Angular version. Angular apps should be always updated to the latest Angular version.
The library should be working with Angular 9+ (v8 will be unsupported after a month now).

My suggestion is to create a new major v2, and leave the v1 as is, but nobody will care about v1 support anyway.
You can also create v3 in case there would be some features which are compatible with Angular 10 only. You might "name" your versions v9 and v10, to be easily recognizable which Angular version is supported. This is a quite common practice with Angular libraries.
Development focus should be always on the latest version of the library.
