### ISSUE TITLE
Uncaught (in promise): CKEditorError: plugincollection-plugin-not-loaded: The requested plugin is not loaded. 

### ISSUE THREAD

**Issue by sem1colon** [ckeditor/ckeditor5-angular#184]
I'm trying out the track changes feature, I was getting the error. I have imported editor as 
`import * as ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic';
`

**Comment by ma2ciek** [comment]
Hi! You should create a custom build and use it. It's not added to the default set of any of our pre-defined builds.

You can add the track changes using e.g. the https://ckeditor.com/ckeditor-5/online-builder/ or manually by installing the plugin, adding icons to toolbar, etc. 

Then follow https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build.

**Comment by sem1colon** [comment]
Getting this error when I tried to import [custom editor.js](https://github.com/ckeditor/ckeditor5-collaboration-samples/blob/master/track-changes-for-angular/vendor/ckeditor5/src/classic-editor-with-track-changes.js).
CKEditorError: collection-get-invalid-arg: Index or id must be given.

**Comment by ma2ciek** [comment]
Have you tried to run the https://github.com/ckeditor/ckeditor5-collaboration-samples/blob/master/track-changes-for-angular alone? It uses the Angular as well so there should be no problem to run it. Since it's our commercial plugin you could contact us using the support channel.

**Comment by sem1colon** [comment]
Yes, I have tried that. It works.
But when I want try out dynamically through service, I was getting the error.
I already tried to reach out the support team, not responding properly to the point.
Can you just look into the project, let me know what went wrong? I was just trying the same example code through service.

**Comment by ma2ciek** [comment]
> // The ID of the current user.

> userId: this.authService.getCurrentUser(), \<-

You're welcome.

**Comment by ma2ciek** [comment]
The error message should be improved here by providing an additional type assertion. This will be done in the future.
