### ISSUE TITLE
File Upload with JWT (add custom header to upload request) 

### ISSUE THREAD

**Issue by Exlord** [ckeditor/ckeditor5-angular#186]
I found this for on older version, can this be converted to ck5+angular7

https://github.com/lemonde/angular-ckeditor/issues/76#issue-315442022

```
   CKEDITOR.on( 'instanceReady', function( evt ) {
     
        evt.editor.on( 'fileUploadRequest', function( evt ) {
            console.log('fileUploadRequest by CKEditor',this.file);

            var xhr = evt.data.fileLoader.xhr;
            xhr.setRequestHeader( 'Authorization', 'Bearer ' + $localStorage.token );

        } );
    } );
```

**Comment by ma2ciek** [comment]
It's possible, you need to create a custom build including simple upload adapter (e.g using an online builder) and then add the editor build to an Angular app and [\[configure the editor\]](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html) after you get the editor instance using the `(ready)="onReady($event)"`.

**Comment by Exlord** [comment]
> 
> 
> It's possible, you need to create a custom build including simple upload adapter (e.g using an online builder) and then add the editor build to an Angular app and [[configure the editor]](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html) after you get the editor instance using the `(ready)="onReady($event)"`.

Simple upload adaptor already has `headers` option, no need to use this code. I was hoping not to use custom build!!!

**Comment by ma2ciek** [comment]
You might be interested in [creating a custom upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html) on top of the https://github.com/ckeditor/ckeditor5-upload/blob/master/src/adapters/simpleuploadadapter.js. That won't require any rebuilding if you would create it without imports to CKEditor 5 source packages.
