### ISSUE TITLE
Error: Uncaught (in promise): CKEditorError: collection-get-invalid-arg: Index or id must be given.

### ISSUE THREAD

**Issue by sem1colon** [ckeditor/ckeditor5-angular#187]
I'm trying out the [track changes feature](https://github.com/ckeditor/ckeditor5-collaboration-samples/blob/master/track-changes-for-angular).
Can anyone have a look at this [project](https://github.com/sem1colon/CKEditor-track-changes-angular-demo)?

**Comment by Mgsy** [comment]
Hi! Track Changes is our commercial plugin and this repository is dedicated to an open-source part of the project. Please, contact us via the [support channel](https://ckeditor.com/contact/) and describe your issue precisely. Our support team will be happy to help you :)
