### ISSUE TITLE
Toolbar doesn't work for following configuration

### ISSUE THREAD

**Issue by shreejibawa** [ckeditor/ckeditor5-angular#193]
Following are the library versions

````
"@angular/core": "5.2.0",
"@ckeditor/ckeditor5-angular": "^1.2.3",
"@ckeditor/ckeditor5-build-classic": "^18.0.0",
````

I am using following configuration in component

````
editor_options = {
		toolbar: [
			['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '|', 'Undo', 'Redo'], 
			['Find', 'Replace', '|', 'SelectAll'],
			['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '|', 'CopyFormatting', 'RemoveFormat', 'NumberedList', 'BulletedList', '|', 'Outdent', 'Indent', '|'],
			['Blockquote', 'Link', 'Unlink', 'Anchor'], 
			['Image', 'Table', 'HorizontalRule',],
			['Smiley', 'Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor']
		]
	}
````

And in template

````
<ckeditor [config]="editor_options" [editor]="Editor" formControlName="recommended_action" [formControl]="valForm.controls['recommended_action']"></ckeditor>
````

Toolbar doesn't show up at all. No errors. What am I doing wrong?

**Comment by ma2ciek** [comment]
Hi @shreejibawa!

The CKEditor 5 editor's toolbar doesn't support array of arrays. You can specify toolbar icons by passing a single array with all toolbar icons added there.

**Comment by shreejibawa** [comment]
@ma2ciek I tried in single array as well..

````
toolbar: [
			'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '|', 'Undo', 'Redo',
			'Find', 'Replace', '|', 'SelectAll',
			'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '|', 'CopyFormatting', 'RemoveFormat', 'NumberedList','BulletedList', '|', 'Outdent', 'Indent', '|',
			'Blockquote', 'Link', 'Unlink', 'Anchor',
			'Image', 'Table', 'HorizontalRule',
			'Smiley', 'Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor'
		]
````

 Not all options are coming. Any idea why?

**Comment by ma2ciek** [comment]
I guess that you have copied these options from CKEditor 4 editor. CKEditor 5 was written from the scratch and its name is a little bit confusing as it's a very different editor in almost every aspect. See https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html and https://stackoverflow.com/questions/47390766/how-do-i-get-toolbar-available-items-in-ckeditor-5.

Also note, that these plugins aren't available by default in the editor classic build. Most of them should be included in the https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html but a few missing you have to add manually. You can also use the https://ckeditor.com/ckeditor-5/online-builder/ to generate the editor you want to have and then paste the generated file into the Angular app by following the documentation.

**Comment by ma2ciek** [comment]
To be precise - this is not an issue with the `ckeditor5-angular` integration. For more information ask on https://github.com/ckeditor/ckeditor5/issues.

**Comment by shreejibawa** [comment]
@ma2ciek thank you its clear now.
