### ISSUE TITLE
**For help！！！**

### ISSUE THREAD

**Issue by smallcoderofme** [ckeditor/ckeditor5-angular#195]
ng version 9.1.0,
**Error：**
src/app/authorize/authorize.create.post.component.html:3:19 - error NG8002: Can'
t bind to 'editor' since it isn't a known property of 'ckeditor'.
3         <ckeditor [editor]="Editor" data="<p>Hello, world!</p>"></ckeditor>
                    ~~~~~~~~~~~~~~~~~
  src/app/authorize/authorize.create.post.component.ts:6:18
    6     templateUrl: './authorize.create.post.component.html',
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AuthorizeCreatePostComponent.
**AuthorizeModule**
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthorizeRoutingModule } from './authorize.routing.module';
import { AuthorizeComponent } from './authorize.component';
import { AuthorizeLoginComponent } from './authorize.login.component';
import { FormsModule } from '@angular/forms';
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';
@NgModule({
  declarations: [ AuthorizeComponent, AuthorizeLoginComponent ],
  imports: [
    CommonModule, AuthorizeRoutingModule, FormsModule, CKEditorModule
  ]
})
export class AuthorizeModule { }
**AuthorizeCreatePostComponent  **
import { Component } from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';
@Component({
    selector: 'app-create',
    templateUrl: './authorize.create.post.component.html',
    styleUrls: []
})
export class AuthorizeCreatePostComponent {
    public Editor = ClassicEditor;
}
**authorize.create.post.component.html **
<div class="row">
    <div class="col-sm-8">
        <ckeditor [editor]="Editor" data="<p>Hello, world!</p>"></ckeditor>
    </div>
</div>

**Comment by smallcoderofme** [comment]
I have imported FormsModule, CKEditorModule in the module where AuthorizeCreatePostComponent is located. This AuthorizeModule is imported as lazyload.

**Comment by ma2ciek** [comment]
Hi!

Could you create a repository when I could reproduce the error? Right now I can't spot the error.

**Comment by smallcoderofme** [comment]
> Hi!
> 
> Could you create a repository when I could reproduce the error? Right now I can't spot the error.

Already solved.

**Comment by fabiancabau** [comment]
@smallcoderofme do you mind sharing the solution?

**Comment by luiza-avelino** [comment]
I was having the same problem and solved removing the CKEditorModule import from the app.module and instead imported on the component's module I was using. Eg. HomeComponentModule

**Comment by ingeJulianLasso** [comment]
@smallcoderofme do you mind sharing the solution? pls

**Comment by ingeJulianLasso** [comment]
In the end I was not able to detect why the ckeditor was failing so I switched to tinymce. Thank you very much to whoever can give me a light on the possible error.

**Comment by Ed-Games** [comment]
> I was having the same problem and solved removing the CKEditorModule import from the app.module and instead imported on the component's module I was using. Eg. HomeComponentModule

Thanks a lot. I spent a week trying to find this error and your solution worked for me.
