### ISSUE TITLE
'ckeditor' is not a known element when using a custom CKEditor 5 build

### ISSUE THREAD

**Issue by gcorsaro** [ckeditor/ckeditor5-angular#196]
Hello, I'm trying to integrate CKEditor to my angular app. Since I need to integrate some custom plugins, I followed the guide as described [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build).
The problem is that I have the following error: **'ckeditor' is not a known element** when I load the page because ckeditor is not recognized as component.
Here my component declaration

```
import {Component, forwardRef, Input, ViewChild, Renderer2, OnInit } from '@angular/core';
import {ControlValueAccessor, NG_VALUE_ACCESSOR} from '@angular/forms';
import * as Editor from './ckeditor/ckeditor.js';

export const CKEDITOR_TEXTAREA_VALUE_ACCESSOR : any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => CKEditorTextareaComponent),
  multi: true,
};

@Component({
	selector: 'ckeditor-textarea',
	providers: [CKEDITOR_TEXTAREA_VALUE_ACCESSOR],
	template: '<ckeditor [editor]="Editor"></ckeditor>',
	styles: [':host {display: contents}']
})
export class CKEditorTextareaComponent implements ControlValueAccessor, OnInit {
	public Editor = Editor;
}

```
what's wrong in my code?

**Comment by ma2ciek** [comment]
Hi!

Have you been followed the docs carefully? I guess that you missed the part with registering the CKEditorModule in the parent module of your component.

**Comment by gcorsaro** [comment]
Hello, many thanks for the feedback. As far as I've seen the module registration would be expected to be done if I used the npm installation. In my case I built on my own and copied the assembly in my src. Could you please tell me where is indicated such module registration in the user build paragraph?

**Comment by ma2ciek** [comment]
I meant adding the `CKEditorModule` to the parent module. Like it's done in the: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#quick-start. You can also browse this repository to see its sample application - https://github.com/ckeditor/ckeditor5-angular/blob/master/src/app/app.module.ts#L28.

**Comment by gcorsaro** [comment]
Maybe I got where is my mistake. I skipped the first step `npm install --save @ckeditor/ckeditor5-angular` because I thought it was related to the **official editor builds** part only. But reading more carefully probably must be done apart from which build I'll choose. Could you confirm?
However when I launch that command I have a stack size exceeded error and those modules aren't downloaded from npm. How do I fix it?
Many thanks for your support.

**Comment by gcorsaro** [comment]
I confirm that the problem was related to the missing `npm install --save @ckeditor/ckeditor5-angular` step. However by running that command I had a **stack size exceeded** error. I solved it by adding `@ckeditor/ckeditor5-angular` as dependency in my package json.
Now it's working and I can close the ticket.
Many thanks for the support

**Comment by ecolara3** [comment]
I assume people are still ending up here trying to figure out how to integrate this all into an Angular Application, specifically with the simpleFileUpload plugin. I made a sample repo of this being done using the custom build tool CKEditor offers and added the steps in the README, cheers!

[CKEditor5 with Angular and SimpleFileUploader Plugin](https://github.com/ecolara3/ckeditor)
