### ISSUE TITLE
Is it Possible to bind Docx file data content to CKEditor5 in Angular 8?

### ISSUE THREAD

**Issue by deva765** [ckeditor/ckeditor5-angular#198]
Hi im trying to read the docx file content using File Reader and bind it to the CKEditor, so the user can modify and should be able to export the CKEditor data to docx file.

Is this function already available?

And in ClassicEditor, can we add more tools which are available in CKEditor 4?

Any help/directions to achieve would be appreciated!

**Comment by ma2ciek** [comment]
Hi!

> Hi im trying to read the docx file content using File Reader and bind it to the CKEditor, so the user can modify and should be able to export the CKEditor data to docx file.

In the CKEditor 5 you can't currently make the output produce the `docx` format. Though, it can be implemented, you can also find if there's a JS library for HTML->docx conversion. The same with loading data.

> And in ClassicEditor, can we add more tools which are available in CKEditor 4?

Not from CKEditor 4 as this editor was written from scratch and is focused on writing and producing semantic output data. [But there're features in CKEditor 5](https://docs.ckeditor.com/ckeditor5/latest/features/) that can be added to the default set of ClassicEditor features.

All in all, this is not a topic for the ckeditor5-angular integration, it's rather a topic for https://github.com/ckeditor/ckeditor5. ckeditor5-angular is only an Angular wrapper for the former library.
