### ISSUE TITLE
Real-Time Collabration

### ISSUE THREAD

**Issue by parth-gr** [ckeditor/ckeditor5-angular#201]
How to check the application, if it is working properly in Real-Time Collaboration, Like the instance Watchdog is working fine in the localHost.

**Comment by ma2ciek** [comment]
Hi!

Could you elaborate more? I don't know what you meant exactly but perhaps it will fit more to https://github.com/ckeditor/ckeditor5/issues as the question is a little bit generic?

Or do you mean testing app restarting with Watchdog?

**Comment by parth-gr** [comment]
Hello sir, Thanks for the reply,
Yes, sir I mean Testing app restarting with Watchdog,
I listed the situation and I find i need a sperate server serving this Angular Editor and by this, we can do the dynamic changes of text by different machine on a single document, as done in google docs. 
Any other suggestions??

**Comment by ma2ciek** [comment]
You can force the restart by calling `watchdog._restart()` It will probably be a public `watchdog.restart()` method soon. You can get the editor watchdog by accessing it via `ckeditorComponent.editorWatchdog`.

**Comment by parth-gr** [comment]
Okay, sir in the route Integration with CKEditor Watchdog this method is not implemented?? 
 
I want this type of software for production.
https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/collaboration.html

**Comment by ma2ciek** [comment]
Closing due to an unclear description of the issue.
