### ISSUE TITLE
There is no option for toggle toolbar icons like 'Bold', 'Italic' etc

### ISSUE THREAD

**Issue by akhilcatone** [ckeditor/ckeditor5-angular#203]
There is no option for toggle toolbar icons (i.e. enable/disable toolbar item) like 'Bold', 'Italic' etc. Is it not available in angular. Also there is no option to refresh toolbar icons if one or more item added to toolbar. @ma2ciek

**Comment by Mgsy** [comment]
Hi! Could you please describe your use case more precisely? Basically, toolbar item's state is bound to a command's `isEnabled` property. It means that the item becomes disabled when the command is disabled. You can disable a command using [`Command#forceDisabled`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_command-Command.html#function-forceDisabled) method. See the example for a bold icon:

```javascript
const command = editor.commands.get( 'Bold' );
command.forceDisabled(); // After disabling the command, the icon becomes disabled
```

> Also there is no option to refresh toolbar icons if one or more item added to toolbar.

I'm not sure what do you mean by saying "refresh toolbar icons", however, if you'd like to add new toolbar items dynamically, please note that this is not supported.

**Comment by akhilcatone** [comment]
This is fine it works for my scenario
