### ISSUE TITLE
Warning: Entry point '@ckeditor/ckeditor5-angular' contains deep imports into xxx

### ISSUE THREAD

**Issue by achraflaakissi** [ckeditor/ckeditor5-angular#205]
I have upgraded to the latest stable version of angular 9.1.9 and i am updating all dependencies but i am still getting this warning message.
`Warning: Entry point '@ckeditor/ckeditor5-angular' contains deep imports into ......`

**Comment by achraflaakissi** [comment]
I just solved it by adding a ngcc.config.js file to ignore deep imports for @ckeditor/ckeditor5-angular.

_ngcc.config.js_
```
module.exports = {
  packages: {
    '@ckeditor/ckeditor5-angular': {
      ignorableDeepImportMatchers: [
        /@ckeditor\//
      ]
    },
  }
};
```
for more info[ look here.](https://github.com/angular/angular/pull/35683)

**Comment by alex-osman** [comment]
@achraflaakissi Where does this ngcc.config.js file go?  Is it in the same directory as angular.json or under the @ckeditor/ckeditor5-angular node_modules directory?

**Comment by Dzivo** [comment]
That is not solved it is ignored :)
