### ISSUE TITLE
Deep Imports Warning

### ISSUE THREAD

**Issue by mswilson4040** [ckeditor/ckeditor5-angular#206]
When building my angular project, I receive the below warning from the ckeditor-angular package:

> Warning: Entry point '@ckeditor/ckeditor5-angular' contains deep imports into '/myapp/node_modules/@ckeditor/ckeditor5-watchdog/src/editorwatchdog'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by ma2ciek** [comment]
Hi!

It's a duplicate of #181.
