### ISSUE TITLE
Ability to change a text once stored.

### ISSUE THREAD

**Issue by ghost** [ckeditor/ckeditor5-angular#208]
Hi Maciej, I have followed your ckeditor5 / angular article on github a lot, and I have had the opportunity to study it, but I have not found anything regarding the modification of a text in ckeditor5.
Let me explain: when I wrote the text, and I stored in MySQL database, when I recall it, I would give the user the possibility to change it, but I found nothing about it, could you help me figure out how.
Thanks

**Comment by Mgsy** [comment]
Hello, could you please explain your use case more precisely? Do you mean some content processing before loading it to the editor?

**Comment by typing-dev** [comment]
No, I want to understand when I recover the text from the database where it is stored, how do I view it and edit it.

**Comment by babbler-eu** [comment]
Maybe I have to explain myself better:
For my project I use ckeditor5.
After writing the post with the editor, this post is stored in a Mysql database.
I have to create the possibility to edit this post, so I call it from my mysql database, but then I don't know how to do it with ckeditor5 to edit the post in angular 9.x
Thanks for your help.

**Comment by Mgsy** [comment]
I'm sorry for the late reply. CKEditor 5 has [`initialData`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData) property which could be used for getting content which should be displayed on the editor initialization. You can simply make a request to your database, get the content and pass it to this property.
