### ISSUE TITLE
editor-watchdog warning

### ISSUE THREAD

**Issue by islamzeki** [ckeditor/ckeditor5-angular#209]
Entry point '@ckeditor/ckeditor5-angular' contains deep imports into 'path/to/node_modules/@ckeditor/ckeditor5-watchdog/src/editorwatchdog'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

**Comment by Mgsy** [comment]
Hi, thanks for the report. We're aware of this issue and it's reported here - #181. I'm closing it as a duplicate.
