### ISSUE TITLE
hello how can i add the third party plugins in ckeditor 

### ISSUE THREAD

**Issue by xumoqiu** [ckeditor/ckeditor5-angular#218]
like HTML5 video and so on

How do I refer to third-party plug-ins

`public Editor = ClassicEditor;
    public config = {
       
        extraPlugins: 'html5video,widget,widgetselection,clipboard,lineutils',
        uploadUrl: 'https://api.net/api/ECategoryDetail/UploadImg',

      };`

`    <ckeditor [config]="config" [editor]="Editor" [(ngModel)]="editorData" (ready)="onReady($event)"></ckeditor>`

**Comment by FilipTokarski** [comment]
Hi, it seems you are trying to use CKEditor4 plugins with CKEditor5. CKE4 and CKE5 are two separate apps, with different architecture and they are not compatible in this way ( you cannot use plugins from CKE4 in CKE5 ). Here you can read more about plugins in CKEditor5:
- [plugins overview](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/plugins.html)
- [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)
- [configuration docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html)
  
Apart from this, if you want to integrate CKEditor5 in Angular app, please see [integration docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html) and especially the part about [using custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build).

**Comment by xumoqiu** [comment]
thanks
