### ISSUE TITLE
How to attach listener to event from editorInstance

### ISSUE THREAD

**Issue by HadiAyoub** [ckeditor/ckeditor5-angular#219]
👋 Hey!

First I'll give some background on what I'm trying to achieve:

> I'm trying to use the markdown feature of the editor for a chat system. I've managed to get markdown output working with a custom build. What I'm trying to account for now is a user trying to paste or insert in some content that includes something I don't want to display (eg, an inline image) or something that isn't markdown. The editor is generating HTML for the image being pasted...

My hunch is that I need to use the editorInstance and work my magic in the 'paste' event, but I've seen the usage of editorInstance questioned a few times in other issues (saying "why not use onReady) and I haven't been able to get it to work (docs aren't suuuuuper clear on this part): the editorInstance is always null even if I'm trying to access it in onReady (unless I wrap it in a timeout), and I can't get a paste event to work on it.

Any ideas, help, suggestions of another way I could do this would be very appreciated.
Thanks!

**Comment by Mgsy** [comment]
@ma2ciek, can you take a look at it?

**Comment by ma2ciek** [comment]
Hey, @HadiAyoub

> the editorInstance is always null even if I'm trying to access it in onReady (unless I wrap it in a timeout), and I can't get a paste event to work on it.

Could you post a code snippet that shows how you try to access the editor instance? The editor should be possible to get using the `onReady` callback or using the `editorInstance` property once the editor is initialized.

**Comment by HadiAyoub** [comment]
template
`<ckeditor #editor [editor]="editorBuild" (ready)="onReady($event)" (change)="onChange($event)" [config]="config"></ckeditor>
`

controller

```
    @ViewChild( 'editor' ) editorComponent: CKEditorComponent;

    ...

    public onReady(editor){
        console.log(this.editorComponent.editorInstance); //null
    }
```

This is just one of many attempts. Similarly, had many attempts to actually listen for the paste event with no luck.

**Comment by ma2ciek** [comment]
Just use:

```
    @ViewChild( 'editor' ) editorComponent: CKEditorComponent;

    ...

    public onReady(editor){
        console.log(editor);
    }
```

After looking at the code it seems that the `this.editorComponent.editorInstance` getter can't be yet accessed as the editor creator promise isn't resolved yet - a 0s setTimeout on the `ckeditor5-angular` component's side should be enough to fix the situation. Thanks for the report.

**Comment by ma2ciek** [comment]
For the `paste` see https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/clipboard.html. In CKEditor5 there's no such thing like a `paste` event. Clipboard pipelines are a bit more complex.

**Comment by HadiAyoub** [comment]
Beautiful, thank you! Huge help.
One last question, is this a valid use-case for requiring the editorInstance?

**Comment by ma2ciek** [comment]
> is this a valid use-case for requiring the editorInstance?

Everything that is used to customize the CKEditor 5 editor's behavior needs to access the instance and operate on it directly. So accessing the editor instance is 100% valid.
