### ISSUE TITLE
Document editor needing extra divs 

### ISSUE THREAD

**Issue by Foxandxss** [ckeditor/ckeditor5-angular#22]
If we look at the official documentation, the document editor needs a structure like:

```html
<div class="document-editor">
    <div class="document-editor__toolbar"></div>
    <div class="document-editor__editable-container">
        <div class="document-editor__editable">
            <p>The initial editor data.</p>
        </div>
    </div>
</div>
```

The important bits in here are the `.document-editor__toolbar` and `.document-editor__editable-container` divs. They are containers for the toolbar and the content itself.

With this component, we get something like:

```html
<ckeditor ...>
  <div class="... ck-toolbar .."></div>
  <div class="... ck-content ..">
     <p>The initial editor data.</p>
  </div>
</ckeditor>
```

On the one hand, the `.ck-toolbar` will contain directly the toolbar pieces instead of an extra div.
I believe this could be fixed by creating that extra div by hand, and hacking the html at `ready` and then insert the toolbar in there.

More importantly, the content itself. It is added as a `<p>` inside that `.ck-content` and if you see the first example, there is an extra div in between.

The reason this is important, is for creating the "word look & feel" where you have a sheet of white paper (the `.document-editor__editable` inside a silver background `.document-editor__editable-container`.

More info [here](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/ui/document-editor.html)

**Comment by ma2ciek** [comment]
Hi, @Foxandxss.

You're right, these two HTML structures slightly differ. The thing is, that with the `DocumentEditor` the developer should be responsible for the HTML structure as this editor provides a more elastic customization than the other ones. I'll update the `ckeditor5-angular`'s docs, so the docs will match the https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/ui/document-editor.html#html, but it will be just creating one more div in the `ready` event subscriber.

**Comment by ma2ciek** [comment]
Or maybe you're right and it can't be done easily, because the `document-editor__editable` is nested in the docs... I'll check it.

**Comment by Foxandxss** [comment]
Yeah, the problem is that we don't control the HTML we generate. The component's template is "empty" and it gets filled with the `tagName` and that is it. We have no control over how we want the different pieces to be generated.

**Comment by raducostea** [comment]
Are there any workarounds right now?

**Comment by ma2ciek** [comment]
For now, you can create another div inside the `<ckeditor>` component, style it as you want and add the editable element into it, I mean:

```ts
onReady( editor: any ) {
    const editableContainer = document.createElement( 'div' );
    const parent = editor.ui.view.editable.element.parentElement;

    parent.removeChild( editor.ui.view.editable.element );
    editableContainer.appendChild( editor.ui.view.editable.element );

    parent.appendChild( editor.ui.view.toolbar.element );
    parent.appendChild( editableContainer );
}
```

**Comment by ma2ciek** [comment]
But I agree, that having this would be better and more explicit:

```html
<ckeditor>
	<ckeditor-toolbar>
	<div>
		<ckeditor-editable-element>
	<div>
</ckeditor>
```

**Comment by ma2ciek** [comment]
This issue is a little bit related to the https://github.com/ckeditor/ckeditor5-angular/issues/14 and they both could be fixed together by enabling the above syntax.

**Comment by ma2ciek** [comment]
I'm closing this issue as there's an option to quickly workaround it like I mentioned [here](https://github.com/ckeditor/ckeditor5-angular/issues/22#issuecomment-414636272). There might be plenty of various editor builds as bases for `<ckeditor>` component and we can't make all of them work out of the box if they heavily depend on the HTML structure of the document.

**Comment by gvillot-macquarie** [comment]
The workaround works well.
But the con of this approach is about the error when trying to remove the editor element:

![image](https://user-images.githubusercontent.com/96264351/163331363-eee1b1ee-e7d1-45ff-bcb5-1b3f934e5d36.png)

https://github.com/ckeditor/ckeditor5-angular/blob/175da814e70261fc3e2a238fdeb44b93dc374be0/src/ckeditor/ckeditor.component.ts#L340

Is there a way to way this ?
