### ISSUE TITLE
editorInstance is empty when the ready event fires

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#220]
Originally reported in #219. 

> After looking at the code it seems that the `this.editorComponent.editorInstance` getter can't be yet accessed as the editor creator promise isn't resolved yet - a 0s setTimeout on the `ckeditor5-angular` component's side should be enough to fix the situation. Thanks for the report.

**Comment by przemyslaw-zan** [comment]
I am unable to reproduce this. If someone still experiences this issue, please provide detailed reproduction steps.
