### ISSUE TITLE
Error with Simple Upload

### ISSUE THREAD

**Issue by brdppl** [ckeditor/ckeditor5-angular#221]
Hi, I created a Custom Build and I'm trying to use the Simple Upload Plugin, but I run into the following error after uploading an image (the upload happens normally)
![Screenshot_5](https://user-images.githubusercontent.com/31192198/88536625-8d653480-cfe2-11ea-8f35-63e99f2923e2.jpg)

My TS:
```
public Editor = ClassicEditor
  public EditorConfig = {
    simpleUpload: {
      uploadUrl: `${environment.baseUrl}/api/upload-ckeditor`,
      headers: {
        Accept: 'application/json, text/plain, */*',
        Authorization: this.loginService.userVerify().token
      }
    }
  }
```

My HTML:
`<ckeditor [editor]="Editor" [config]="EditorConfig" formControlName="conteudo"></ckeditor>`

**Comment by ma2ciek** [comment]
Hi @brdppl,

It looks like an internal CKEditor 5 error. Could you share more information about the build you created? (I mean the `package.json` file and the entry point of the application)

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
