### ISSUE TITLE
Error when using the Font plugin

### ISSUE THREAD

**Issue by santonini82** [ckeditor/ckeditor5-angular#223]
Following this guide (https://ckeditor.com/docs/ckeditor5/latest/features/font.html#installation) for installing and using plugin in an angular project, when plugin is added to toolbar,  application fails:

**Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated**

**Comment by FilipTokarski** [comment]
Hi, [this error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) occurs beacause in Angular you cannot just add a plugin to the editor, you need to create a custom build first and then integrate it with Angular. Please see our docs on: 
- [Angular integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build)
- [Creating custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html)
- [Adding plugin to an editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor)
- [Quick start](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html)

You can also use our [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/) to create a ready-to-use editor with all the plugins that you need.

**Comment by santonini82** [comment]
Hi, Thanks for the reply.
I created a custom build using the online builder tool, and followed the suggested guides.
Unfortunately, the component still goes wrong:

`ERROR Error: Uncaught (in promise): TypeError: this.editor.create is not a function
creator/</</</</<@http://localhost:4199/vendor.js:101735:91
step@http://localhost:4199/vendor.js:166653:23
verb/<@http://localhost:4199/vendor.js:166634:53
__awaiter/<@http://localhost:4199/vendor.js:166627:71
ZoneAwarePromise@http://localhost:4199/polyfills.js:3268:29
__awaiter@http://localhost:4199/vendor.js:166623:12
creator/</</<@http://localhost:4199/vendor.js:101728:97
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4199/polyfills.js:2749:26
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://localhost:4199/polyfills.js:2508:43
./node_modules/@angular/core/fesm5/core.js/NgZone.prototype.runOutsideAngular@http://localhost:4199/vendor.js:53381:28
creator/</<@http://localhost:4199/vendor.js:101725:51
step@http://localhost:4199/vendor.js:166653:23
verb/<@http://localhost:4199/vendor.js:166634:53
__awaiter/<@http://localhost:4199/vendor.js:166627:71
ZoneAwarePromise@http://localhost:4199/polyfills.js:3268:29
__awaiter@http://localhost:4199/vendor.js:166623:12
creator@http://localhost:4199/vendor.js:101722:100
create/<@http://localhost:4199/vendor.js:102174:17
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4199/polyfills.js:2749:26
onInvoke@http://localhost:4199/vendor.js:53422:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://localhost:4199/polyfills.js:2748:52
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://localhost:4199/polyfills.js:2508:43
scheduleResolveOrReject/<@http://localhost:4199/polyfills.js:3247:34
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4199/polyfills.js:2781:31
onInvokeTask@http://localhost:4199/vendor.js:53413:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4199/polyfills.js:2780:60
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4199/polyfills.js:2553:47
drainMicroTaskQueue@http://localhost:4199/polyfills.js:2959:35`

The guides you sent me seem very confusing.
It is not clear whether the plugin should be installed with npm install (as suggested here [Adding plugin to an editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-an-editor) ) or not because it is already included in the custom build.
In general, it is not clear when a guide is also suitable for an angular project.
I believe that specific guides must be written for the various frameworks.

**Comment by santonini82** [comment]
I tried to perform the procedure again exactly as described in the guidelines:

[Installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build)
[Using a custom CKEditor 5 build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build)

This time, instead of using the online builder tool, I downloaded the project and followed the 'Adding a plugin to a build' procedure.

The error is the same:

**Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.**

**Comment by FilipTokarski** [comment]
In order to look into this issue we'll need more information - this means a detailed step-by-step description of how to reproduce this, your editor configuration and your `package.json` contents. Meanwhile, please see [duplicated modules error docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules), because it might be that you are using a build instead of an editor class, or you're loading plugins which have different version.

**Comment by santonini82** [comment]
Ok.
Thanks to your last comment I was able to identify the problem.
As you suggested there was a misalignment between version of plugin and that of the other installed packages:

"devDependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^19.0.0",
    "@ckeditor/ckeditor5-alignment": "^**21.0.0**",      <-------------
    "@ckeditor/ckeditor5-autoformat": "^19.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^19.0.0",
    "@ckeditor/ckeditor5-block-quote": "^19.0.0",
    "@ckeditor/ckeditor5-ckfinder": "^19.0.0",
    "@ckeditor/ckeditor5-core": "^**19.0.0**",  <-------------
    "@ckeditor/ckeditor5-dev-utils": "^13.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^9.0.0",
     .....

Thank you very much for helping
