### ISSUE TITLE
CKEditor automatically folds the toolbar in the Ng-Module

### ISSUE THREAD

**Issue by FindEvery** [ckeditor/ckeditor5-angular#224]
I tried to put CKEditor in the NG-module, but the toolbar was automatically hidden in more tools. I did not find the parameter description and solution of this problem in the official document. Could you please give me some guidance?

**Comment by ma2ciek** [comment]
Hi @FindEvery,

> but the toolbar was automatically hidden in more tools

Could you describe it clearer? Or perhaps attach some gifs/screenshots that could show the problem?

**Comment by FindEvery** [comment]
![微信截图_20200907135749](https://user-images.githubusercontent.com/44216474/92353150-323d5c00-f0cf-11ea-81a4-5087bf5992a8.png)
like this,I want to show all toolbar

**Comment by FindEvery** [comment]
I want to show all toolbar ,but it only show three points,

**Comment by FindEvery** [comment]
If the picture above doesn't show the problem, please refer to the picture below. I'm using the Decument Editor type in an Angular project
![20200907162435](https://user-images.githubusercontent.com/44216474/92365725-c1ed0580-f0e3-11ea-8d2c-456e10814b79.png)

**Comment by FilipTokarski** [comment]
Hi, I just created a document editor following [Angular integration docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html) and the toolbar is visible, right where it should be. I'd advise to double check whether you have everything correct in your config, especially [this part](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#using-the-document-editor-build).
