### ISSUE TITLE
How to Binding raw text to model

### ISSUE THREAD

**Issue by graphicsxp** [ckeditor/ckeditor5-angular#225]
I cannot find a way to bind the ckeditor raw text to my model. In fact I don't see how to access raw text at all.

This is problematic because I'm trying to validate the length of the text, which should be less than 200 characters. And my model property bound to CKEditor also contains the HTML markups, which leads to wrong text length.

Is this possible to achieve  ?

**Comment by ma2ciek** [comment]
Hi @graphicsxp,

Do you mean https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html?

**Comment by graphicsxp** [comment]
@ma2ciek , kind of. But the word count is more for display purpose. In my case i want to validate the max length of my model property bound to the ngmodel attribute of the ckeditor. Again, this is angular version of ckeditor.
The problem is that the ngmodel attribute gives me the full text (including html markup) so I cannot validate the length based on that.

**Comment by ma2ciek** [comment]
The CKEditor 5 Angular integration component doesn't support such option. It could be easily achieved without depending on the NgModel as it limits to only one value and use the [https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html](https://ckeditor.com/docs/ckeditor5/latest/features/word-count.html).

You could try something like:

```javascript

const div = document.createElement( 'div' ); 
div.innerHTML = data; 

console.log( div.innerText.length ); 
```

but I'd be carefull about using innerHTML and some security issues.

> want to validate the max length of my model property bound to the ngmodel attribute of the ckeditor

Another option is to change the https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_dataprocessor_dataprocessor-DataProcessor.html but it would be a tough job.

**Comment by graphicsxp** [comment]
Could this feature be implemented in the repo ? I'm not confident in changing the data processor and the first solution sounds a bit hacky, although I'll give it a try.

**Comment by ma2ciek** [comment]
> Could this feature be implemented in the repo ?

It's almost impossible to implement. The `NgModel`'s value can't be trimmed inside the component as it is used to feed the editor. So you'd have the `<p>foo</p><p>bar</p>` -> `foobar` -> `<p>foobar</p>` conversion inside the editor that would break your initial data.

Actually, changing the data processor won't work in combination with the ngModel here either. So the only way is to do something with the data afterwards.
