### ISSUE TITLE
Release ckeditor5-angular@2.0.0

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#226]
Changes in the #183 break older versions of Angular (\<9) so a new major version needs to be made. This way we could even release some hotfixes on the 1.x.x branch (as the support for Angular@8 ends in November 2020). Also, it should be created a tag for the 1.x.x branch.

**Comment by oleq** [comment]
I guess this can be closed as per https://github.com/ckeditor/ckeditor5-angular/releases/tag/v2.0.0?
