### ISSUE TITLE
Add information about supported Angular versions in docs.

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#227]
Currently, there's no information on https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html about supported Angular versions. This information may be needed by our clients. 

Also, this information should be synced with the one provided by the package on NPM / Github - https://www.npmjs.com/package/@ckeditor/ckeditor5-angular/v/2.0.1

**Comment by AnnaTomanek** [comment]
Both fixed, readme updated.
