### ISSUE TITLE
Image Resize not showing up on Image Toolbar, resize with handles not adding width style to image

### ISSUE THREAD

**Issue by khambley** [ckeditor/ckeditor5-angular#234]
I'm using Angular 8 and Angular Material. I'm using Easy Image for my upload adaptor. The ckeditor is inside a mat-list-item block. I've loaded and enabled the resize image feature both with resizeOptions and resize handles.

The resize buttons are NOT appearing on the image toolbar. The align presentation styles are, but not the resize option buttons. The handles are showing up and I'm able to resize image inside the ckeditor, but it is NOT adding the inline style width to the figure element and it is not adding the image-resized class css styling to the figure element. 

So when it Saves and displays the image in on the HTML page, it is HUGE! full-size! Can I use Image resize feature with Easy Image? What am I doing wrong? Do I need to install another plugin other than Image in order for Resize to work?

**Comment by Mgsy** [comment]
Hi, it seems that there's something wrong with your configuration. Could you share your CKEditor 5 config?
