### ISSUE TITLE
Check compatibility with latest Angular (v11)

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-angular#235]
A similar to CKEditor 4 (https://github.com/ckeditor/ckeditor4-angular/issues/148).

**Comment by pomek** [comment]
Blindly estimating as 0.5 in case if changes in docs will be required.

**Comment by pkwasnik** [comment]
There are two issues with zone.js (possibly not blocking the PR):

*   During update process angular requires zone.js in version "~0.10.3". After that update I've updated zone.js to "~0.11.3" and haven't noticed any issues during tests.
*   Problem with importing zone.js the same like in the past, described here: #109. Solution from https://github.com/ckeditor/ckeditor5-angular/issues/109#issuecomment-497344588 fixes the problem, but anyway there should be created an issue for zone.js about that.

**Comment by ma2ciek** [comment]
I've checked and the Zone.js 0.11 breaking changes are described here - https://github.com/angular/angular/tree/master/packages/zone.js#breaking-changes-since-zonejs-v0111.

Anyway, could you create an issue in Zone.js for the found regression and link it here?
