### ISSUE TITLE
Outdated piece of info in the documentation

### ISSUE THREAD

**Issue by alx1004** [ckeditor/ckeditor5-angular#243]
Hi guys,
Skimming thru our docs for angular, I have noticed one minor statement that I think does not apply anymore:

![image](https://user-images.githubusercontent.com/43168871/106120151-52d98180-6156-11eb-9ffc-925e45b09d6f.png)

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html

Hope it's relevant!

**Comment by godai78** [comment]
Merged in: ckeditor/ckeditor5#8944
