### ISSUE TITLE
How to make "enter" insert a soft break instead of a paragraph

### ISSUE THREAD

**Issue by issambaccouch** [ckeditor/ckeditor5-angular#244]
hi 
how can i add enterMode or any other solution to my config to make soft-break instead paragraph with enter key in angular , because ck5 is not supporting enterMode .
```
 editorConfig = {
    toolbar: {
      items: [
        'heading',
        'fontSize',
        'fontColor',
        'bold',
        'underline',
        'link',
        'bulletedList',
        'numberedList',
        '|',
        'undo',
        'redo',
      ]
    },
  };  
```

**Comment by ma2ciek** [comment]
CKEditor 5 only supports soft breaks inside paragraphs and they can be done using `shift` + `enter`. It is not configurable like in previous versions.

**Comment by Mgsy** [comment]
As a workaround, you can try to swap the native behaviour to insert `<br>` after pressing Enter and a new paragraph after pressing Shift + Enter. [See this comment](https://github.com/ckeditor/ckeditor5/issues/4570#issuecomment-483601793) to learn more.

**Comment by issambaccouch** [comment]
thank you @Mgsy for reply i appreciate that , i wanted to switch enter key to do <br> , at the end i used custom css the solve this without adding plugins . for anyone want the same result , you can use the css below by add it in style.scss

`.ck-editor__editable_inline p{
  margin: 0%;
}`
