### ISSUE TITLE
collection-get-invalid-arg is thrown in Watchdog

### ISSUE THREAD

**Issue by getsnoopy** [ckeditor/ckeditor5-angular#245]
## 📝 Provide detailed reproduction steps (if any)

1. Use any version of `@ckeditor/ckeditor5-build-classic` (I'm using `v12.1.3`).
2. Set up the editor with Watchdog with any version higher than `v11.0.0` (I'm using `@ckeditor/ckeditor5-angular`).
3. An error `collection-get-invalid-arg: Index or id must be given.` is thrown.

### ✔️ Expected result

No error should be thrown.

### ❌ Actual result

The error is thrown.

## 📃 Other details

* Browser: N/A
* OS: N/A
* First affected CKEditor version: It's independent of the editor, but started with Watchdog version `v11.0.0`.
* Installed CKEditor plugins: N/A
* Bug was introduced in [this commit](https://github.com/ckeditor/ckeditor5-watchdog/commit/692955e#diff-f4e9beeb2f57aa54b525668b51d83d15b838714e797d9b9322cdaa203a43fdb3R336).
* The bug occurs because there were an extra pair of braces put around the variable `rootName`, which made it into an object with the property `rootName` with the value of the variable `rootName`. The `get()` function, however, accepts only a string or a number.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
I transferred this issue to the `ckeditor5-angular` repository.

**Comment by ma2ciek** [comment]
Probably this issue be also fixed by downgrading the version of `ckeditor5-angular`. But I encourage you to have both up to date.

**Comment by getsnoopy** [comment]
The version we are using supports multiple roots as well, but the parameter to the `get()` function was expecting the name of the root as a `string` and not an `object` with the property `rootName`. But I guess the API has been changed at some point later on; interesting. So it seems like `ckeditor5-angular` was depending on an incompatible combo of `ckeditor5-watchdog`/`ckeditor5-editor-classic`.

But we can't upgrade/downgrade the `ckeditor5-angular` because it's tied to the Angular version it depends on as well, and we use Angular 7. I've created a monkey patch for our project for the moment where it just overrides the `EditorWatchdog.prototype._getData` to fix the issue.

It would be good to backport a fix for the version of `ckeditor5-angular` that depends on Angular 7, if possible, so that we can remove that monkey patch though (versions `1.0.x` I believe).

**Comment by ma2ciek** [comment]
> But I guess the API has been changed at some point later on; interesting. So it seems like `ckeditor5-angular` was depending on an incompatible combo of `ckeditor5-watchdog`/`ckeditor5-editor-classic`.

It's impossible as we would catch it quickly. 

> It would be good to backport a fix for the version of `ckeditor5-angular` that depends on Angular 7, if possible, so that we can remove that monkey patch though (versions `1.0.x` I believe).

You can check at [https://github.com/ckeditor/ckeditor5-angular/releases](https://github.com/ckeditor/ckeditor5-angular/releases) that the 1.x.x still supports Angular 7, only the 2.x.x branch is a BC in terms of Angular compatibility. But in your case, it looks that you're using a pretty old version of the CKEditor 5 library, that the `ckeditor5-angular` doesn't support. [https://www.npmjs.com/package/@ckeditor/ckeditor5-build-classic](https://www.npmjs.com/package/@ckeditor/ckeditor5-build-classic) - as you can see the 12.1.0 version was released 2 years ago. Try to bump it as high as you can and keep it up to date in the future.

**Comment by getsnoopy** [comment]
I figured it out. We were pulling in `^1.0.1` of `ckeditor5-angular` and `^11.1.1` of `ckeditor5-editor-classic` (the version specified in the [`package.json`](https://github.com/ckeditor/ckeditor5-angular/blob/b3c40130083f0e2927c01a75eb3ff13b1cca4b12/package.json) of `ckeditor5-angular@1.0.1`), and it was resolving to `ckeditor5-angular@1.2.3` and `ckeditor5-editor-classic@11.2.0`. However, `1.1.1` of `ckeditor5-angular` is the one where you moved to Angular 8 and `1.2.3` was likely pulling in a newer version of Watchdog than is compatible with `ckeditor5-editor-classic@11.1.1`, so it was throwing that error. When I froze the versions at `1.0.1` and `11.1.1`, respectively, it works fine, so it seems like it was a semver issue for `ckeditor5-angular`.

**Comment by getsnoopy** [comment]
Closing the issue since the problem can't really be fixed anymore, as the semver was broken, and the corresponding PR was closed as well. One either needs to freeze the version of `ckeditor5-angular` they are using, or use a later major version of `ckeditor5-editor-classic` to supply to `ckeditor5-angular`.
