### ISSUE TITLE
How to append selected image to editor through custom gallery button

### ISSUE THREAD

**Issue by pankajcharpe** [ckeditor/ckeditor5-angular#246]
Hi,
I am using angular version of ckeditor 5. 
I have created a custom plugin button which opens a gallery modal on clicking.
But I don't know how to append the selected image to editor.
Please guide me on this.
**Plugin.js** 
`// import uploadIcon from './icons/upload.svg';
import imageIcon from '@ckeditor/ckeditor5-core/theme/icons/image.svg';
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';

export default class CustomGallaryPlugin extends Plugin {
	init() {
		const editor = this.editor;

		editor.ui.componentFactory.add( 'gallary', locale => {
			const view = new ButtonView( locale );

			view.set( {
				label: 'Gallary',
				icon: imageIcon,
				tooltip: true
			} );

			// Callback executed once the icon is clicked
			view.on( 'execute', () => {
			// fire a JS event
				// eslint-disable-next-line no-undef
				window.dispatchEvent( new Event( 'onClickGallaryButton' ) );
			} );

			return view;
		} );
	}
}`

**angular component:**
`export class AddImageComponent {
  //ckeditor events
  public componentEvents: string[] = [];
  public Editor = ClassicEditor;
  public editorData =	``;

    //inline editor
  editorConfig = {
    placeholder: 'Start typing here',
    language: 'en'
  };
  // Gallary modal
  @HostListener('window: onClickGallaryButton', ['$event'])
  openGalleryPopup(event) {
    const modalOptions = {
      backdrop: true,
      keyboard: true,
      focus: false,
      show: false,
      ignoreBackdropClick: true,
      class: ' modal-dialog modal-dialog-scrollable modal-fluid',
      containerClass: 'model fade top',
      animated: true,
      data: {
        title: '',
        text: '',
    }
    };
    this.modalRef = this.modalService.show(ImageBrowserComponent, modalOptions);
    this.modalRef.content.galleryResp.subscribe(name => {
        if (name) {
          var img = document.createElement('img'); // Use DOM HTMLImageElement
          img.src = name;
            //How to insert to the editor
        }
      });
  }
}`

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply. I think in this case, you could try [insertImage](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image_utils.html#function-insertImage) function. Alternatively, you could use [`model.insertContent`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent) as a more general approach.
