### ISSUE TITLE
Can't create custom ControlValueAccessor component 

### ISSUE THREAD

**Issue by Myerden** [ckeditor/ckeditor5-angular#248]
Hi, 
I use ckeditor custom build for my project, but now I needed to create a custom component that includes this ckeditor.
There is some issue with implementing `ControlValueAccessor` for ckeditor. It gives always `ExpressionChangedAfterItHasBeenCheckedError`. I use same code for html `input` element but no error occurs.

Here is my component:

**custom-editor.component.html**
```
<ckeditor #editor [config]="EditorConfig" [editor]="Editor" (ready)="onEditorReady($event)"
  (change)="onModelChange($event)" [(ngModel)]="value">
</ckeditor>
```

**custom-editor.component.ts**
```
import { Component, EventEmitter, forwardRef, Input, OnInit, Output, ViewChild } from '@angular/core';
import { ChangeEvent, CKEditorComponent } from '@ckeditor/ckeditor5-angular';
import { CKEditorConfig } from 'src/app/configs/ckeditor-settings.config';
import { BaseComponent } from 'src/app/core/abstract/base.component';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import * as PerasisEditor from "libs/ckeditor5-build-perasis";
@Component({
  selector: 'app-custom-editor',
  templateUrl: './custom-editor.component.html',
  styleUrls: ['./custom-editor.component.scss'],
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => CustomEditorComponent),
    multi: true, 
  }],
})
export class CustomEditorComponent extends BaseComponent implements OnInit, ControlValueAccessor {

  @ViewChild("editor", {static: true}) 
  editorComponent: CKEditorComponent;
  Editor = PerasisEditor;
  EditorConfig = CKEditorConfig;
  value: string = '';
  isModalVisible = false;
  @Output('change')
  change: EventEmitter<any> = new EventEmitter<any>()
  disabled: boolean;
  private _onChange = (_: any) => { };
  private _onTouched = () => { };

  
  ngOnInit() {
    
  }

  public onEditorReady(editor) {
    editor.ui
      .getEditableElement()
      .parentElement.insertBefore(
        editor.ui.view.toolbar.element,
        editor.ui.getEditableElement()
      );
  }

  public onModelChange(event: ChangeEvent) {
    this._onChange(this.value);
  }

  writeValue(obj: any): void {
    this.value = obj;
    this.changeDetector.markForCheck();
  }

  registerOnChange(fn: any): void {
    this._onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this._onTouched = fn;
  }
  
  setDisabledState?(isDisabled: boolean): void {
    this.disabled = isDisabled;
    this.changeDetector.markForCheck();
  }


}
```
Error:
![image](https://user-images.githubusercontent.com/15304742/113267624-3df8a600-92df-11eb-9aad-e583dfdcffd3.png)

As I sad, when I use this ControlValueAccessor with html input or select element, it works well but I can't use with ckeditor. What am I doing wrong?

Thank you

Angular: 8.0.1
CKEditor-Angularr: 1.2.3

**Comment by FilipTokarski** [comment]
cc @ma2ciek could you take a look at this?

**Comment by ma2ciek** [comment]
Hi @Myerden, 

Could you also share the `BaseComponent`? Or, ideally, a full sample/repo where the problem can be reproduced?

**Comment by ma2ciek** [comment]
Also, I'd not mix the `(change)` and the two-way-binding. I'd either use one of those.

So, perhaps the following:

```
<ckeditor [ngModel]="value" (ngModelChange)="onModelChange($event)">
```

Perhaps there might be a small bug in the order of calls when you rely on both, `onChange` and `[ngModel]` at the same time.

**Comment by Myerden** [comment]
Thanks for your answer,

**base.component.ts**
```
export abstract class BaseComponent implements OnInit {
  
  constructor(
    @Optional() public authService: AuthService,
    @Optional() public postService: PostService,
    public changeDetector: ChangeDetectorRef,
    public routeStateService: RouteStateService,
    public route: ActivatedRoute,
    public router: Router,
    public location: Location,
    public slugifyPipe: SlugifyPipe,
    public datePipe: DatePipe,
    public fb: FormBuilder,
   
  ) {

    // do something

  }
  
}
```

I changed some codes as you describe,

`<ckeditor [ngModel]="value" (ngModelChange)="onModelChange($event)">`

```
  public onModelChange(data: string) {
    this.value = data;
    this._onChange(this.value);
  }
```

this fixs my component's issue, now I can use `ngModel` attribute. 

---

But I realized that my problem not related with here. I use my custom editor as follows:

html:
```
<div *ngFor="let content of editorContents; let i=index">
	<app-custom-editor [(ngModel)]="content"></app-custom-editor>
</div>
```
ts:
`editorContents: string[] = [];`

This is causing **ExpressionChangedAfterItHasBeenCheckedError**. When I use **ngModel** with `*ngFor`, something is going wrong and errors occurs.

---

I found a temporary solution: I have created two different arrays, the first one for `ngFor`, the second one for `ngModel`. Now I can use my editor without any problem.
```
<div *ngFor="let content of editorContents; let i=index">
	<app-custom-editor [(ngModel)]="editorContents2[i]"></app-custom-editor>
</div>
```
ts:
```
editorContents: string[] = [];
editorContents2: string[] = [];
```
