### ISSUE TITLE
How to implement drag and drop feature in Angular?

### ISSUE THREAD

**Issue by Zcaw** [ckeditor/ckeditor5-angular#249]
I am using the document editor in an Angular 8 project and I would like to implement the drag and drop feature, I see the demo on the documentation, however I do not see any implementation guide on how to actually USE the drag and drop feature in the regular section or Angular section. Any help to get this implemented would be greatly appreciated!

**Comment by FilipTokarski** [comment]
Hi, drag and drop is available by default. However it was introduced in editor version 27.0.0 ( latest ), so please make sure, your editor packages are up to date.

**Comment by Zcaw** [comment]
I have version 27.0.0 

My question is how do I actually implement the drag and drop feature? I see no example on how to implement it into my project, can you help me with that?

**Comment by FilipTokarski** [comment]
As I said, it's available by default in all builds. If you want to install it in some custom editor, please [see the docs](https://ckeditor.com/docs/ckeditor5/latest/features/pasting/drag-drop.html#installation).
