### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules

### ISSUE THREAD

**Issue by ManikandanTh** [ckeditor/ckeditor5-angular#259]
Hi, 
I have tried to install plugins to use custom build but we need more toolbars , so we are trying to use decouple editor 

I am using Custom build and decuple editor in same projects in different modules(Lazy loading). but it show ERROR : **`CKEditorError: ckeditor-duplicated-modules`**  In Angular 11

**Comment by Mgsy** [comment]
Hi! If you'd like to use multiple builds on one page, you'll need to [create a super build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors).
