### ISSUE TITLE
HOW TO GET FONT SIZE IN THE CLASSIC CKEDITOR ?

### ISSUE THREAD

**Issue by DhivyaGopal** [ckeditor/ckeditor5-angular#260]
Hi,
I have tried to use Classic editor to get font size, but it shows 
> Cannot read property 'create' of undefined
>     at CertificateTemplateFormatDialogComponent.ngOnInit (certificate-template-format.dialog.component.ts:85)
>     at callHook (core.js:2535)
>     at callHooks (core.js:2506)
>     at executeInitAndCheckHooks (core.js:2457)
>     at refreshView (core.js:9433)
>     at renderComponentOrTemplate (core.js:9532)
>     at tickRootContext (core.js:10758)
>     at detectChangesInRootView (core.js:10783)
>     at RootViewRef.detectChanges (core.js:22751)
>     at ApplicationRef.tick (core.js:29491)

So that i have tried to install font plugins to get font size
> npm install --save @ckeditor/ckeditor5-font
After this installation it shows lot of file changes nearly 1K files changes

imported in ckeditor5\src\ckeditor.js
```
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize.js';
Editor.builtinPlugins = [ FontSize,... ]
```
_component :_ 
**____.module.ts:**

```
 import { CKEditorModule } from '@ckeditor/ckeditor5-angular';

 @NgModule({
     imports: [
         SharedModule,
         CoreRoutes,
         CKEditorModule
     ]})
```

**____.component.ts:**
```
import * as Editor from '../../../app/ckeditor5/build/ckEditor';
public config = {
        toolbar: ['heading', '|', 'fontFamily', "fontSize", 'bold', 'italic', 'imageUpload', 'Alignment', 'font'],
    };
```

**_____.component.html:**
```
<ckeditor [editor]="Editor" (ready)="onReady($event)" (change)="onChange($event)" [(ngModel)]="data"
                    name="data" id="editor" [config]="config"></ckeditor>
```

**console:**
![image](https://user-images.githubusercontent.com/83198811/120157918-27a09500-c211-11eb-8662-14b8634f7a8e.png)

After that We have referred so much website. so we have decided to make npm run build in ckeditor file. 
**Terminal:**

 `src\app\ckeditor5> npm run build`

 ckeditor5-custom-build@0.0.1 build D:\-------> src\app\ckeditor5
 webpack --mode production

 [webpack-cli] Failed to load 'D:\-------> src\app\ckeditor5\webpack.config.js' config
 [webpack-cli] Error: Cannot find module '@ckeditor/ckeditor5-dev-utils'
 
 npm ERR! code ELIFECYCLE
 npm ERR! errno 2
 npm ERR! ckeditor5-custom-build@0.0.1 build: `webpack --mode production`
 npm ERR! Exit status 2
 npm ERR!
 npm ERR! Failed at the ckeditor5-custom-build@0.0.1 build script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

HOW TO GET FONT SIZE IN THE CLASSIC CKEDITOR ?

**Comment by FilipTokarski** [comment]
Hi, the current Angular integration doesn't allow to simply add custom plugins like you would in React or Vue. You first need to create a custom build and then integrate it with your Angular app. You can do it by following docs on [creating build from source](https://ckeditor.com/docs/ckeditor5/26.0.0/builds/guides/development/custom-builds.html) or using [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/). 
Please refer to [Angular integration docs](https://ckeditor.com/docs/ckeditor5/26.0.0/builds/guides/integration/frameworks/angular.html#using-a-custom-ckeditor-5-build) for detailed information.
