### ISSUE TITLE
I am not able to find Full screen view in CKE5 editor

### ISSUE THREAD

**Issue by neeraj-chhatani** [ckeditor/ckeditor5-angular#272]
Hi,
One very important plugin is missing as I am not able to find full screen view mode or maximize plugin in CKE5 editor.
![FULL-SCREEN_CKE5](https://user-images.githubusercontent.com/37043826/128526626-387c82bf-63eb-439c-8a0d-66730be6a6e6.PNG)

Please help me ASAP

**Comment by FilipTokarski** [comment]
Hi, in CKEditor 5 there is no official full screen/maximize plugin. There is a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/1235), so feel free to join the discussion there and add 👍  to bump its popularity.
I'll close this as a duplicate.

**Comment by pikulinpw** [comment]
Following the discussion about the feature to maximize the editor to full screen, I developed a plugin that solves this problem. I would appreciate it if you tried it and share your experience using it. Any additions, suggestions or questions are welcome. Your feedback will help make the plugin even better!

https://github.com/pikulinpw/ckeditor5-fullscreen
