### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by YuriiZadorozhnyi** [ckeditor/ckeditor5-angular#280]
When CKEditor receives a null value I've got an error - "TypeError: Cannot convert undefined or null to object".
I believe that this should be handled by CKEditor, even though provided input type is a "string".

The same issue I've found in the ckeditor/ckeditor5-vue issues - https://github.com/ckeditor/ckeditor5-vue/issues/39

**Comment by sergey-morenets** [comment]
Hi @YuriiZadorozhnyi 

Yes, the same issue reproduced in my project. So I just had to initialize the initial value with empty string:

`  editorText= '';`

```
<ckeditor [(ngModel)]="editorText" [editor]="Editor" [ngModelOptions]="{standalone: true}"
(ready)="onReady($event)"></ckeditor>
```

**Comment by YuriiZadorozhnyi** [comment]
Hi, @sergey-morenets. Yep, I've fixed it in almost the same way `editorText = value ?? '';` but I still think that it should be fixed in CKEditor. I hope that someday it will be fixed :)
Thanks for sharing the info.

**Comment by przemyslaw-zan** [comment]
As explained in https://github.com/ckeditor/ckeditor5-vue/issues/39#issuecomment-473268525, this is expected behaviour.
