### ISSUE TITLE
CKSource does not exist

### ISSUE THREAD

**Issue by ChipClark** [ckeditor/ckeditor5-angular#281]
After cloning the project and installing the node modules, the project would not compile.  CKSource does not exist. 
import * as CKSource from '../../../ckeditor/src/ckeditor';  doesn't exist

```
src/app/watchdog-demo/watchdog-demo.ts:36:58 - error TS2339: Property 'Context' does not exist on type 'typeof import("C:/Sites/ckeditor5-angular/ckeditor/src/ckeditor")'.

36      this.watchdog = new CKSource.ContextWatchdog( CKSource.Context );
```

**Comment by FilipTokarski** [comment]
Hi, did you follow the [docs on Angular integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html)? If you believe there's a bug somewhere in the editor, we'll need more information about your environment and precise steps to reproduce the issue.

**Comment by FilipTokarski** [comment]
Hi, did you follow the [docs on Angular integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html)? If you believe there's a bug somewhere in the editor, we'll need more information about your environment and precise steps to reproduce the issue.

**Comment by ChipClark** [comment]
After following the steps to get the basic CKEditor working on Angular, everything works.

However, clone the github project, and the project will not run.  It’s not an issue with the editor, but the project.

I have decided to use another editor, so I don’t care if you fix this.

Chip Clark | Development Engineer | Allen Matkins
***@***.******@***.***> | Direct (949) 854-5457

**Comment by FilipTokarski** [comment]
Thanks for the reply. I just checked it and the repository demo works fine for me after installing and building. Could you  possibly share some more details on this (your node version, precise steps to reproduce, os, etc.)?

**Comment by ChipClark** [comment]
Hello –

Here is the process I used.

λ node -v
v12.20.1

λ npm -v
6.14.10

git clone https://github.com/ckeditor/ckeditor5.git

cd ckeditor5

npm i


  *   Not sure what I did the first time, but this did compile.

Sorry for the confusion.


Chip Clark | Development Engineer | Allen Matkins
***@***.******@***.***> | Direct (949) 854-5457

**Comment by FilipTokarski** [comment]
Thanks, so I guess we can close this ticket for now.
