### ISSUE TITLE
Support DLL Builds

### ISSUE THREAD

**Issue by mdgilene** [ckeditor/ckeditor5-angular#288]
I don't believe there is anyway to load CKEditor5 via DLL builds under the current implementation. I have been able to get DLL builds to work in angular but I am unable to use the official component to do so, effectively needing to re-implement the component myself.

**Comment by ma2ciek** [comment]
Can you explain why you were struggling and what can be missing in the current documentation/implementation?

**Comment by pomek** [comment]
Closing due to lack of feedback.
