### ISSUE TITLE
How to preserve Custom attributes for table tag

### ISSUE THREAD

**Issue by krishnareddyML** [ckeditor/ckeditor5-angular#292]
Hi,

 We tried to build table html from database content and loading that data in editor. but whenever we read this data, after changes in editor the custom attributes (id, class etc) are disappearing from content. Can you please suggest how do we preserve these ?

**Comment by FilipTokarski** [comment]
Hi, you can use [general HTML support](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html) plugin to enable attributes that are not supported in the editor by default.

**Comment by krishnareddyML** [comment]
Thank you ..Now I am able to preserve the attributes easily with this plugin.
