### ISSUE TITLE
The <CKEditor> component requires using CKEditor 5 in version 34 or higher.

### ISSUE THREAD

**Issue by AlanObject** [ckeditor/ckeditor5-angular#313]
I am using a custom build from the online utility.   When I use it with the Angular package I get the following error:

```ckeditor-ckeditor5-angular.js:142 The <CKEditor> component requires using CKEditor 5 in version 34 or higher.```

Looking into the package.json in the editor build itself I see:

```json
{
  "name": "ckeditor5-custom-build",
  "author": "CKSource",
  "description": "A custom CKEditor 5 build made by the CKEditor 5 online builder.",
  "version": "0.0.1",
  "license": "SEE LICENSE IN LICENSE.md",
  "private": true,
  "main": "./build/ckeditor.js",
  "devDependencies": {
    "@ckeditor/ckeditor5-autoformat": "^33.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^33.0.0",
    "@ckeditor/ckeditor5-block-quote": "^33.0.0",
    "@ckeditor/ckeditor5-cloud-services": "^33.0.0
(etc)
```

This shows two possible issues: 1) the version of the custom package is 0.0.1 which sure doesn't seem like 34 or greater, and the dependencies used are all 33.0.0 which also aren't 34 or greater.

So far I am getting functionality, but the warning message is troublesome and may indicate problems I haven't been affected by yet.

Does the online package generator need to be updated?

**Comment by FilipTokarski** [comment]
Hi, I wasn't able to reproduce this. Recently there was a release of new editor version, together with release of integrations and online builder. It may be that you used the newest Angular integration and at the same time downloaded the editor from online builder, just before it was updated. Anyway, online builder now generates the editor in the latest version (`34.0.0`) and everything should work fine now.

**Comment by AlanObject** [comment]
I'll try generating a new build and report the results here.   With any luck we can just close this issue.

**Comment by pomek** [comment]
It seems to be resolved. Please, reopen if I'm wrong.
