### ISSUE TITLE
Prepare the package for release and release it

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5-angular#329]
Recent changes from https://github.com/ckeditor/ckeditor5-angular/pull/328 requires Angular 13. Because of that, the following actions are needed before releasing the new package:

- Update [CKEditor 5 docs](https://github.com/ckeditor/ckeditor5/blob/master/docs/installation/frameworks/angular.md) about supported Angular versions. Let's add descriptions for the following releases 
	- 3.0.0 (due to bumping the minimal version of Node.js), it should support Angular 9.1+.
	- 4.0.0 requires CKEditor 5 at least in version 34. Please, read [MAJOR BREAKING CHANGES](https://github.com/ckeditor/ckeditor5/releases/tag/v34.0.0).
	- 5.0.0 (the release containing #328) - For Angular 13+ applications.
- Update [README.md](https://github.com/ckeditor/ckeditor5-angular/blob/master/README.md) about supported Angular versions.
	- More or less the same scope of changes like we did in the component guide.

And then release the package.

**Comment by pomek** [comment]
A new version is published: https://github.com/ckeditor/ckeditor5-angular/releases/tag/v5.0.0.
