### ISSUE TITLE
contains deep import

### ISSUE THREAD

**Issue by faizaldong** [ckeditor/ckeditor5-angular#333]
Entry point '@ckeditor/ckeditor5-angular' contains deep imports into 'C:/Users/faizal.kamaruddin/Desktop/others/bpm/node_modules/@ckeditor/ckeditor5-watchdog/src/editorwatchdog'.

**Comment by pomek** [comment]
Dup of https://github.com/ckeditor/ckeditor5-angular/issues/181.
