### ISSUE TITLE
Build error: All declarations of 'CKEDITOR_VERSION' must have identical modifiers.

### ISSUE THREAD

**Issue by tahaerden** [ckeditor/ckeditor5-angular#342]
I have just installed and set up ckeditor5-angular following the Getting Started guide. And I am facing the errors below on build:

```

Error: node_modules/@ckeditor/ckeditor5-angular/ckeditor.component.d.ts:8:9 - error TS2687: All declarations of 'CKEDITOR_VERSION' must have identical modifiers.

8         CKEDITOR_VERSION?: string;
          ~~~~~~~~~~~~~~~~


Error: node_modules/@ckeditor/ckeditor5-angular/ckeditor.component.d.ts:8:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'CKEDITOR_VERSION' must be of type '"32.0.0"', but here has type 'string | undefined'.

8         CKEDITOR_VERSION?: string;
          ~~~~~~~~~~~~~~~~

  node_modules/@types/ckeditor__ckeditor5-utils/src/version.d.ts:5:9
    5         CKEDITOR_VERSION: typeof version;
              ~~~~~~~~~~~~~~~~
    'CKEDITOR_VERSION' was also declared here.


Error: node_modules/@types/ckeditor__ckeditor5-utils/src/version.d.ts:5:9 - error TS2687: All declarations of 'CKEDITOR_VERSION' must have identical modifiers.

5         CKEDITOR_VERSION: typeof version;

```

**My versions are:** 

    "@angular/animations": "~13.3.11",
    "@angular/cdk": "^13.3.9",
    "@angular/common": "~13.3.11",
    "@angular/compiler": "~13.3.11",
    "@angular/core": "~13.3.11",
    "@angular/forms": "~13.3.11",
    "@angular/material": "^13.3.9",
    "@angular/material-moment-adapter": "^13.3.9",
    "@angular/platform-browser": "~13.3.11",
    "@angular/platform-browser-dynamic": "~13.3.11",
    "@angular/router": "~13.3.11",
    "@ckeditor/ckeditor5-angular": "^4.0.0",
    "@ckeditor/ckeditor5-build-classic": "^35.4.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

**Temporary fix that works:**

- Go to file \node_modules\@ckeditor\ckeditor5-angular\ckeditor.component.d.ts
- Comment out CKEDITOR_VERSION?: string; on line 8.

**Comment by FilipTokarski** [comment]
We checked the guide on [integration with Angular](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/angular.html) and had no problems with running the editor.
  
Are you able to provide detailed steps to reproduce this problem?

**Comment by tahaerden** [comment]
What I basically did step by step is: 

1. npm install --save @ckeditor/ckeditor5-angular
2. npm install --save @ckeditor/ckeditor5-build-classic
3. Added CKEditorModule to my module
4. Added public Editor = ClassicEditor; and its import to TS.
5. Added <ckeditor [editor]="Editor" data="<p>Hello, world!</p>"></ckeditor> to HTML.
6. Added const ClassicEditorBuild: any; to typings.d.ts.

And faced the error on npm start. Maybe it's a specific bug in the Angular and Ckeditor versions that I use.

[Here ](https://stackoverflow.com/questions/73248657/all-declarations-of-ckeditor-version-must-have-identical-modifiers)you can see someone else had the exact same issue, and I used the best answer for a temporary fix.

**Comment by tahaerden** [comment]
@pomek The issue seems to be fixed in my case. Thank you 👍
