### ISSUE TITLE
Error: Module not found: Error: Can't resolve '@ckeditor/ckeditor5-watchdog/src/editorwatchdog'

### ISSUE THREAD

**Issue by sergey-morenets** [ckeditor/ckeditor5-angular#349]
Hi

We tried to upgrade from 4.0 to 5.0 in our project but failed because of this error during project build:

./node_modules/@ckeditor/ckeditor5-angular/fesm2020/ckeditor-ckeditor5-angular.mjs:4:0-77 - Error: Module not found: Error: Can't resolve '@ckeditor/ckeditor5-watchdog/src/editorwatchdog' in '\node_modules\@ckeditor\ckeditor5-angular\fesm2020'

Angular: 15.1.2

**Comment by pomek** [comment]
Hi,

Please, try to install the latest CKeditor 5 Angular integration ([`v5.1.1`](https://github.com/ckeditor/ckeditor5-angular/releases/tag/v5.1.1)) and let us know if it works.

The watchdog package is marked as a dependency, so the package manager (npm/yarn/pnpm) should install it.

![image](https://user-images.githubusercontent.com/2270764/219592222-27dad4ab-7e5d-448e-a15e-6a854932c340.png)

**Comment by sergey-morenets** [comment]
Hi @pomek 

Thank you for the quick response. Just checked 5.1.1 and project is built without errors.

**Comment by pomek** [comment]
Good to hear that!
