### ISSUE TITLE
Make editor id public

### ISSUE THREAD

**Issue by ulrikdom** [ckeditor/ckeditor5-angular#367]
Hi.

I want to implement the context watchdog to implement better error-handling. But since I can't access the id of the editor it's impossible to know which editor that emited which event. Could you make the id property of the component public?

**Comment by pomek** [comment]
Hi @ulrikdom,

Just to make sure we talk about the same thing. Is it this property? 👇 

https://github.com/ckeditor/ckeditor5-angular/blob/2b3c88bf974a0c263a3a6b33123a2635dd2256b5/src/ckeditor/ckeditor.component.ts#L234

**Comment by ulrikdom** [comment]
Yes, that's the one

**Comment by pomek** [comment]
Let's add a method: `getId()` that returns a value of the `id` property.
