### ISSUE TITLE
PastePlainText

### ISSUE THREAD

**Issue by Tiru150837** [ckeditor/ckeditor5-angular#372]
Is there any other possibility to change the ctrl+shift+V shortcut to the ctrl+v to paste the plain text without formatting?

I want ctrl+v instead of ctrl+shift+v . 

If there is possibility , what files I need to change?

I am using CKEditor5-28.0.0

Thanks in Advance

**Comment by Witoso** [comment]
DUP of https://github.com/ckeditor/ckeditor5/issues/14303. Please don't create duplicated issues. Sometimes it will take time to get our response. If you would like to have a direct support channel, please [contact us](https://ckeditor.com/contact/).
