### ISSUE TITLE
Pinned Watchdog version leads to problems when updating

### ISSUE THREAD

**Issue by Witoso** [ckeditor/ckeditor5-angular#376]
In the published package on the npm, we pin a specific version of Watchdog which leads to problems when someone is using a different version of the editor or wants to update.

`package.json` on npm:
![image](https://github.com/ckeditor/ckeditor5-angular/assets/9881379/4624c36a-3401-4f04-9d6a-fae5f1be6d07)

React on the other hand specifies Watchdog as a peer dependency:
![image](https://github.com/ckeditor/ckeditor5-angular/assets/9881379/559c0aab-d3a7-44f2-a159-87c90ec9cca9).

Not sure what's the best approach to solve this but it's a major issue for some integrators.

**Comment by Reinmar** [comment]
We also planned to expose Watchdog on the Editor class to completely avoid this additional dependency. 

Some internal notes where we discussed this:

*   **Update (13.04.2023)**:
    *   😂 And the above didn’t work: ckeditor/ckeditor5#13852
    *   Two options for now:
        *   Add ckeditor5-watchdog to the “Framework” layer and make the base `Editor` expose these
            *   Simpler option
            *   Risk: circular dependency on types between the editor and watchdog interfaces
            *   This time let’s also update the integrations to verify that it all works together
        *   Merge the code from ckeditor5-watchdog to ckeditor5-core, but keep ckeditor5-watchdog as a **re-export** for backwards compat
            *   It would make core the dep of watchdog pkg (it has no deps now)

**Comment by pomek** [comment]
### Scope

* We agreed to define core, engine, utils, and watchdog packages as peer dependencies.
	* They all are needed when an integrator installs the `<CKEditor>` component and tries to build a custom app.
	* Example: `tsc` needs to resolve `import type { GetEventInfo } from '@ckeditor/ckeditor5-utils';`, so the utils package must be installed too.
	* We require at least version 37 or higher (`>=37.0.0`). 37 is the first number that offers typings.
* It's a breaking change.
* Update [the Angular guide](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html). We should mention that peer dependencies should be installed in the same version like the editor build that integrator wants to use.
