### ISSUE TITLE
Type '(elementOrData: HTMLElement | string | Record<string, string>, config: EditorConfig) => Promise<TEditor>' is not assignable to type 'EditorCreatorFunction'.

### ISSUE THREAD

**Issue by billpeace** [ckeditor/ckeditor5-angular#381]
update  @angular  16.2.1  @ckeditor 39.0.1

Error: src/ckeditor/ckeditor.component.ts:391:5 - error TS2322: Type '(elementOrData: HTMLElement | string | Record<string, string>, config: EditorConfig) => Promise<TEditor>' is not assignable to type 'EditorCreatorFunction'.
  Types of parameters 'elementOrData' and 'elementOrData' are incompatible.
    Type 'string | HTMLElement | Record<string, string> | Record<string, HTMLElement>' is not assignable to type 'string | HTMLElement | Record<string, string>'.
      Type 'Record<string, HTMLElement>' is not assignable to type 'string | HTMLElement | Record<string, string>'.
        Type 'Record<string, HTMLElement>' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 283 more.

**Comment by Witoso** [comment]
I see that you opened multiple issues today in more than one repo. Please, let's keep them joined so that we can keep the context of your application and use case. Let's move this to https://github.com/ckeditor/ckeditor5-angular/issues/382
