### ISSUE TITLE
Avoid warning messages for Angular versions <6.0.0

### ISSUE THREAD

**Issue by maximelafarie** [ckeditor/ckeditor5-angular#39]
I installed ckeditor5-angular on my project running with Angular `5.2.11`.

When I serve it, it echoes the following warning messages:
```shell
warning " > @ckeditor/ckeditor5-angular@1.0.0-beta.1" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > @ckeditor/ckeditor5-angular@1.0.0-beta.1" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > @ckeditor/ckeditor5-angular@1.0.0-beta.1" has incorrect peer dependency "@angular/forms@^6.0.0".
```
I saw that in the library's `package.json` there is:

```json
...
  "peerDependencies": {
    "@angular/core": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/forms": "^6.0.0"
  },
...
```
So this is responsible of the warning messages. Replacing it with:
```json
...
  "peerDependencies": {
    "@angular/core": ">=5.2.0",
    "@angular/common": ">=5.2.0",
    "@angular/forms": ">=5.2.0"
  },
...
```
will resolve this issue (tilde or caret won't match for both v5 and v6 Angular versions).

Maybe in the future you would like to create different tags to manage required versions of Angular. E.g: a v1 tag for Angular <6.0.0 and a v2 for Angular >= 6.0.0 ?

Actually the library works well as-is, but it would be nice to avoid theses warning messages. 😉 

Cheers!

**Comment by ma2ciek** [comment]
Hi!

Great to hear that the `ckeditor5-angular` works well for lower versions of Angular. I'll make a PR to downgrade these requirements.

I don't remember why I made it exactly `^6.0.0`... Good catch.

**Comment by maximelafarie** [comment]
Hi! 

Yes, it works perfectly but I didn't try it with lower Angular versions. Anyway, with Angular 5.x.x it works like a charm and it actually saved me a lot of time! Thank you for this awesome lib! 😍

Thank you for your reactivity! 💪 🤘

**Comment by ma2ciek** [comment]
Thanks for the positive feedback! It's always good to hear it. It's the motivation that keeps me going :)

**Comment by ma2ciek** [comment]
For the Angular 4.x.x the build process throws the following error:

```
ERROR in Error:
Metadata version mismatch for module node_modules/@ckeditor/ckeditor5-angular/ckeditor-ckeditor5-angular.d.ts,
found version 4, expected 3, resolving symbol AppModule in src/app/app.module.ts,
resolving symbol AppModule in src/app/app.module.ts
```

I've been able to run it on the 5.0.0 so for the current code the 5.x.x version should be minimal. And I've seen that [angular@7 will be released soon](https://github.com/angular/angular/releases) with changes that should be transparent for the `ckeditor5-angular` so I'd go with the `>=5.0.0` range.
