### ISSUE TITLE
Upgraded to version 40.0 of all components and custom build will not show in Angular 15 now

### ISSUE THREAD

**Issue by tlawapsc** [ckeditor/ckeditor5-angular#393]
I created a new custom build using the Online Build editor, I deleted all ckeditor references from node_modules and followed the online instructions to install the custom build again. The compiler throws no errors and there are no errors in the console, but the spot where the ckeditor should render just has an empty <div></div> tag inside the <ckeditor> tags. 

I am importing the editor in my component using the following:
**import Editor from 'ckeditor5-custom-build/build/ckeditor';
...
public Editor = Editor;**

If I change this to use the ClassicEditor it renders fine in the UI:
**import ClassicEditor from '@ckeditor/ckeditor5-build-classic';**

**package.json**
    "@ckeditor/ckeditor5-angular": "^7.0.1",
    "@ckeditor/ckeditor5-build-classic": "40.0.0",
    "@ckeditor/ckeditor5-core": "^40.0.0",
    "@ckeditor/ckeditor5-engine": "^40.0.0",
    "@ckeditor/ckeditor5-utils": "^40.0.0",
    "@ckeditor/ckeditor5-watchdog": "^40.0.0",
    "ckeditor5-custom-build": "file:ckeditor5",

Is there a bug in version 40.0 that is making ckeditor not show?

**Comment by Witoso** [comment]
There's no known issue that v40 custom build is not working. Did you follow [the steps from the tutorial](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html#integrating-a-build-from-the-online-builder)?

**Comment by tlawapsc** [comment]
Yes I followed the steps and it was working prior. I found the issue. If Watchdog is included in the build it exports a "_default" object that has 2 properties of Editor and Watchdog.
```
declare const _default: {
    Editor: typeof Editor;
    EditorWatchdog: typeof EditorWatchdog;
};
export default _default;
```

 So on your component when you initialize the editor you have to use:
` public Editor = Editor.Editor;`

**Comment by Witoso** [comment]
Thanks, we will update the docs.
