### ISSUE TITLE
Create editor from source code

### ISSUE THREAD

**Issue by Haribabujanjala** [ckeditor/ckeditor5-angular#4]
Hi Oleq,
Help me out,

1) i try to installing plugin "your editor from source code"
2) editor.setData( this.data ) -- data was not setting to the editor
3)editor.model.document.on( 'change', evt => {}); -- this event was not firing

**Comment by jodator** [comment]
Hi @Haribabujanjala what did you exactly to bring the editor? Did you follow "[Creating custom builds](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html)" guide or the "[Installation](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/installation.html)" guide?

Without any configuration or setup description it's hard to tell what's going on.

**Comment by Haribabujanjala** [comment]
**ckeditor5-angular** referred this branch **https://github.com/ckeditor/ckeditor5-angular/tree/t/1** 

------------------------------------------------------------------------------------------------

**configuration or setup description**

-----ckeditor5-angular/src/app/simple-usage/simple-usage.component.ts ----

import { Component, OnInit } from '@angular/core';

//import * as ClassicEditorBuild from '@ckeditor/ckeditor5-build-classic'
**import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';**
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';

@Component( {
	selector: 'app-simple-usage',
	templateUrl: './simple-usage.component.html',
	styleUrls: [ './simple-usage.component.css' ]
} )
export class SimpleUsageComponent implements OnInit {

	public ClassicEditor = ClassicEditor;

	public isDisabled = false;
	public editorData = '<p>Welcome to ckEditor 5.... Awesome </p>';
    public configData;
	constructor() {

		//editor configarations
		**this.configData = {
		    plugins: [
				Bold	
			],
			toolbar: [				
				 'bold'
				 ]
		}**
	 }

	ngOnInit() {
	}

	toggleDisableEditors() {
		this.isDisabled = !this.isDisabled
	}

	onFocus( evt: any ): void {
		console.log( 'Focused the editing view', evt );
	}

	onBlur( evt: any ): void {
		console.log( 'Blurred the editing view', evt );
	}

	change( evt: any ): void {
		console.log( 'Editor model changed', evt );
	}

	ready( evt: any ): void {
		console.log( 'The editor is ready', evt );
	}
}
------------------------------------------------------------------------------------
these are the statements made changes in above 

<< import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor'; >>

<< this.configData = {
		    plugins: [
				Bold	
			],
			toolbar: [				
				 'bold'
				 ]
		} >>

---------------------------------------------------------------------------------------------------------------

Through error in browser console like this <<TypeError: Cannot read property 'getAttribute' of null >>
see below screen-shot 

![screenshot from 2018-05-31 19 22 41](https://user-images.githubusercontent.com/37529136/40788236-20aecbb4-64df-11e8-9b99-6646e6b38cd1.png)

**Comment by Haribabujanjala** [comment]
Hi @jodator 

This time i made change in **nodemodules inside bold plugin** directly like this see below code

/nodemodule/@ckeditor/ckeditor5-basic-styles/src/boldui.js

`view.set( {
				label: t( 'Bold' ),
				icon: boldIcon,
				keystroke: 'CTRL+B',
				tooltip: true
			} );`

boldIcon replaced with svg content like this

	view.set( {
					label: t( 'Bold' ),
					icon: '<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"><path d="M10.187 17H5.773c-.637 0-1.092-.138-1.364-.415-.273-.277-.409-.718-.409-1.323V4.738c0-.617.14-1.062.419-1.332.279-.27.73-.406 1.354-.406h4.68c.69 0 1.288.041 1.793.124.506.083.96.242 1.36.478.341.197.644.447.906.75a3.262 3.262 0 0 1 .808 2.162c0 1.401-.722 2.426-2.167 3.075C15.05 10.175 16 11.315 16 13.01a3.756 3.756 0 0 1-2.296 3.504 6.1 6.1 0 0 1-1.517.377c-.571.073-1.238.11-2 .11zm-.217-6.217H7v4.087h3.069c1.977 0 2.965-.69 2.965-2.072 0-.707-.256-1.22-.768-1.537-.512-.319-1.277-.478-2.296-.478zM7 5.13v3.619h2.606c.729 0 1.292-.067 1.69-.2a1.6 1.6 0 0 0 .91-.765c.165-.267.247-.566.247-.897 0-.707-.26-1.176-.778-1.409-.519-.232-1.31-.348-2.375-.348H7z" fill="#000" fill-rule="evenodd"/></svg>',
                                        keystroke: 'CTRL+B',
					tooltip: true
				} );

this time didn't get this error in in console  <<TypeError: Cannot read property 'getAttribute' of null  >> but editor was responding.

![screenshot from 2018-05-31 20 32 28](https://user-images.githubusercontent.com/37529136/40790152-af955722-64e3-11e8-802f-adf4777759ba.png)

See above the screen 

Editor was not showing setting data, and also enter data it was not changing model...

**Comment by Reinmar** [comment]
I'm sorry, @Haribabujanjala, but I'm not able to understand what you're doing and what you're asking about. Please work on formatting your question (so it displays correctly), defining what you did and what happened in a clear and **reproducible** way.

Please also note that what you can find on https://github.com/ckeditor/ckeditor5-angular/tree/t/1 is not a ready-for-production component yet. It's just a first implementation from which we're going to continue improving until it's ready. You might've experienced issues caused by bugs in that component, but we need a more thorough feedback to be able to understand that. Actually, I'm not even sure you used our component.

**Comment by ma2ciek** [comment]
> It doesn't work because plugins are not working when using the Angular CLI. The CLI uses the url-loader instead of the raw-loader for SVG files.

You can actually try to use `ng eject` and replace loader in the config. But for now, it's a solution only for the angular@5, see the [issue](https://github.com/angular/angular-cli/issues/10618). I'll see later if it's possible without ejecting.

**Comment by Reinmar** [comment]
This means that using the [official](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/overview.html) or [custom](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html) CKEditor 5 builds is the easiest way for now.

However, I think that people commented that the new Angular CLI was supposed to be more flexible when it comes to webpack configuration. I keep my 🤞 for that.

**Comment by ma2ciek** [comment]
I've checked and both, CKEditor5 CSSs and SVGs` are broken now when a CKEditor5 editor is built from source in the angular environment. Also, there's no error visible in the console and you can't type, so maybe those are not the only broken things.

**Comment by ma2ciek** [comment]
There're some tools listed in the https://github.com/angular/angular-cli/issues/10618 (https://github.com/meltedspark/angular-cli-builders and https://github.com/Angular-RU/angular-cli-webpack). The first one looks promising as we can prepend our loaders to the config.

**Comment by ma2ciek** [comment]
DUP of #26.

**Comment by thuctd** [comment]
I use:  `<ckeditor [editor]="Editor" #myEditor (ready)="onReady($event)" (change)="saveArticle()" data="{{htmlContent}}"></ckeditor>`
