### ISSUE TITLE
Placeholder option

### ISSUE THREAD

**Issue by maximelafarie** [ckeditor/ckeditor5-angular#40]
It could be really cool to create an option in order to pass a placeholder to the editor.

Example use case:
```html
<ckeditor [editor]="Editor"
          [config]="CKEConfig"
          placeholder="Write your message"></ckeditor>
```

Let me know if you want me to make a PR, it would be a pleasure!

Cheers! 🖖

**Comment by ma2ciek** [comment]
I wouldn't implement it here to do not duplicate this feature, but we can track this issue here too to make sure it's in progress.

**Comment by ma2ciek** [comment]
This feature works with the latest CKEditor5 builds (available on GH only). These builds should be available on NPM in two/three weeks. The placeholder can be set via the [editor's config]( https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-placeholder):

```html
<ckeditor [editor]="Editor"
          [config]="config"></ckeditor>
```

```ts
class Component {
	public Editor = ClassicEditorBuild;
	public config = {
		placeholder: 'Your placeholder'
	};
}
```

I'll close this issue after updating docs.

**Comment by ma2ciek** [comment]
The release is out so this feature should work with the latest NPM builds 🎉
