### ISSUE TITLE
ckeditor updateEditorData() issue 

### ISSUE THREAD

**Issue by waleedmughal42** [ckeditor/ckeditor5-angular#403]
using ckeditor5 custom build in an angular project. getting this error on updating the editorData: 
`this.editorComponent.editorInstance.plugins.get('SourceEditing').updateEditorData();`
Property 'updateEditorData' does not exist on type 'PluginInterface'.ts(2339)

**Comment by Witoso** [comment]
It looks like somehow the TypeScript augmentation didn't work. Try to:

1.  Add **`import type { SourceEditing } from '@ckeditor/ckeditor5-source-editing';`**. If that's not sufficient, then
2.  Look for the issue in this custom build as to why augmentation is not working. If unable to find the issue, then
3.  Perform casting, i.e., **`this.editorComponent.editorInstance.plugins.get('SourceEditing') as SourceEditing`**.
