### ISSUE TITLE
Lists lose their inline style when they are indented.

### ISSUE THREAD

**Issue by juliancalderone** [ckeditor/ckeditor5-angular#406]
About the error: 
I have tried several tests, it appears when the user tries to index lists of different types within ckeditor. 

https://github.com/ckeditor/ckeditor5-angular/assets/22227757/bcc5a2b3-6222-4c68-aeae-b8fa2b58fd0a

As you can see in the video, when the first list type is selected, the inline style tag "list-style-type:upper-latin;" is added, but when the user indents with the tab key, the editor changes the list type without adding the inline style. 

I'm implementing the custom version of the library

Files: 

[Custom configuration](https://gist.github.com/juliancalderone/ed5c821fa093c1a7dee7e022a3a63742)
 
[This is my package.json file](https://gist.github.com/juliancalderone/a81b3c1e110f2e1169ba42b07c5a3d2d#file-package-json)

I´m using Angular 16.2.12

Thank you very much in advance, in the event that this is not a bug at all.

**Comment by Witoso** [comment]
Hey! This is a default behavior, we style one level of the lists, the others come from default stylesheets. Related improvement could be ckeditor/ckeditor5#10862, and other related to defining custom lists.

**Comment by juliancalderone** [comment]
Hi @Witoso Thanks for your answer !
