### ISSUE TITLE
CI is red

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-angular#42]
https://travis-ci.org/ckeditor/ckeditor5-angular/builds/434130390

Did I break something? It doesn't sound like caused by my changes.

**Comment by ma2ciek** [comment]
It looks like there's some problem with typings. Maybe because of some dependency update they are duplicated now. I'll check it.

**Comment by ma2ciek** [comment]
And I'm sorry to say, but your changes need to be passed to that file: https://github.com/ckeditor/ckeditor5-angular/blob/master/src/ckeditor/package.json, as this is the `package.json` that will be published on the NPM. I could add a comment under some `//` property in the root package.json, that this one won't be published.

**Comment by Reinmar** [comment]
I wanted to ask you about that, but forgot it because I found that broken CI build :D I'll move those props.
