### ISSUE TITLE
Unexpected behavior in the Restricted Editing plugin when using two–way data binding with `ngModel`

### ISSUE THREAD

**Issue by mabryl** [ckeditor/ckeditor5-angular#425]
## 📝 Provide detailed reproduction steps (if any)

1. Open the demo Stackblitz provided by one of our customers: https://stackblitz.com/edit/stackblitz-starters-4vbrqb?file=src%2Fmain.ts
2. Notice the unexpected behavior in the editor with `ngModel`

### ✔️ Expected result

The restricted editing exception should behave like it does in the first demo editor.

### ❌ Actual result

When using `ngModel`, an additional editable field is created, which cannot be removed.

## 📃 Other details

* Browser: cross-browser
* OS: cross-OS
* First affected CKEditor version: N/A
* Installed CKEditor plugins: RestrictedEditing

**Comment by Witoso** [comment]
After the investigation, we think this is connected with the behavior of the editor itself, not Angular integration. The main issue will be https://github.com/ckeditor/ckeditor5/issues/16721.

**Comment by Witoso** [comment]
Resolved by https://github.com/ckeditor/ckeditor5/pull/17367.
