### ISSUE TITLE
Localization does not work as shown in the documentation

### ISSUE THREAD

**Issue by Saiuke** [ckeditor/ckeditor5-angular#433]
I am experiencing issues with implementing internationalization in the editor for our Angular application. We are following the steps outlined here: https://ckeditor.com/docs/ckeditor5/latest/getting-started/installation/angular.html#localization.

Specifically, we have an issue with the following line:

`import coreTranslations from 'ckeditor5/translations/sv.js;`

It appears that no `coreTranslations` entity is being exported from that file.
What would be the correct way of implementing internationalization for the UI of the editor?

Stack info:

- CKE installed via NPM, standard package, no plugins
- Angular application 17
- Node JS 18.19.1
- @ckeditor/ckeditor5-angular: ^8.0.0
- ckeditor5: ^42.0.2

**Comment by Saiuke** [comment]
I have found a workaround for this issue:

And the translations can be imported like this:
`import sv from 'node_modules/ckeditor5/dist/translations/sv'`

I also had a similar problem trying to import the main CSS file, I was able to import it like this:
`@import "node_modules/ckeditor5/dist/ckeditor5.css";`

**Comment by Mati365** [comment]
@Saiuke It looks like it's similar to this issue: https://github.com/ckeditor/ckeditor5-angular/issues/432#issuecomment-2255760804

**Comment by Witoso** [comment]
@Saiuke could you pass your tsconfig? Could you check if switching to  to `"moduleResolution": "node16"` or `"moduleResolution": "nodenext"` helps?. These modes have better support for the `exports` field and are designed to work with the latest features of Node.js, including wildcard exports.

package.json is defined as follows:

```
"exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/ckeditor5.js"
    },
    "./*": "./dist/*",
    "./browser/*": null,
    "./build/*": "./build/*",
    "./src/*": "./src/*",
    "./package.json": "./package.json"
  },
```

**Comment by Witoso** [comment]
Let's keep the discussion in one issue in the main repo.
