### ISSUE TITLE
event before image is uploaded

### ISSUE THREAD

**Issue by ayeshabhattids** [ckeditor/ckeditor5-angular#446]
I went through the documentation but could not find how to receive an event before the image is sent to server. 

I am using, https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html

The following is working 

   editor.plugins.get( 'FileRepository' ).on( 'change:uploaded', evt => {
            console.log( 'Image uploaded!' );
            console.log( evt );
                // do something here
        } );

I would like something on ImageInsert plugin may be changed:selected kindof. 

Thanks in advance.

**Comment by Witoso** [comment]
Hi! I'm not sure what's your use case. You can always listen to the command:

```javascript
editor.commands.get('uploadImage').on('execute', (evt, files) => { ... });
```

**Comment by ayeshabhattids** [comment]
Worked!
