### ISSUE TITLE
Error: Cannot find module 'ckeditor5-premium-features' after upgrading to @ckeditor/ckeditor5-angular@9.0.0

### ISSUE THREAD

**Issue by studentrk** [ckeditor/ckeditor5-angular#447]
When upgrading from version 8.0.0 to version 9.0.0 of @ckeditor/ckeditor5-angular, I encounter the following error during the build process when executing ionic build:
```

✘ [ERROR] TS2307: Cannot find module 'ckeditor5-premium-features' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-integrations-common/dist/cdn/ck/globals.d.ts:6:46:
      6 │ ...ype * as CKEditorPremiumFeatures from 'ckeditor5-premium-features';
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'ckeditor5-premium-features' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ckeditor/ckeditor5-integrations-common/dist/globals.d.ts:11:20:
      11 │   export type * from 'ckeditor5-premium-features';
```

**To Reproduce**
1. Upgrade @ckeditor/ckeditor5-angular from 8.0.0 to 9.0.0.
2. Run the command ionic build.

**Expected behavior**
The project should build without errors related to ckeditor5-premium-features.

**Environment**
Angular version: 18.2.5
@ckeditor/ckeditor5-angular: 9.0.0
Ionic CLI : 7.2.0
NodeJS : v20.17.0

**Additional context**
I do not use ckeditor5-premium-features in my application, and I believe this issue may have been introduced in the latest version upgrade.

**Workaround**
Currently I just have downgraded to version 8.0.0 again, so that the build works.

**Comment by Mati365** [comment]
Hi! Consider adding `skipLibCheck: true` to your `tsconfig.json` file.

**Comment by Mati365** [comment]
@studentrk Fix has been released in our dependencies. `ckeditor5-premium-features` is now optional.
