### ISSUE TITLE
How to Play the video embed in ckeditor document

### ISSUE THREAD

**Issue by yogeshbansal** [ckeditor/ckeditor5-angular#52]
Hi, 
I am using CKEditor 5 ( angular 2+). I added a video in my document and save the document content in the database. Now, I want to view and play that video on another page. the content saved into the database looked like this:
"<figure class="media"><oembed url="https://www.youtube.com/watch?v=Xco-TEI-HU4"></oembed></figure>"

**Comment by pomek** [comment]
DUP of https://github.com/ckeditor/ckeditor5-media-embed/issues/21.
