### ISSUE TITLE
Use CKEditor in an Angular Library

### ISSUE THREAD

**Issue by yowari** [ckeditor/ckeditor5-angular#54]
Hi!
I'm trying to use CKEditor in my Angular library. In the description, it says that I should install dependencies and save them as `DevDependency` https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#quick-start . The problem is in my project that uses my library, the CKEditor libraries are not recongnized.
```
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-angular'
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic'
```
I saw that `package.json` in `@ckeditor/ckeditor5-build-classic` uses DevDependencies. Do I have to build from source as described in the [doc](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source) or are there other solutions?

**Comment by ma2ciek** [comment]
Hi, @yowari!

Did you install them from the NPM? It looks like they don't exist in the `node_modules`.

**Comment by ma2ciek** [comment]
And did you follow this guide and run these two commands:

* `npm install --save-dev @ckeditor/ckeditor5-angular`
* `npm install --save-dev @ckeditor/ckeditor5-build-classic`

**Comment by yowari** [comment]
Yes, I followed the Docs and installed with `npm install --save-dev` on my library. I got in `package.json`:
```javascript
"devDependencies": {
    "@ckeditor/ckeditor5-angular": "^1.0.0",
    "@ckeditor/ckeditor5-build-classic": "^11.1.1",
    ...
}
```

**Comment by ma2ciek** [comment]
Are you sure that you also have them inside your project's `node_modules` (`node_modules/@ckeditor/ckeditor5-angular` and `node_modules/@ckeditor/build-classic`)?

**Comment by yowari** [comment]
Yes
![image](https://user-images.githubusercontent.com/16974468/47802166-02cda380-dd30-11e8-9943-a542283aa958.png)

**Comment by ma2ciek** [comment]
Could you tell me more details? What Angular version do you use, what tsconfig do you have in your app? Do you have a special webpack configuration?

**Comment by ma2ciek** [comment]
> Yes, I followed the Docs and installed with npm install --save-dev on my library. I got in package.json:

That should be done with the `--save` and it's actually a bug in our docs. But that shouldn't have an impact on your error.

**Comment by yowari** [comment]
Sure. Basically what I'm trying to do is to create a rich-text component that wraps the ckeditor component and export my rich-text component in my library. The problem occurs when I launch webpack-dev-server on the project that depends on my library.
I use Angular 6.0.7

**Comment by ma2ciek** [comment]
Thanks.

Could you recheck it with the `--save` option? If that's a dependency of a dependency, then it does make sense to install it as a dependency of an app.

**Comment by yowari** [comment]
My Bad 😮 
Seems that the dependency is not installed because I use `npm link` in my project. So the solution is to install the depedencies on the project (without save).
Anyway, thanks for the support you can close ;)

**Comment by ma2ciek** [comment]
If you have an architecture like this:

project A
	- project B

project B
	- CKEditor 5

Then if you have linked project B, you shouldn't have to install CKEditor 5 in the CKEditor A too. Unless I don't understand something.

There's also a `preventSymlinks` option available in the angular.json config, maybe that can be also taken into consideration.

```json
"architect": {
	"build": {
		"options": {
			"preserveSymlinks": true
		}
	}
}
```

**Comment by yowari** [comment]
Yes, that the kind of architecture that I use. Well, dependencies were installed on project B but all dependencies of project B should also be installed on project A. When I install dependencies of project A, the links disapear, and it installs the one on the repo packages without CKEditor dependency

**Comment by ma2ciek** [comment]
>  Well, dependencies were installed on project B but all dependencies of project B should also be installed on project A

This shouldn't work like that.

And did you tried to install the `ckeditor5-angular` with `npm install --save`? When you create a link via `npm link`, the NPM installs all deps in the linked repository, so later you shouldn't need to install anything more than just linking the package.

**Comment by ma2ciek** [comment]
Since I guess it's a problem with NPM linking, I'm closing this issue.
