### ISSUE TITLE
Publish the package in the npm

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-angular#7]
Similar to the React [issue](https://github.com/ckeditor/ckeditor5-react/issues/5), we need to:

* [x] make sure the README makes sense and corresponds to the code,
* [ ] clearly state in the README that this is a dev preview,
* [ ] create a basic guide in [docs.ckeditor.com](https://docs.ckeditor.com/ckeditor5/latest/builds/index.html); a few words + redirect to the GitHub repo would do the trick. I think maintaining a proper guide before the stabilization is a chore, let's wait for the feedback from the community first,
* [ ] update [FAQ in docs.ckeditor.com](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/faq.html#how-to-use-ckeditor-5-with-frameworks-angular-react-etc),
* [x] a few [tests](https://github.com/ckeditor/ckeditor5-angular/issues/8) would be great,
* [x] some [basic CI](https://github.com/ckeditor/ckeditor5-angular/issues/3) would also help
* [x] add npm script that generates the changelog
* [x] make sure that `npm run publish` will do what we want. And check if we need to use [ckeditor5-dev-env/lib/release-tools/utils/releaserepository.js](https://github.com/ckeditor/ckeditor5-dev/blob/0acc91d27829a88de541519d950284ec870e5321/packages/ckeditor5-dev-env/lib/release-tools/utils/releaserepository.js) after building, like [here](https://github.com/ckeditor/ckeditor5-react/pull/14/files/17ef4105ba36323aa860b8736ea8b40d085b49e2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R27)
* [x] make sure that the `package.json` created for the `NPM` release will contain only peer angular@6 dependencies

cc @ma2ciek @Reinmar

**Comment by ma2ciek** [comment]
Two things to add:

* add npm script that generates the changelog
* make sure that `npm run publish` will do what we want. And check if we need to use [ckeditor5-dev-env/lib/release-tools/utils/releaserepository.js](https://github.com/ckeditor/ckeditor5-dev/blob/0acc91d27829a88de541519d950284ec870e5321/packages/ckeditor5-dev-env/lib/release-tools/utils/releaserepository.js) after building, like [here](https://github.com/ckeditor/ckeditor5-react/pull/14/files/17ef4105ba36323aa860b8736ea8b40d085b49e2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R27)

**Comment by ma2ciek** [comment]
We should also make sure that the `package.json` created for the `NPM` release will contain only peer dependencies to angular@6 repositories, nothing more.

**Comment by nfdevil** [comment]
It is not published to NPM yet? https://www.npmjs.com/package/@ckeditor/ckeditor5-angular gives a 404

**Comment by ma2ciek** [comment]
Hi @nfdevil, the package should be published today.

**Comment by ma2ciek** [comment]
Update: The `ckeditor5-angular` package has been just published - https://www.npmjs.com/package/@ckeditor/ckeditor5-angular 🎉
