### ISSUE TITLE
Inline style for Highlighting feature

### ISSUE THREAD

**Issue by gaurav2887** [ckeditor/ckeditor5-angular#73]
I am using ckeditor for editing the existing HTML templates and sending it in emails. Ckeditor uses `class=mark-red` to highlight the text. Is there anyway we can convert it into inline styles for email clients to understand?. I see ckeditor also does not like lot of inline styles coming from html templates.

I need to know if there is any way in CkEditor to convert css classes to inline styles.

**Comment by Mgsy** [comment]
Hello, @gaurav2887, I saw you tried to use the solution provided in [this ticket](https://github.com/ckeditor/ckeditor5-highlight/issues/35). Could you share more details about the errors you experience? Also, your full CKEditor 5 config code will be appreciated.

**Comment by ma2ciek** [comment]
Is this a `ckeditor5-angular` issue? I guess we can port it to the main issue tracker.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
