### ISSUE TITLE
Using Classic Build, it doesn't apply styles in toolbar

### ISSUE THREAD

**Issue by futbolsalas15** [ckeditor/ckeditor5-angular#77]
When I use the Classic Build (using the basic example at https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html), it seems that doesn't apply the styles in the toolbar:

![error-ckeditor5](https://user-images.githubusercontent.com/1960482/53643564-64305100-3c02-11e9-876c-4a5df6a9e9a9.png)

What is different from the example is that from the main module (app.module.ts) I'm creating a web component for each of the components of the project:

```typescript
const element = createCustomElement(TestComponent, { injector: this._injector });
customElements.define('test-component', element);
```

Doesn't ckeditor5-angular have compatibility (specially the CSS) when is used in web components?

Thanks!

**Comment by Mgsy** [comment]
Hello, @futbolsalas15, could you give us more details about your environment? The content of your `package.json` and code of your component will be appreciated.

**Comment by futbolsalas15** [comment]
Hello @Mgsy, thanks for your prompt response!
I attached my _package.json_:

[package.zip](https://github.com/ckeditor/ckeditor5-angular/files/2919831/package.zip)

The main module (_app.module.ts_) has the following code:

```typescript
const BOOTSTRAP = environment.production ? [] : [AppComponent];

@NgModule({
  bootstrap: BOOTSTRAP,
  declarations: [AppComponent],
  imports: [BrowserModule, RichTextEditorModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule implements DoBootstrap {
  constructor(private readonly _injector: Injector) {
    this._registerWidgets();
  }

  public ngDoBootstrap(): void {}

  private _registerWidgets(): void {
    // here is where we register the angular componentes as web components, using createCustomElement method of Angular
    const element = createCustomElement(RichTextEditorComponent, { injector: this._injector });
    customElements.define('rich-text-editor', element);
  }
}
```

The component _RichTextEditorComonent_ has the following code:

```typescript
import { Component, Input, OnInit, ViewEncapsulation, Output, EventEmitter } from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';

@Component({
  templateUrl: './rich-text-editor.component.html',
  styleUrls: ['./rich-text-editor.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class RichTextEditorComponent implements OnInit {
  @Input()
  public content: string;
  public editor = ClassicEditor;

  @Output()
  public contentChanged = new EventEmitter<string>();

  constructor() {}

  public ngOnInit(): void {
    this.content = 'Hello World!';
  }
}
```

The template:

```html
<ckeditor
  [editor]="editor"
  [data]="content"
  [config]="{ toolbar: ['heading', '|', 'bold', 'italic'] }"
></ckeditor>
```

And in _app.component.html_, I use the previous component with the following code:

```html
<rich-text-editor content="test"></rich-text-editor>
```

I don't know if it is enough. Thanks!.

**Comment by futbolsalas15** [comment]
I'm sorry, I missed the _module_ config where I called _CKEditorModule_:

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';

import { RichTextEditorComponent } from './containers/rich-text-editor.component';

  declarations: [RichTextEditorComponent],
  imports: [CommonModule, CKEditorModule],
  entryComponents: [RichTextEditorComponent]
})
export class RichTextEditorModule {}
```

Thanks!.

**Comment by futbolsalas15** [comment]
Hi @ma2ciek 

When I included the CKEditorModule, the result is the same:

![error-ckeditor](https://user-images.githubusercontent.com/1960482/53646380-0c491880-3c09-11e9-91e2-59cbfc76a4a1.gif)

Sorry and thanks!

**Comment by ma2ciek** [comment]
Ok, so I did not understand you previously 😄

I'll check it. Looks like somehow the CKEditor 5 styles are not applied.

**Comment by futbolsalas15** [comment]
Hi @ma2ciek ,

I think I found the problem! Is the following line that I added as option to the `@Component` definition:

```typescript
encapsulation: ViewEncapsulation.ShadowDom
```
I changed it to `encapsulation: ViewEncapsulation.Emaulated` and it works as expected. Reading the error is because _ckeditor5_ doesn't support Shadow DOM.

Thanks again for your help!

**Comment by ma2ciek** [comment]
Kudos for you for solving that issue. It's always good to know what can be a potential problem in the integration. 👍

The Shadow DOM is on our TODO list already: https://github.com/ckeditor/ckeditor5/issues/1483.

**Comment by saravana-sk** [comment]
@ma2ciek   @Reinmar 
I am seeing this issue is closed, but I am still facing the same issue. May I know whether the **ShadowDOM** feature is implemented in CK Editor5 ??

**Comment by Witoso** [comment]
It's not, here's a related ticket: https://github.com/ckeditor/ckeditor5/issues/3891, and a comment that[ it's also blocked on the browsers' side](https://github.com/ckeditor/ckeditor5/issues/3891#issuecomment-1659181917).
