### ISSUE TITLE
How to integrate Markdown plugin with Angular?

### ISSUE THREAD

**Issue by CalvinDale** [ckeditor/ckeditor5-angular#79]
This question is similar to [#6](https://github.com/ckeditor/ckeditor5-angular/issues/6). The difference is the [Markdown plugin](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html) requires instantiation of a `GFMDataProcessor` instance.

I'm not sure how to wire this up. I have tried a couple of ideas (shown below) and neither is working.

```javascript
import GFMDataProcessor from '@ckeditor/ckeditor5-markdown-gfm/src/gfmdataprocessor';

export default class ClassicEditor extends ClassicEditorBase { 
    constructor() { 
        super();
        this.data.processor = new GFMDataProcessor();
    }
}

// function Markdown(editor) { editor.data.processor = new GFMDataProcessor(); }

ClassicEditor.builtinPlugins = [
    Essentials,
...
    List,
    // Markdown,
    MediaEmbed,
];
```

**Comment by ma2ciek** [comment]
Hi @CalvinDale!

There's a problem with the above code because the `ClassicEditor` takes source element and editor config as paramteres. Did you try something like this:

```js
export default class ClassicEditor extends ClassicEditorBase { 
    constructor( ...args ) { 
        super( ...args );
        this.data.processor = new GFMDataProcessor();
    }
}
```

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.

**Comment by CalvinDale** [comment]
Hello @ma2ciek Sorry I dropped the ball here; I haven't been coding lately. I will try however out the approach you outlined when I eventually return to the project.
