### ISSUE TITLE
Dynamic content into ckeditor

### ISSUE THREAD

**Issue by Goutam192002** [ckeditor/ckeditor5-angular#81]
I was trying to add dynamic content to the editor.

This is my code
HTML:
`<ckeditor [editor]="Editor" [data]="content"></ckeditor>`

the content property is decorated by an @Input(), The value of content changes but the same is not reflected in the editor.

If you need more details regarding the issue...please comment below and I will be happy to share my code.

**Comment by ma2ciek** [comment]
Hi @Goutam192002!

I'd be happy if you could paste your component with its template. Or some additional details that are required to reproduce the issue.

**Comment by Goutam192002** [comment]
Editor component:
`import {Component, Input, OnInit} from '@angular/core';
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';

@Component({
  selector: 'app-editor',
  template: '<div class="container mt-5">
  <label>Title</label>
  <input type="text" name="Title" class="form-control" placeholder="Enter your title" id="title" [value]="title">
  <br>
  <ckeditor [editor]="Editor" [data]="content"></ckeditor>
  <br>
  <button type="button" name="Submit" class="btn btn-primary">Submit</button>
</div>',
  styleUrls: ['./editor.component.css']
})
export classEditorComponent implements OnInit {
  @Input() title = '';
  @Input() content = '';
  public Editor = ClassicEditor;
  constructor() { }

  ngOnInit() {
  }

}`

The parent component: ParentComponent
`import { Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-parent',
  template: '
....
    <app-terms-edit [content]="editorData.content" [title]="editorData.title"></app-terms-edit>
....',
  styleUrls: ['./parent.component.css']
})
export class ParentComponent implements OnInit {

  editorData = {};
  constructor() { }

  ngOnInit() {
  }

  handleDataEmit = data => {
    this.editorData = data;
    // I logged this.editorData here and everything works fine
  }

}`

**Comment by Goutam192002** [comment]
Nevermind I found a workaround

**Comment by fromage9747** [comment]
@Goutam192002 What was your workaround?  I am trying to insert data from a database that was saved previously for editing but I error out whenever it tries to load ckeditor

**Comment by Samandcode** [comment]
> @Goutam192002 What was your workaround? I am trying to insert data from a database that was saved previously for editing but I error out whenever it tries to load ckeditor

Hey there, Did you later find a fix? If you did please help a brother out here
