### ISSUE TITLE
Big document block typing

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5-angular#82]
For performance issues, specially in big documents, I think the code below should be modified:
https://github.com/ckeditor/ckeditor5-angular/blob/63c0073f2683669b69cdaef593a1257816ba4599/src/ckeditor/ckeditor.component.ts#L258-L268

I would suggest the following:
```
modelDocument.on( 'change:data', ( evt: CKEditor5.EventInfo<'change:data'> ) => {
 	this.ngZone.run( () => {
 		if ( this.cvaOnChange ) {
 			const data = editor.getData(); 
 			this.cvaOnChange( data );
 		}
  
 		this.change.emit( { event: evt, editor } );
 	} );
 } );
```
Getting the data(`getData()`) only when it is necessary.

**Comment by dkrahn** [comment]
Hi @ma2ciek, I found this performance issue and did the PR #83 to fix it. Did I do it correctly?

**Comment by ma2ciek** [comment]
H1 @dkrahn

Thanks for the detailed issue and PR! This change makes sense indeed, it's a pity that I overlooked it. I'll add one test to your PR and will merge it.

**Comment by ma2ciek** [comment]
I'll try to release it soon.

**Comment by dkrahn** [comment]
Thanks for the great work you all are doing!!!
