### ISSUE TITLE
Unable to use ckeditor in ngFor

### ISSUE THREAD

**Issue by samilywang** [ckeditor/ckeditor5-angular#85]
When I try to use ckeditor inside ngFor, it reports an error below.
![image](https://user-images.githubusercontent.com/13418696/55710792-f60b5500-5a1d-11e9-9ce7-46ff68ae855d.png)

My HTML Code is below:
![image](https://user-images.githubusercontent.com/13418696/55712441-551e9900-5a21-11e9-8f24-189e908378b6.png)

How can I solve this error?

**Comment by Mgsy** [comment]
@ma2ciek, could you take a look at this one?

**Comment by ma2ciek** [comment]
I'll take a look at it.

**Comment by ma2ciek** [comment]
I've tested it a little bit and I've found a few bugs... (https://github.com/ckeditor/ckeditor5-angular/issues/86) 😞 I've not reproduced this one, but one of them might be connected.

**Comment by ma2ciek** [comment]
Could you provide additional information about your snippet - are those `<ckeditor>` components wrapped in the `<form>` or not?

**Comment by samilywang** [comment]
Oh, sorry. I have found out that this error is caused by another ckeditor outside the ngFor and I have solved it.

Thanks for help anyway. 😄
