### ISSUE TITLE
How to make this Component render Editor styles

### ISSUE THREAD

**Issue by lidibe** [ckeditor/ckeditor5-angular#87]
Dear Team,

I'm using ckeditor 5 (classic) with Angular 6. The editor is placed under a mat-tab. However, the actions to the editor menu items "Bold", "Italic" does not have any effect on the display even though the console the text with "strong" or "i" tags.

<p><strong>example</strong></p>

image link https://pasteboard.co/I9wudb2.png

Does anyone face this issue before?

Thanks in advance for your help.

**Comment by ma2ciek** [comment]
Hi @lidibe,

Could you describe step-by-step how to reproduce the issue?

**Comment by lidibe** [comment]
Hi @ma2ciek ,

Thanks for replying.

I have installed the package and also the ckeditor 5 classic build

1. app.module.ts
`...
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    SharedModule,
    ApplicationRoutingModule,
    ReactiveFormsModule,
    MatInputModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressSpinnerModule,
    CKEditorModule,
  ],
....`

2. app.component.ts

`...
import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';


@Component({
  selector: 'app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  encapsulation: ViewEncapsulation.None
})

....

public Editor = ClassicEditor;

`


3. app.component.html

`
....

<mat-tab label="Borrower Request">

              <br />
              <br />

              <h4 mat-dialog-title style="color: #00736e;">Borrower Request</h4>

              <br />
              <br />


            <ckeditor id="editor" tagName="textarea" style="border: 1px solid #00736e; width: 100%;" [(ngModel)]="data" [editor]="Editor" name="_data"></ckeditor>

          </mat-tab>
`

**Comment by lidibe** [comment]
Hi @ma2ciek 

Have you managed to reproduce?

L

**Comment by lidibe** [comment]
Hi @ma2ciek ,

Any update?

L.

**Comment by ma2ciek** [comment]
I followed your steps and didn't reproduce the issue. The editor inside tabs has been working fine for me.

See https://github.com/ma2ciek/ckeditor5-angular-test/tree/t/87.
