### ISSUE TITLE
How to define a Base64 file upload?

### ISSUE THREAD

**Issue by diedona** [ckeditor/ckeditor5-angular#88]
Hello,

I'm using the ckeditor5 with Angular 7 for the first time. I have seen this topic about how to upload the images in Base64 format (https://github.com/ckeditor/ckeditor5/issues/1378 - specifically this gist: https://gist.github.com/f1ames/f0d154e2a1fbeefcac5bb4dff20920ec) but i don't follow where to use this code in my environment.

I tried to add it as a separated .ts and import it in the project, but it didn't work (at best i got that i duplicated modules).

Can someone point me to the right direction?

**Comment by diedona** [comment]
i was able to make it work (https://github.com/diedona/angular-ckeditor-test) but i had to tweek somethings. Is this the intended way?

**Comment by ma2ciek** [comment]
Hi @diedona!

This gist imports source files from CKEditor so to make it work you should create a [custom build first](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) outside of the Angular project. Then add to this build the [Custom upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html) and after bundling the custom editor outside of the Angular app you can copy the generated `ckeditor.js` file to the Angular project and use it. It's because we don't officially support [building from source in the Angular ecosystem yet](https://github.com/ckeditor/ckeditor5-angular/issues/26).

Hope it will help you :)

**Comment by diedona** [comment]
thanks for the promp reply @ma2ciek. I was able to make it work by making some changes in the gist, like so: https://gist.github.com/diedona/16444e367c069b8b7639b85899b957f7

Then i placed the file in my solution:
![image](https://user-images.githubusercontent.com/3251917/56034247-34925f80-5cfd-11e9-8400-51806b9a47c0.png)

Called it in as a extraplugin:
![image](https://user-images.githubusercontent.com/3251917/56034350-77543780-5cfd-11e9-9ba9-0434805c2e1c.png)

![image](https://user-images.githubusercontent.com/3251917/56034385-8fc45200-5cfd-11e9-8266-cb474ced2242.png)

And it works like a charm! All using the decoupled editor build. Seems like a workaround, but suits me very nice right now and might help others.

**Comment by ma2ciek** [comment]
Oh, now your gist is perfectly fine and that approach should be the easiest solution to that problem. I overlooked that these imports can be omitted. Good job 👍

**Comment by diedona** [comment]
@puru101 your path in the import should be relative from your component calling it. In my example i created a custom path (tsconfig.json, key "paths"), but you don't need it.

If your component is inside the folder "/app", you should import it as:

`import Base64Upload from ../ckeditor/Base64Upload`

For a functional example, check my github (https://github.com/diedona/angular-ckeditor-test/tree/master/src/app) it does not use custom name paths

**Comment by puru101** [comment]
> @puru101 your path in the import should be relative from your component calling it. In my example i created a custom path (tsconfig.json, key "paths"), but you don't need it.
> 
> If your component is inside the folder "/app", you should import it as:
> 
> `import Base64Upload from ../ckeditor/Base64Upload`
> 
> For a functional example, check my github (https://github.com/diedona/angular-ckeditor-test/tree/master/src/app) it does not use custom name paths

Thanks, @diedona , Yes it's working for me.

**Comment by puru101** [comment]
@diedona, as per your suggestion I am able to integrate base64 plugins in angular. But when insert image and try to get data it's through 
Error:  my-editor.component.ts:37 Log error TypeError: Cannot read property 'getData' of undefined

![image](https://user-images.githubusercontent.com/12029123/56421775-cda71480-62c1-11e9-9e17-034c852df4cc.png)

Here is a code which is used to get an editor data:
![image](https://user-images.githubusercontent.com/12029123/56421842-18c12780-62c2-11e9-8eda-3f9a13c15c18.png)

Could you please suggest me to fetch data from the editor.

Thanks,
Purushottam

**Comment by venkateshwarans** [comment]
> Hi @diedona!
> 
> This gist imports source files from CKEditor so to make it work you should create a [custom build first](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) outside of the Angular project. Then add to this build the [Custom upload adapter](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html) and after bundling the custom editor outside of the Angular app you can copy the generated `ckeditor.js` file to the Angular project and use it. It's because we don't officially support [building from source in the Angular ecosystem yet](https://github.com/ckeditor/ckeditor5-angular/issues/26).
> 
> Hope it will help you :)

Hi, When can we expect an official support for Angular2+ to build from source?  Is it in the pipeline?

**Comment by bharathnallamothu** [comment]
> thanks for the promp reply @ma2ciek. I was able to make it work by making some changes in the gist, like so: https://gist.github.com/diedona/16444e367c069b8b7639b85899b957f7
> 
> Then i placed the file in my solution:
> ![image](https://user-images.githubusercontent.com/3251917/56034247-34925f80-5cfd-11e9-8400-51806b9a47c0.png)
> 
> Called it in as a extraplugin:
> ![image](https://user-images.githubusercontent.com/3251917/56034350-77543780-5cfd-11e9-9ba9-0434805c2e1c.png)
> 
> ![image](https://user-images.githubusercontent.com/3251917/56034385-8fc45200-5cfd-11e9-8266-cb474ced2242.png)
> 
> And it works like a charm! All using the decoupled editor build. Seems like a workaround, but suits me very nice right now and might help others.

awesome work man .... ......just works like charm

**Comment by fromage9747** [comment]
Thank you thank you Thank you thank you Thank you thank you!  I spent a whole day on this trying to do the custom builds and none of it worked!  This worked first time! Thank you thank you!

**Comment by nevraydin** [comment]
> @diedona, as per your suggestion I am able to integrate base64 plugins in angular. But when insert image and try to get data it's through
> Error: my-editor.component.ts:37 Log error TypeError: Cannot read property 'getData' of undefined
> 
> ![image](https://user-images.githubusercontent.com/12029123/56421775-cda71480-62c1-11e9-9e17-034c852df4cc.png)
> 
> Here is a code which is used to get an editor data:
> ![image](https://user-images.githubusercontent.com/12029123/56421842-18c12780-62c2-11e9-8eda-3f9a13c15c18.png)
> 
> Could you please suggest me to fetch data from the editor.
> 
> Thanks,
> Purushottam

You can use `ngModelChange`.

HTML
```
<ckeditor [editor]="Editor"
              [(ngModel)]="TextValue"
              (ngModelChange)="TextValueChange($event)"></ckeditor>
```

Component

```
public TextValue: string;
public TextValueChange(value: any): void {
        console.log(value);
    }
```

**Comment by id1945** [comment]
**This is better**
https://stackblitz.com/edit/ngx-summernote
