### ISSUE TITLE
BalloonEditor - Module duplicated

### ISSUE THREAD

**Issue by M-Blobby** [ckeditor/ckeditor5-angular#91]
Hello,

With the balloonEditor I see the following console error :
ckeditor.js:5 ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

After switch to the classicEditor, all works like a charm. Do you have any clue to resolve this error ?

**Comment by ma2ciek** [comment]
Hi!

I guess that you cloned this repository and tried to use a different editor? We import that editor two times in our samples, probably that's why you get this error.

1. demo-form/demo-form-component.ts
2. simple-usage/simple-usage/component.ts

If that's not your case, please fill your post with steps to reproduce the issue.

**Comment by M-Blobby** [comment]
Thanks a lot for your answer .

No, I didn't clone this repo. I installed  directly in my angular project. Here my dependencies in my package.json about ckEditor :
```
"@ckeditor/ckeditor5-angular": "^1.0.1",
"@ckeditor/ckeditor5-build-balloon": "^12.1.0",
"@ckeditor/ckeditor5-build-classic": "^12.0.0",
"@ckeditor/ckeditor5-build-inline": "^12.0.0",
"@ckeditor/ckeditor5-highlight": "^11.0.0",
```

Next I added CKEditorModule into my module, and in my component.ts :

`import * as BalloonEditor from '@ckeditor/ckeditor5-build-balloon';`

`description = BalloonEditor;`

And in my html :
`<ckeditor [editor]="description" data="<p>Hello, world!</p>"></ckeditor>`

And the error is displayed in the browser's console. If I replace with ClassicEditor, so with my component.ts :
`import * as ClassicEditor from '@ckeditor/ckeditor5-build-classic';`

`description = ClassicEditor;`

I don't see any error.

**Comment by ma2ciek** [comment]
You can't add any package to the existing build, it's forbidden because it leads to code duplication, that's why the error shows up. And for Angular, unfortunately, the only way to build custom editor is to follow the https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html guide and then add built editor to the Angular app.

IDK why it doesn't happen in case of ClassicEditor.

**Comment by M-Blobby** [comment]
Ah yes ... I understand now ...

Thank you very much for your explanation :) .

**Comment by hoango7604** [comment]
> IDK why it doesn't happen in case of ClassicEditor.
Actually it does. I am currently working with ClassicEditor from ckeditor5-build-classic and Base64UploadAdapter from ckeditor5-upload/src/base64uploadadapter and it happens to be some modules are duplicated, so I have to implement a custom upload adapter

**Comment by ma2ciek** [comment]
Hi @hoango7604,

Could you provide more information?

**Comment by sohaieb** [comment]
Hi, @ma2ciek  ,
I support what @hoango7604  said, 
I'm working with **DecoupledEditor** , and I find the same problem of the duplicated module after installing the **Base64UploadAdapter** in my Angular project .
Idk if I installed it correctly, but what i did is that I followed the official documentation .
I hope you answer as as possible as soon to fix this problem .
thank you :)

**Comment by SilinaGeorge** [comment]
Hi,
I'm also experiencing the same problem working with inlineditor and Base64UploadAdapter
when I am importing both into a component

`import  InlineEditor from '@ckeditor/ckeditor5-build-inline'`
`import Base64UploadAdapter from '@ckeditor/ckeditor5upload/src/adapters/base64uploadadapter';`

**Comment by raso03031983** [comment]
I have problems using the base64 image plugin. Does anyone know what it would be like to do a custom build?

**Comment by ma2ciek** [comment]
All is described in the https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html guide.

**Comment by raso03031983** [comment]
Thanks for listening. I had already taken a look at the link that you spent more and made even more doubts. I downloaded the project separately and includes the plugin I wanted. But after which procedure to follow to work in an application using "reactJS" ??

**Comment by ma2ciek** [comment]
>  But after which procedure to follow to work in an application using "reactJS" ??

This is a guide for Angular ;) For the React integration see https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds.

**Comment by raso03031983** [comment]
Sorry if I'm asking dumb questions but my doubt would be to use the plugin "base64uploadadapter" the rest is already working on the project. I am getting the error of duplicate components and for my research I will have to do something customizable and found nothing in the documentation regarding it in the documentation

**Comment by raso03031983** [comment]
This excerpt ( https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds ) in the documentation was not very explanatory.  
I have also looked at other links you mentioned in another part of the forum
