### ISSUE TITLE
set editor's min-height via ck-editor__editable but the image would over stretch

### ISSUE THREAD

**Issue by anysunflower** [ckeditor/ckeditor5-angular#92]
Hi, I would like to report an issue about the editor height style setting.
When I use ```<ckeditor [editor]="Editor" ></ckeditor>``` I hope I can set up the editor's min-height, so I follow the step in the doc:
[CKEditor-angular:Setting the height via the component stylesheet](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#setting-the-height-via-the-component-stylesheet)

It work, but came along with another question,when I insert an image in the editor,the image would show like that:
![2019-04-16 15-55-44 的屏幕截图](https://user-images.githubusercontent.com/40011822/56192220-81a96500-6060-11e9-8fba-8b6e61527707.png)

The image caption size would  stretch to fill the **min-height**, this kind of  make user hard to edit after insert an image.

I have no idea about how could I set the ```min-height```of the editor and set the image caption with the common height at the same time.

It would be much appreciate If anyone have a good solution

**Comment by ma2ciek** [comment]
Hi @anysunflower!

The problem here is that the editor caption also is an editor itself, that's why it's so big. I see that we have a small error in docs. you can use for now the style below and we'll try to update docs soon.

```css
:host ::ng-deep .ck-editor__editable:not(.ck-editor__nested-editable) {
    min-height: 500px !important;
}
```

Ref: https://stackoverflow.com/questions/52485000/how-to-set-ckeditor-5-height/52485082#52485082

Personally speaking, I don't like this `:not` part, maybe we can figure out something else.

**Comment by anysunflower** [comment]
@ma2ciek 
this works well,thank you so much for the speedy reply :+1:

**Comment by Reinmar** [comment]
Eee... if nested editables have the same class, then how can https://stackoverflow.com/questions/46559354/how-to-set-the-height-of-ckeditor-5-classic-editor have 50 upvotes? :O How could we miss that?

We need to fix this on SO, in our docs and wherever else we've made that mistake.

**Comment by ma2ciek** [comment]
I'd mark it as a DUP of a https://github.com/ckeditor/ckeditor5/issues/1708 which is a more accurate issue.
