### ISSUE TITLE
Support for Reactive Forms

### ISSUE THREAD

**Issue by suyash01** [ckeditor/ckeditor5-angular#93]
Is there support for Reactive Forms or is there any plan to support it?

**Comment by Mgsy** [comment]
cc @ma2ciek

**Comment by ma2ciek** [comment]
Yep, we support it, the `CKEditorComponent` implements the `ControlValueAccessor` interface, so you can use [`ngModel`](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html#integration-with-ngmodel), `formControlName`, and so on.
