### ISSUE TITLE
Update `ng-buildr` to `ng generate library`

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-angular#96]
The `ng-buildr` package is now internally used by the `ng generate library` command. Since it's a more "official" way to build Angular libs we can change it.

**Comment by ma2ciek** [comment]
Note to myself: https://angular.io/guide/creating-libraries.

**Comment by pomek** [comment]
I do not understand the ROI of it. So far, the Angular integration works and I do not think we need to redesign the entire repository.
