### ISSUE TITLE
CKEditor no longer showing data from formControlName

### ISSUE THREAD

**Issue by Alexander-Fuchs** [ckeditor/ckeditor5-angular#97]
Before i updated to the 1.1.0 it was possible to pass the form field data via formControlName to the CKEditor.
Today i updated to this new version and all editors are no longer taking data from formControlName (you cannot see it in the editor).
They only pass the data back to the formControl.

Used Angular Version: 7.2.14
Last working version for me: 1.0.1

**Comment by Mgsy** [comment]
Hi, could you check whether your console contains some errors?

**Comment by Alexander-Fuchs** [comment]
Hi! There was no errors, it failed in silence. I now went back to 1.0.1 and everything is working again... Tell me how i can help you to fix this. :)

**Comment by Mgsy** [comment]
Thanks for the information! 

@ma2ciek, could you investigate this problem?

**Comment by dkrahn** [comment]
Hi @ma2ciek, @Mgsy, @Alexander-Fuchs 
I added a pull request with a new demo using formControlName.
For me it worked out just fine.
Hope it will help.

**Comment by ma2ciek** [comment]
Hi @dkrahn, @Alexander-Fuchs.

I'm not sure if any recent commit could change the behavior in the app. I'll check the PR (thanks @dkrahn for it!) and see whether all works fine.

**Comment by ktwbc** [comment]
also getting this same behaviour, reverting to 1.0.1 worked.

**Comment by ma2ciek** [comment]
Hi @ktwbc, @Alexander-Fuchs,

Could you describe step-by-step how to reproduce the issue? And have you looked at the https://github.com/ckeditor/ckeditor5-angular/pull/98, which shows how the `formControlName` can be used together with `<ckeditor>` component?

**Comment by FrauleinGela** [comment]
Hi. After updating to the new version 1.1.0 I got the same weird behavior too. I have also tested using the following demo example and the value is not displayed in the editor. 
Does it only work with  CKEditor 5 `v12.1.0.` ?
I am using CkEditor `v11.0.2`,  `Angular Version: 7.2`.
Reverting to 1.0.1, which perfectly works.

**Comment by ma2ciek** [comment]
Hi @FrauleinGela, could you provide a repository when the error can be reproduced? Otherwise, I won't be able to help.

**Comment by gmarab** [comment]
The error occurs if the field name contains an underscore...

**Comment by ma2ciek** [comment]
> The error occurs if the field name contains an underscore...

It sounds weird. Have you tried to reproduce it on the latest version? (1.1.2)

**Comment by gmarab** [comment]
It seems strange to me, too.
But I tried to change the field name by removing the underscore and it worked.
I'm working in Angular 8 with version 1.1.2
Using formControl works.
I try as soon as possible to replicate the situation in a dedicated repository.
